//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class HUBComponentGestureRecognizer;

@protocol HUBGestureRecognizerSynchronizing
- (_Bool)gestureRecognizerShouldBeginHandlingTouches:(HUBComponentGestureRecognizer *)arg1;
- (void)gestureRecognizerDidFinishHandlingTouches:(HUBComponentGestureRecognizer *)arg1;
- (void)gestureRecognizerDidBeginHandlingTouches:(HUBComponentGestureRecognizer *)arg1;
@end

