//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class UIView;

@interface MSAPersistentTouchInfo : NSObject <NSCopying>
{
    _Bool _alreadyMoved;
    _Bool _lastEventWasDispatched;
    float _dx;
    float _dy;
    int _tapCount;
    int _uniqueTouchID;
    UIView *_activeView;
    UIView *_hitTestView;
    double _timestamp;
    long long _lastEvent;
    long long _numberOfTouchesForEvent;
    struct CGPoint _startTouchPoint;
    struct CGPoint _endTouchPoint;
    struct CGPoint _currentTouchPoint;
    struct CGPoint _locationInScreen;
    struct CGPoint _startLocationInScreen;
}

@property(nonatomic) _Bool lastEventWasDispatched; // @synthesize lastEventWasDispatched=_lastEventWasDispatched;
@property(nonatomic) _Bool alreadyMoved; // @synthesize alreadyMoved=_alreadyMoved;
@property(nonatomic) long long numberOfTouchesForEvent; // @synthesize numberOfTouchesForEvent=_numberOfTouchesForEvent;
@property(nonatomic) long long lastEvent; // @synthesize lastEvent=_lastEvent;
@property(nonatomic) int uniqueTouchID; // @synthesize uniqueTouchID=_uniqueTouchID;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) int tapCount; // @synthesize tapCount=_tapCount;
@property(nonatomic) float dy; // @synthesize dy=_dy;
@property(nonatomic) float dx; // @synthesize dx=_dx;
@property(nonatomic) struct CGPoint startLocationInScreen; // @synthesize startLocationInScreen=_startLocationInScreen;
@property(nonatomic) struct CGPoint locationInScreen; // @synthesize locationInScreen=_locationInScreen;
@property(nonatomic) struct CGPoint currentTouchPoint; // @synthesize currentTouchPoint=_currentTouchPoint;
@property(nonatomic) struct CGPoint endTouchPoint; // @synthesize endTouchPoint=_endTouchPoint;
@property(nonatomic) struct CGPoint startTouchPoint; // @synthesize startTouchPoint=_startTouchPoint;
@property(retain, nonatomic) UIView *hitTestView; // @synthesize hitTestView=_hitTestView;
@property(retain, nonatomic) UIView *activeView; // @synthesize activeView=_activeView;
- (void).cxx_destruct;
- (id)description;
- (_Bool)isSameTouchAs:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithID:(int)arg1;

@end

