//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (BMWAppKit)
+ (id)dateWithDateGaugeValue:(long long)arg1;
+ (id)dateWithTimeGaugeValue:(long long)arg1;
- (long long)dateGaugeValue;
- (long long)timeGaugeValue;
@end

