//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GLUEStyle.h"

@class GLUELabelStyle, NSString, SPTArtistAboutGlobalChartPositionViewStyle, SPTArtistAboutMonthlyListenersViewStyle, UIColor;

@interface SPTArtistAboutPreviewViewStyle : NSObject <GLUEStyle>
{
    double _viewHeight;
    UIColor *_backgroundColor;
    GLUELabelStyle *_biographyLabelStyle;
    SPTArtistAboutMonthlyListenersViewStyle *_monthlyListenersViewStyle;
    SPTArtistAboutGlobalChartPositionViewStyle *_globalChartPositionViewStyle;
}

@property(copy, nonatomic) SPTArtistAboutGlobalChartPositionViewStyle *globalChartPositionViewStyle; // @synthesize globalChartPositionViewStyle=_globalChartPositionViewStyle;
@property(copy, nonatomic) SPTArtistAboutMonthlyListenersViewStyle *monthlyListenersViewStyle; // @synthesize monthlyListenersViewStyle=_monthlyListenersViewStyle;
@property(copy, nonatomic) GLUELabelStyle *biographyLabelStyle; // @synthesize biographyLabelStyle=_biographyLabelStyle;
@property(copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) double viewHeight; // @synthesize viewHeight=_viewHeight;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

