//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTShowsFormatCellImageLoadingContext.h"

@interface SPTAttributedCellImageLoadingContext : SPTShowsFormatCellImageLoadingContext
{
}

- (id)cellForUpdatingInCollectionView:(id)arg1;
- (void)setImage:(id)arg1 forCellInCollectionView:(id)arg2 animated:(_Bool)arg3;
- (void)setImage:(id)arg1 animated:(_Bool)arg2;

@end

