//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SPTBannerItem;

@protocol SPTBannerPresentationManagerTicket <NSObject>
@property(readonly, nonatomic) SPTBannerItem *bannerItem;
@property(readonly, nonatomic) long long status;
@end

