//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPAction.h"

@class NSString, NSURL;

@interface SPTContextMenuSpeedControlAction : SPAction
{
    NSString *_logEventName;
    id <SPTPodcastSpeedControlManager> _speedControlManager;
    id <SPTUIPresentationService> _presentationService;
    NSURL *_episodeURI;
    id <SPTLogCenter> _logCenter;
}

@property(retain, nonatomic) id <SPTLogCenter> logCenter; // @synthesize logCenter=_logCenter;
@property(retain, nonatomic) NSURL *episodeURI; // @synthesize episodeURI=_episodeURI;
@property(nonatomic) __weak id <SPTUIPresentationService> presentationService; // @synthesize presentationService=_presentationService;
@property(retain, nonatomic) id <SPTPodcastSpeedControlManager> speedControlManager; // @synthesize speedControlManager=_speedControlManager;
- (id)logEventName;
- (void).cxx_destruct;
- (void)logSpeedControlSelected;
- (id)execute:(id)arg1;
- (id)image;
- (id)title;
- (id)initWithPodcastSpeedControlManager:(id)arg1 presentationService:(id)arg2 episodeURI:(id)arg3 logContext:(id)arg4 logCenter:(id)arg5;

@end

