//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTArtistEntity.h"

@class NSString, NSURL;

@interface SPTContributingArtistsTestArtistEntityImplementation : NSObject <SPTArtistEntity>
{
    NSString *_name;
    NSURL *_uri;
    id <SPTArtistImage> _image;
    id <SPTArtistImage> _headerImage;
    NSString *_fileId;
}

+ (id)provideTestArtistEntities:(unsigned long long)arg1;
@property(retain, nonatomic) NSString *fileId; // @synthesize fileId=_fileId;
@property(readonly, nonatomic) id <SPTArtistImage> headerImage; // @synthesize headerImage=_headerImage;
@property(readonly, nonatomic) id <SPTArtistImage> image; // @synthesize image=_image;
@property(readonly, nonatomic) NSURL *uri; // @synthesize uri=_uri;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithName:(id)arg1 URI:(id)arg2 imageURL:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

