//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTPlayerObserver.h"
#import "SPTPodcastPlayer.h"

@class NSString, NSURL, SPTPlayerState;

@interface SPTDefaultPodcastPlayer : NSObject <SPTPlayerObserver, SPTPodcastPlayer>
{
    id <SPTPodcastPlayerDelegate> _delegate;
    id <SPTPlayer> _player;
    NSURL *_currentlyPlayingTrack;
    SPTPlayerState *_lastState;
}

@property(retain, nonatomic) SPTPlayerState *lastState; // @synthesize lastState=_lastState;
@property(retain, nonatomic) NSURL *currentlyPlayingTrack; // @synthesize currentlyPlayingTrack=_currentlyPlayingTrack;
@property(retain, nonatomic) id <SPTPlayer> player; // @synthesize player=_player;
@property(nonatomic) __weak id <SPTPodcastPlayerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isPaused) _Bool paused;
- (id)restrictionsForPodcasts;
- (_Bool)isActiveContextURI:(id)arg1;
- (_Bool)isActiveEpisodeURL:(id)arg1 inEntityURL:(id)arg2;
- (void)player:(id)arg1 stateDidChange:(id)arg2 fromState:(id)arg3;
- (void)playPodcast:(id)arg1 withEpisodes:(id)arg2 startEpisodeUrl:(id)arg3 fromTimestamp:(id)arg4 resetPlay:(_Bool)arg5 reverseOrder:(_Bool)arg6;
- (void)pausePodcast:(id)arg1 startEpisodeUrl:(id)arg2;
@property(readonly, nonatomic) _Bool isPlayingPodcastEpisode;
@property(readonly, nonatomic) double currentTrackProgress;
@property(readonly, nonatomic) NSURL *lastStateContextURI;
- (id)initWithPlayer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

