//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTableViewController.h"

#import "SPTDailyMixEntityViewModelDelegate.h"
#import "SPTImageLoaderDelegate.h"
#import "SPTNavigationControllerNavigationBarState.h"
#import "SPTPageController.h"

@class NSMutableDictionary, NSString, NSURL, SPTDailyMixEntityViewModel, SPTEntityTableHeaderView, SPTInfoView, SPTProgressView, SPTTheme, UIView;

@interface SPTDailyMixEntityViewController : SPTableViewController <SPTDailyMixEntityViewModelDelegate, SPTImageLoaderDelegate, SPTNavigationControllerNavigationBarState, SPTPageController>
{
    SPTDailyMixEntityViewModel *_model;
    SPTTheme *_theme;
    id <SPTImageLoader> _imageLoader;
    SPTProgressView *_progressView;
    SPTInfoView *_errorView;
    UIView *_blankView;
    SPTEntityTableHeaderView *_headerView;
    NSMutableDictionary *_headerImages;
    id <SPTUpsellManager> _upsellManager;
}

@property(readonly, nonatomic) __weak id <SPTUpsellManager> upsellManager; // @synthesize upsellManager=_upsellManager;
@property(retain, nonatomic) NSMutableDictionary *headerImages; // @synthesize headerImages=_headerImages;
@property(retain, nonatomic) SPTEntityTableHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UIView *blankView; // @synthesize blankView=_blankView;
@property(retain, nonatomic) SPTInfoView *errorView; // @synthesize errorView=_errorView;
@property(retain, nonatomic) SPTProgressView *progressView; // @synthesize progressView=_progressView;
@property(readonly, nonatomic) id <SPTImageLoader> imageLoader; // @synthesize imageLoader=_imageLoader;
@property(readonly, nonatomic) SPTTheme *theme; // @synthesize theme=_theme;
@property(readonly, nonatomic) SPTDailyMixEntityViewModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=spt_pageIdentifier) NSString *pageIdentifier;
@property(readonly, nonatomic, getter=spt_pageURI) NSURL *pageURI;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)playButtonTouchedUpInside:(id)arg1;
- (unsigned long long)preferredNavigationBarState;
- (void)imageLoader:(id)arg1 didLoadImage:(id)arg2 forURL:(id)arg3 loadTime:(double)arg4 context:(id)arg5;
- (void)scrollViewDidScroll:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;
- (void)radioEntityViewModelDidStopPlaying:(id)arg1;
- (void)radioEntityViewModelDidLoad:(id)arg1;
- (void)radioEntityViewModelDidBeginPlaying:(id)arg1;
- (void)radioEntityViewModel:(id)arg1 didLoadPlayerContext:(id)arg2 forRadioURI:(id)arg3;
- (void)radioEntityViewModel:(id)arg1 didFailToLoadWithError:(id)arg2;
- (void)radioEntityViewModel:(id)arg1 didChangeTrack:(id)arg2;
- (void)radioEntityViewModel:(id)arg1 didChangeCurrentRadioURI:(id)arg2;
- (void)configureCell:(id)arg1 forTrack:(id)arg2;
- (void)loadCurrentContext;
- (id)initWithModel:(id)arg1 theme:(id)arg2 imageLoader:(id)arg3 upsellManager:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=spt_pageContainer) id <SPTPageContainer> pageContainer;
@property(readonly) Class superclass;

@end

