//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTExternalIntegrationSearchService.h"

@class NSString, SPTAllocationContext;

@interface SPTExternalIntegrationSearchServiceImplementation : NSObject <SPTExternalIntegrationSearchService>
{
    id <SPTExternalIntegrationSearchController> _sharedController;
    id <SPTExternalIntegrationDebugLogService> _debugLogService;
    id <SPTNetworkService> _networkService;
    id <SPTContainerService> _containerService;
}

+ (id)serviceIdentifier;
@property(readonly, nonatomic) __weak id <SPTContainerService> containerService; // @synthesize containerService=_containerService;
@property(readonly, nonatomic) __weak id <SPTNetworkService> networkService; // @synthesize networkService=_networkService;
@property(readonly, nonatomic) __weak id <SPTExternalIntegrationDebugLogService> debugLogService; // @synthesize debugLogService=_debugLogService;
- (void).cxx_destruct;
@property(readonly, nonatomic) id <SPTExternalIntegrationSearchController> sharedController; // @synthesize sharedController=_sharedController;
- (id)provideSearchController;
- (void)configureWithServices:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

