//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SPTFormatListViewModelDelegate.h"
#import "SPTNavigationControllerNavigationBarState.h"
#import "SPTPageController.h"
#import "SPViewController.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, NSURL, SPTFormatListContextMenuController, SPTFormatListView, SPTFormatListViewModel;

@interface SPTFormatListViewController : UIViewController <SPTFormatListViewModelDelegate, SPViewController, SPTNavigationControllerNavigationBarState, UITableViewDataSource, UITableViewDelegate, SPTPageController>
{
    SPTFormatListViewModel *_viewModel;
    id <SPTFormatListTableViewConfigurator> _tableViewConfigurator;
    SPTFormatListContextMenuController *_contextMenuController;
}

@property(retain, nonatomic) SPTFormatListContextMenuController *contextMenuController; // @synthesize contextMenuController=_contextMenuController;
@property(readonly, nonatomic) id <SPTFormatListTableViewConfigurator> tableViewConfigurator; // @synthesize tableViewConfigurator=_tableViewConfigurator;
@property(retain, nonatomic) SPTFormatListViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (unsigned long long)preferredNavigationBarState;
@property(readonly, nonatomic, getter=spt_pageURI) NSURL *pageURI;
@property(readonly, nonatomic, getter=spt_pageIdentifier) NSString *pageIdentifier;
@property(readonly, nonatomic) NSURL *URI;
- (void)formatListViewModel:(id)arg1 didFailToLoadFormatListModelWithError:(id)arg2;
- (void)formatListViewModel:(id)arg1 didLoadFormatListModel:(id)arg2;
- (void)formatListViewModel:(id)arg1 didChangePlaybackURI:(id)arg2 isPlaying:(_Bool)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableViewCellContextMenuButtonTapped:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithFormatListWithViewModel:(id)arg1 tableViewConfigurator:(id)arg2 contextMenuFeature:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=spt_pageContainer) id <SPTPageContainer> pageContainer;
@property(readonly) Class superclass;
@property(retain, nonatomic) SPTFormatListView *view; // @dynamic view;

@end

