//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SPTPageController.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, NSURL, SPTFeedCollectionViewCellConfigurator, SPTFeedTableViewCellConfigurator, SPTFeedViewModel, SPTLayoutConstraintBuilder, UICollectionViewCell, UIRefreshControl, UITableView, UITableViewCell;

@interface SPTFeedViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, SPTPageController>
{
    id <GLUETheme> _theme;
    id <SPTLinkDispatcher> _linkDispatcher;
    SPTLayoutConstraintBuilder *_layout;
    UITableView *_tableView;
    UIRefreshControl *_refreshControl;
    UITableViewCell *_selectedTableViewCell;
    UICollectionViewCell *_selectedCollectionViewCell;
    SPTFeedViewModel *_viewModel;
    SPTFeedTableViewCellConfigurator *_tableViewCellConfigurator;
    SPTFeedCollectionViewCellConfigurator *_collectionViewCellConfigurator;
}

@property(retain, nonatomic) SPTFeedCollectionViewCellConfigurator *collectionViewCellConfigurator; // @synthesize collectionViewCellConfigurator=_collectionViewCellConfigurator;
@property(retain, nonatomic) SPTFeedTableViewCellConfigurator *tableViewCellConfigurator; // @synthesize tableViewCellConfigurator=_tableViewCellConfigurator;
@property(retain, nonatomic) SPTFeedViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) UICollectionViewCell *selectedCollectionViewCell; // @synthesize selectedCollectionViewCell=_selectedCollectionViewCell;
@property(retain, nonatomic) UITableViewCell *selectedTableViewCell; // @synthesize selectedTableViewCell=_selectedTableViewCell;
@property(retain, nonatomic) UIRefreshControl *refreshControl; // @synthesize refreshControl=_refreshControl;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) SPTLayoutConstraintBuilder *layout; // @synthesize layout=_layout;
@property(retain, nonatomic) id <SPTLinkDispatcher> linkDispatcher; // @synthesize linkDispatcher=_linkDispatcher;
@property(retain, nonatomic) id <GLUETheme> theme; // @synthesize theme=_theme;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=spt_pageURI) NSURL *pageURI;
@property(readonly, nonatomic, getter=spt_pageIdentifier) NSString *pageIdentifier;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)applyGradientTo:(id)arg1 entity:(id)arg2 indexPath:(id)arg3;
- (void)playButtonTapped:(id)arg1;
- (void)coverButtonTapped:(id)arg1;
- (void)profileButtonTapped:(id)arg1;
- (void)refreshControlActivated;
- (void)fetchFeedData;
- (void)setupRefreshControl;
- (void)setupTableView;
- (void)updateViewConstraints;
- (void)addViewConstraints;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithViewModel:(id)arg1 tableViewCellConfigurator:(id)arg2 collectionViewCellConfigurator:(id)arg3 linkDispatcher:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=spt_pageContainer) id <SPTPageContainer> pageContainer;
@property(readonly) Class superclass;

@end

