//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTGaiaDevicesAvailableViewProvider.h"

@class NSString, SPTTheme;

@interface SPTGaiaDevicesAvailableViewFactory : NSObject <SPTGaiaDevicesAvailableViewProvider>
{
    id <SPTGaiaManager> _gaiaManager;
    SPTTheme *_theme;
}

@property(retain, nonatomic) SPTTheme *theme; // @synthesize theme=_theme;
@property(retain, nonatomic) id <SPTGaiaManager> gaiaManager; // @synthesize gaiaManager=_gaiaManager;
- (void).cxx_destruct;
- (id)createGaiaDevicesAvailableView:(_Bool)arg1;
- (id)initWithGaiaManager:(id)arg1 theme:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

