//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "EXP_HUBContentOperation.h"

@interface SPTHomeErrorHandlingContentOperation : NSObject <EXP_HUBContentOperation>
{
    _Bool _didEmitNonErrorViewModel;
    id <EXP_HUBContentOperationDelegate> _delegate;
    CDUnknownBlockType _errorPredicate;
}

@property(readonly, copy, nonatomic) CDUnknownBlockType errorPredicate; // @synthesize errorPredicate=_errorPredicate;
@property(nonatomic) _Bool didEmitNonErrorViewModel; // @synthesize didEmitNonErrorViewModel=_didEmitNonErrorViewModel;
@property(nonatomic) __weak id <EXP_HUBContentOperationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)configureOverlayForServerError:(id)arg1;
- (void)configureOverlayForOfflineError:(id)arg1;
- (void)addOverlayForError:(id)arg1 toViewModelBuilder:(id)arg2;
- (void)performForViewModelBuilder:(id)arg1 previousError:(id)arg2;
- (id)initWithErrorPredicate:(CDUnknownBlockType)arg1;

@end

