//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GLUEStyle.h"

@class GLUEButtonStyle, GLUELabelStyle, NSArray, NSString, UIColor;

@interface SPTLyricsFullScreenViewStyle : NSObject <GLUEStyle>
{
    UIColor *_backgroundColor;
    double _backgroundBlurIntensity;
    double _backgroundBlurRadius;
    NSArray *_backgroundGradientOverlayColors;
    UIColor *_backgroundTintColor;
    GLUEButtonStyle *_closeButtonStyle;
    GLUELabelStyle *_titleLabelStyle;
    GLUELabelStyle *_subtitleLabelStyle;
    UIColor *_progressBarColor;
    UIColor *_progressTrackColor;
    UIColor *_tableBackgroundColor;
    double _tableMaskFadeRatio;
    struct UIEdgeInsets _headerInset;
}

@property(nonatomic) struct UIEdgeInsets headerInset; // @synthesize headerInset=_headerInset;
@property(nonatomic) double tableMaskFadeRatio; // @synthesize tableMaskFadeRatio=_tableMaskFadeRatio;
@property(retain, nonatomic) UIColor *tableBackgroundColor; // @synthesize tableBackgroundColor=_tableBackgroundColor;
@property(retain, nonatomic) UIColor *progressTrackColor; // @synthesize progressTrackColor=_progressTrackColor;
@property(retain, nonatomic) UIColor *progressBarColor; // @synthesize progressBarColor=_progressBarColor;
@property(copy, nonatomic) GLUELabelStyle *subtitleLabelStyle; // @synthesize subtitleLabelStyle=_subtitleLabelStyle;
@property(copy, nonatomic) GLUELabelStyle *titleLabelStyle; // @synthesize titleLabelStyle=_titleLabelStyle;
@property(copy, nonatomic) GLUEButtonStyle *closeButtonStyle; // @synthesize closeButtonStyle=_closeButtonStyle;
@property(retain, nonatomic) UIColor *backgroundTintColor; // @synthesize backgroundTintColor=_backgroundTintColor;
@property(copy, nonatomic) NSArray *backgroundGradientOverlayColors; // @synthesize backgroundGradientOverlayColors=_backgroundGradientOverlayColors;
@property(nonatomic) double backgroundBlurRadius; // @synthesize backgroundBlurRadius=_backgroundBlurRadius;
@property(nonatomic) double backgroundBlurIntensity; // @synthesize backgroundBlurIntensity=_backgroundBlurIntensity;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

