//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPTLyricsTestUtils : NSObject
{
}

+ (id)lyricsResultWithPublisherAndSongwriterJSON;
+ (id)lyricsResultWithSongwriterJSON;
+ (id)lyricsResultWithPublisherJSON;
+ (id)lyricsResultWithUnknownSyncTypeJSON;
+ (id)lyricsResultWithWordSyncTypeJSON;
+ (id)lyricsResultWithTextSyncTypeJSON;
+ (id)lyricsResultWithLineSyncTypeJSON;
+ (id)invalidLyricsResultWithMissingFieldsJSON;
+ (id)validLyricsResultWithMultiLineJSON;
+ (id)validLyricsResultWithSingleLineJSON;
+ (id)emptyLyricsResultJSON;
+ (id)emptyJSON;
+ (id)emptyPayload;

@end

