//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTAbbaFeatureFlagsObserver.h"
#import "SPTFeatureFlagSignalObserver.h"
#import "SPTPodcastTestManager.h"

@class NSString, SPTObserverManager;

@interface SPTPodcastTestManagerImplementation : NSObject <SPTAbbaFeatureFlagsObserver, SPTFeatureFlagSignalObserver, SPTPodcastTestManager>
{
    _Bool _podcastFeatureEnabled;
    _Bool _videoFeatureEnabled;
    _Bool _videoEntityPagesEnabled;
    id <SPTAbbaFeatureFlags> _featureFlags;
    id <SPTLocalSettings> _localSettings;
    id <SPTProductState> _productState;
    id <SPTFeatureFlagSignal> _freeTierSignal;
    id <SPTFeatureFlagSignal> _heartsEverywhereSignal;
    SPTObserverManager *_observerManager;
    long long _freeTierState;
    long long _heartsEverywhereState;
}

@property(nonatomic) long long heartsEverywhereState; // @synthesize heartsEverywhereState=_heartsEverywhereState;
@property(nonatomic) long long freeTierState; // @synthesize freeTierState=_freeTierState;
@property(nonatomic, getter=isVideoEntityPagesEnabled) _Bool videoEntityPagesEnabled; // @synthesize videoEntityPagesEnabled=_videoEntityPagesEnabled;
@property(nonatomic, getter=isVideoFeatureEnabled) _Bool videoFeatureEnabled; // @synthesize videoFeatureEnabled=_videoFeatureEnabled;
@property(nonatomic, getter=isPodcastFeatureEnabled) _Bool podcastFeatureEnabled; // @synthesize podcastFeatureEnabled=_podcastFeatureEnabled;
@property(readonly, nonatomic) SPTObserverManager *observerManager; // @synthesize observerManager=_observerManager;
@property(readonly, nonatomic) id <SPTFeatureFlagSignal> heartsEverywhereSignal; // @synthesize heartsEverywhereSignal=_heartsEverywhereSignal;
@property(readonly, nonatomic) id <SPTFeatureFlagSignal> freeTierSignal; // @synthesize freeTierSignal=_freeTierSignal;
@property(readonly, nonatomic) id <SPTProductState> productState; // @synthesize productState=_productState;
@property(readonly, nonatomic) id <SPTLocalSettings> localSettings; // @synthesize localSettings=_localSettings;
@property(readonly, nonatomic) id <SPTAbbaFeatureFlags> featureFlags; // @synthesize featureFlags=_featureFlags;
- (void).cxx_destruct;
- (_Bool)calculateVideoEntityPagesEnabled;
- (_Bool)calculateVideoFeatureEnabled;
- (_Bool)calculatePodcastFeatureEnabled;
- (void)featureFlagSignal:(id)arg1 hasAssumedState:(long long)arg2;
- (void)featureFlagsDidChange:(id)arg1;
@property(readonly, nonatomic, getter=isPodcastYourLibrarySubmenuEnabled) _Bool podcastYourLibrarySubmenuEnabled;
@property(readonly, nonatomic, getter=isPodcastYourLibraryEnabled) _Bool podcastYourLibraryEnabled;
@property(readonly, nonatomic, getter=isPodcastEpisodeCellNewComponentEnabled) _Bool podcastEpisodeCellNewComponentEnabled;
@property(readonly, nonatomic, getter=isOfflineActionEnabled) _Bool offlineActionEnabled;
@property(readonly, nonatomic, getter=isLikeActionEnabled) _Bool likeActionEnabled;
@property(readonly, nonatomic, getter=isFollowActionEnabled) _Bool followActionEnabled;
@property(readonly, nonatomic, getter=isOnboardingTabBarTooltipTestEnabled) _Bool onboardingTabBarTooltipTestEnabled;
@property(readonly, nonatomic, getter=isOnboardingShowcaseTestEnabled) _Bool onboardingShowcaseTestEnabled;
@property(readonly, nonatomic, getter=isActionsForVideoWithAudioEnabled) _Bool actionsForVideoWithAudioEnabled;
@property(readonly, nonatomic, getter=isShowsCollectionFeatureEnabled) _Bool showsCollectionFeatureEnabled;
@property(readonly, nonatomic, getter=isPodmarksEnabled) _Bool podmarksEnabled;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)dealloc;
- (id)initWithFeatureFlags:(id)arg1 localSettings:(id)arg2 productState:(id)arg3 freeTierSignal:(id)arg4 heartsEverywhereSignal:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

