//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTService.h"

@class NSString, SPTAllocationContext, SPTSpotifyAppProtocolWakeupRemoteAudioHandler;

@interface SPTSpotifyAppProtocolUriHandlerService : NSObject <SPTService>
{
    id <SPTPlayerFeature> _playerService;
    id <SPTURIDispatchService> _URIDispatchService;
    SPTSpotifyAppProtocolWakeupRemoteAudioHandler *_wakeupRemoteAudioHandler;
}

+ (id)serviceIdentifier;
@property(retain, nonatomic) SPTSpotifyAppProtocolWakeupRemoteAudioHandler *wakeupRemoteAudioHandler; // @synthesize wakeupRemoteAudioHandler=_wakeupRemoteAudioHandler;
@property(nonatomic) __weak id <SPTURIDispatchService> URIDispatchService; // @synthesize URIDispatchService=_URIDispatchService;
@property(nonatomic) __weak id <SPTPlayerFeature> playerService; // @synthesize playerService=_playerService;
- (void).cxx_destruct;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

