//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol SPTSleepTimerEventObserver <NSObject>
- (void)timerDidCancel:(id <SPTSleepTimerController>)arg1;
- (void)timerDidEnd:(id <SPTSleepTimerController>)arg1;
- (void)timerDidStart:(id <SPTSleepTimerController>)arg1;
@end

