//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SPTUpsellQAToolShowcaseSlateController, UIImage;

@protocol SPTUpsellQAToolShowcaseSlateControllerDelegate <NSObject>
- (void)didChangeQAToolShowcaseSlatePosition:(SPTUpsellQAToolShowcaseSlateController *)arg1 accepted:(_Bool)arg2;
- (void)didDismissQAToolShowcaseSlate:(SPTUpsellQAToolShowcaseSlateController *)arg1 accepted:(_Bool)arg2 image:(UIImage *)arg3 currentDateAndTime:(NSString *)arg4;
@end

