//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GCKPB_PBGeneratedMessage.h"

@class NSString;

@interface GCKPB_PlayCeClientInfo : GCKPB_PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSString *applicationBuild; // @dynamic applicationBuild;
@property(retain, nonatomic) NSString *clientId; // @dynamic clientId;
@property(retain, nonatomic) NSString *country; // @dynamic country;
@property(nonatomic) _Bool hasApplicationBuild; // @dynamic hasApplicationBuild;
@property(nonatomic) _Bool hasClientId; // @dynamic hasClientId;
@property(nonatomic) _Bool hasCountry; // @dynamic hasCountry;
@property(nonatomic) _Bool hasLoggingId; // @dynamic hasLoggingId;
@property(nonatomic) _Bool hasMake; // @dynamic hasMake;
@property(nonatomic) _Bool hasModel; // @dynamic hasModel;
@property(nonatomic) _Bool hasPlatformVersion; // @dynamic hasPlatformVersion;
@property(retain, nonatomic) NSString *loggingId; // @dynamic loggingId;
@property(retain, nonatomic) NSString *make; // @dynamic make;
@property(retain, nonatomic) NSString *model; // @dynamic model;
@property(retain, nonatomic) NSString *platformVersion; // @dynamic platformVersion;

@end

