//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GCKPB_PBGeneratedMessage.h"

@class NSString;

@interface GCKPB_LOGS_MessageDetails_Type : GCKPB_PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasLogType; // @dynamic hasLogType;
@property(nonatomic) _Bool hasSourceType; // @dynamic hasSourceType;
@property(retain, nonatomic) NSString *logType; // @dynamic logType;
@property(retain, nonatomic) NSString *sourceType; // @dynamic sourceType;

@end

