//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GCKPB_PBGeneratedMessage.h"

@class GCKPB_PBMutableArray, NSData;

@interface GCKPB_AuthResponse : GCKPB_PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSData *clientAuthCertificate; // @dynamic clientAuthCertificate;
@property(nonatomic) _Bool hasClientAuthCertificate; // @dynamic hasClientAuthCertificate;
@property(nonatomic) _Bool hasHashAlgorithm; // @dynamic hasHashAlgorithm;
@property(nonatomic) _Bool hasIntermediateCertificateArray; // @dynamic hasIntermediateCertificateArray;
@property(nonatomic) _Bool hasSenderNonce; // @dynamic hasSenderNonce;
@property(nonatomic) _Bool hasSignature; // @dynamic hasSignature;
@property(nonatomic) _Bool hasSignatureAlgorithm; // @dynamic hasSignatureAlgorithm;
@property(nonatomic) int hashAlgorithm; // @dynamic hashAlgorithm;
@property(retain, nonatomic) GCKPB_PBMutableArray *intermediateCertificateArray; // @dynamic intermediateCertificateArray;
@property(retain, nonatomic) NSData *senderNonce; // @dynamic senderNonce;
@property(retain, nonatomic) NSData *signature; // @dynamic signature;
@property(nonatomic) int signatureAlgorithm; // @dynamic signatureAlgorithm;

@end

