//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GCKPB_PBGeneratedMessage.h"

@class GCKPB_PBMutableArray, NSData, NSString;

@interface GCKPB_PBUninterpretedOption : GCKPB_PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSString *aggregateValue; // @dynamic aggregateValue;
@property(nonatomic) double doubleValue; // @dynamic doubleValue;
@property(nonatomic) _Bool hasAggregateValue; // @dynamic hasAggregateValue;
@property(nonatomic) _Bool hasDoubleValue; // @dynamic hasDoubleValue;
@property(nonatomic) _Bool hasIdentifierValue; // @dynamic hasIdentifierValue;
@property(nonatomic) _Bool hasNameArray; // @dynamic hasNameArray;
@property(nonatomic) _Bool hasNegativeIntValue; // @dynamic hasNegativeIntValue;
@property(nonatomic) _Bool hasPositiveIntValue; // @dynamic hasPositiveIntValue;
@property(nonatomic) _Bool hasStringValue; // @dynamic hasStringValue;
@property(retain, nonatomic) NSString *identifierValue; // @dynamic identifierValue;
@property(retain, nonatomic) GCKPB_PBMutableArray *nameArray; // @dynamic nameArray;
@property(nonatomic) long long negativeIntValue; // @dynamic negativeIntValue;
@property(nonatomic) unsigned long long positiveIntValue; // @dynamic positiveIntValue;
@property(retain, nonatomic) NSData *stringValue; // @dynamic stringValue;

@end

