//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor, UIImage, UIImageView;

@interface IMAnimatedBackgroundView : UIView
{
    UIImageView *gradientImageView;
    UIImage *_imageOfGradientBackground;
    UIView *tintView;
    struct CGPoint centerStart;
    struct CGPoint centerStop;
    struct CGPoint scaleStart;
    struct CGPoint scaleStop;
    UIColor *tintColorStart;
    UIColor *tintColorStop;
    double tintAlphaStart;
    double tintAlphaStop;
    int currentStep;
    int totalSteps;
}

+ (Class)layerClass;
- (void).cxx_destruct;
- (void)animateToNext;
- (void)randomizeWithSeed:(unsigned int)arg1;
- (void)generateRandomValuesWithSeed:(unsigned int)arg1 preserveTint:(_Bool)arg2;
- (_Bool)performAnimationStep;
- (void)updatePositionAndScale;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)imageOfGradientBackground;

@end

