//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSMutableDictionary;

@interface IMBarButton : UIButton
{
    id frameToken;
    double height[2];
    NSMutableDictionary *stateToBackgroundImage[2];
}

- (void).cxx_destruct;
- (void)willMoveToSuperview:(id)arg1;
- (void)superviewFrameChanged:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (struct CGRect)fixFrame:(struct CGRect)arg1 forMetrics:(long long)arg2;
- (long long)metricsForSuperview:(id)arg1;
- (void)superviewFrameChanged;
- (id)backgroundImageForState:(unsigned long long)arg1 barMetrics:(long long)arg2;
- (void)setBackgroundImage:(id)arg1 forState:(unsigned long long)arg2 barMetrics:(long long)arg3;
- (double)heightForBarMetrics:(long long)arg1;
- (void)setHeight:(double)arg1 forBarMetrics:(long long)arg2;
- (void)initialize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

