//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface IMDownloadSummaryView : UIView
{
    UILabel *summaryLabel;
}

- (void).cxx_destruct;
- (id)memoryFormatter:(long long)arg1;
- (id)freeDiskSpace;
- (void)scheduleUpdateSummary;
- (void)scheduledUpdateSummary;
- (void)updateSummary;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

