//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class IMDownloadManager, IMLayout, UILabel;

@interface IMDownloadSpeedCell : UITableViewCell
{
    UILabel *label;
    IMLayout *layout;
    IMDownloadManager *downloadManager;
    double sideMargin;
}

@property(nonatomic) double sideMargin; // @synthesize sideMargin;
@property(nonatomic) __weak IMDownloadManager *downloadManager; // @synthesize downloadManager;
- (void).cxx_destruct;
- (void)update;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

