//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "IMVideoOverlayButton.h"

#import "IMGoogleCastDelegate-Protocol.h"

@class NSString;

@interface IMGoogleCastButton : IMVideoOverlayButton <IMGoogleCastDelegate>
{
    int nextAnimationStep;
}

- (void)imGoogleCastStateDidChange:(id)arg1;
- (void)updateIcon;
- (void)touchedUpInside:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

