//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "IMLayoutAction.h"

@class UIView;

@interface IMLayoutBlockAction : IMLayoutAction
{
    CDUnknownBlockType block;
    CDUnknownBlockType blockWithRect;
    UIView *view;
}

+ (id)actionForView:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
+ (id)actionWithBlock:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
- (void)perform:(id)arg1;

@end

