//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IMPlayerItem, NSString;

@protocol IMPlayerErrorHandler <NSObject>
- (void)reportError:(NSString *)arg1 forItem:(IMPlayerItem *)arg2 continue:(void (^)(void))arg3;
@end

