//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class IMScrubber;

@protocol IMScrubberDelegate

@optional
- (float)imScrubberGetHoldDelay:(IMScrubber *)arg1;
- (void)imScrubber:(IMScrubber *)arg1 cancelledAndReturnedToPosition:(float)arg2;
- (void)imScrubber:(IMScrubber *)arg1 releasedAtPosition:(float)arg2;
- (void)imScrubber:(IMScrubber *)arg1 wasHeldAtPosition:(float)arg2;
- (void)imScrubber:(IMScrubber *)arg1 dividerDidChange:(int)arg2;
- (void)imScrubber:(IMScrubber *)arg1 didMoveToPosition:(float)arg2;
- (void)imScrubberScrubbingDidBegin:(IMScrubber *)arg1;
@end

