//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IMTrackerServerAddressResolver : NSObject
{
    struct GetServerState getServerState;
}

- (void)cancel;
- (void)resolveServerAddresses:(id)arg1 remoteId:(id)arg2 succeeded:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;

@end

