//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UISwipeGestureRecognizer.h>

@class UIView;

@interface IMVideoOverlayControllerSwipeGestureRecognizer : UISwipeGestureRecognizer
{
    UIView *actualView;
}

@property(readonly, nonatomic) __weak UIView *actualView; // @synthesize actualView;
- (void).cxx_destruct;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;

@end

