//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CFNetwork/NSNetServiceBrowser.h>

@class NSString;

@interface NSNetServiceBrowser (GCKAdditions)
@property(copy, nonatomic) NSString *gck_subtype;
@end

