//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SPTUIPageService.h"

@class MISSING_TYPE;

@interface _TtC20HomeThingFeatureImpl16HomeThingService : SPTUIPageService
{
    MISSING_TYPE *networkService;
    MISSING_TYPE *remoteConfigurationService;
    MISSING_TYPE *glueService;
    MISSING_TYPE *settingsService;
    MISSING_TYPE *dispatchService;
    MISSING_TYPE *gaiaFeature;
    MISSING_TYPE *activationMobiusLoopController;
    MISSING_TYPE *configurationProperties;
    MISSING_TYPE *claimsURIs;
    MISSING_TYPE *$__lazy_storage_$_homeThingTheme;
    MISSING_TYPE *$__lazy_storage_$_settingsManager;
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
- (id)init;
- (id)provideViewControllerForURI:(id)arg1 context:(id)arg2;
- (_Bool)claimsURI:(id)arg1;
- (void)load;
- (void)configureWithServices:(id)arg1;

@end

