//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC26FullscreenStoryFeatureImpl22FullscreenStoryService : NSObject
{
    MISSING_TYPE *containerService;
    MISSING_TYPE *glueService;
    MISSING_TYPE *networkService;
    MISSING_TYPE *videoService;
    MISSING_TYPE *settingsService;
    MISSING_TYPE *presentationService;
    MISSING_TYPE *playerService;
    MISSING_TYPE *collectionPlatformService;
    MISSING_TYPE *contextMenuService;
    MISSING_TYPE *volumeService;
    MISSING_TYPE *dispatchService;
    MISSING_TYPE *coreService;
    MISSING_TYPE *eventSenderService;
    MISSING_TYPE *ubiService;
    MISSING_TYPE *fullscreenStoryViewController;
    MISSING_TYPE *$__lazy_storage_$_userDefaultsController;
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
- (id)init;
- (id)provideFullscreenStoryViewControllerWithUri:(id)arg1;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;

@end

