//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC22ConnectUIV2FeatureImpl23ConnectUIV2FlagsManager : _TtCs12_SwiftObject
{
    MISSING_TYPE *abbaFeatureFlags;
    MISSING_TYPE *remoteConfigurationResolver;
    MISSING_TYPE *abbaDesignPickerRedesignKey;
    MISSING_TYPE *abbaDesignPickerRedesignEnabledGroupKey;
    MISSING_TYPE *$__lazy_storage_$_isDevicePickerRedesignEnabled;
    MISSING_TYPE *$__lazy_storage_$_isMiniPickerEnabled;
    MISSING_TYPE *$__lazy_storage_$_isDevicePickerRedesignEnabledInABBA;
    MISSING_TYPE *$__lazy_storage_$_isDevicePickerRedesignEnabledInRemoteConfig;
    MISSING_TYPE *$__lazy_storage_$_isMiniPickerEnabledInRemoteConfig;
    MISSING_TYPE *$__lazy_storage_$_remoteConfigProperties;
    MISSING_TYPE *$__lazy_storage_$_isConnectAttachedDestinationEnabled;
    MISSING_TYPE *$__lazy_storage_$_isConnectDestinationNudgeEnabled;
}

@property(nonatomic) _Bool isConnectDestinationNudgeEnabled;
@property(nonatomic) _Bool isConnectAttachedDestinationEnabled;

@end

