//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC28PlaylistMigrationFeatureImpl23PLSponsoredCellProvider.h"

#import "SPTFreeTierPlaylistSectionDescription-Protocol.h"

@interface _TtC28PlaylistMigrationFeatureImpl23PLSponsoredCellProvider (PlaylistMigrationFeatureImpl1) <SPTFreeTierPlaylistSectionDescription>
- (void)willDisplaySection;
- (id)sectionFooter;
- (id)sectionHeader;
- (unsigned long long)numberOfRows;
- (unsigned long long)section;
@end

