//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC22QuickScrollFeatureImpl20QuickScrollIndicator : UIView
{
    MISSING_TYPE *style;
    MISSING_TYPE *label;
    MISSING_TYPE *verticalConstraint;
    MISSING_TYPE *text;
}

- (void).cxx_destruct;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

