//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCVV13SwiftProtobuf31Google_Protobuf_DescriptorProto14ExtensionRangeP33_DC8661342CA8480725FF8D5BB36F322A13_StorageClass : _TtCs12_SwiftObject
{
    MISSING_TYPE *_start;
    MISSING_TYPE *_end;
    MISSING_TYPE *_options;
}

@end

