//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC28PodcastOnboardingFeatureImpl15CurationManager.h"

#import "SPTFreeTierTasteOnboardingCurationProvider-Protocol.h"

@interface _TtC28PodcastOnboardingFeatureImpl15CurationManager (PodcastOnboardingFeatureImpl1) <SPTFreeTierTasteOnboardingCurationProvider>
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
@end

