//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC25VoiceCompanionFeatureImpl28VCSSnackCollectionViewBinder : NSObject
{
    MISSING_TYPE *collectionView;
    MISSING_TYPE *eventConsumer;
    MISSING_TYPE *recommendations;
    MISSING_TYPE *imageLoader;
    MISSING_TYPE *currentEntityPlayingURL;
}

- (void).cxx_destruct;
- (id)init;

@end

