//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC22FilterChipsFeatureImpl27FilterChipsCollectionBinder.h"

@interface _TtC22FilterChipsFeatureImpl27FilterChipsCollectionBinder (FilterChipsFeatureImpl2)
- (struct CGSize)collectionView:(id)arg1 sizeForItemAt:(id)arg2;
@end

