//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC26MarketingFormatFeatureImpl21SegmentedProgressView : UIView
{
    MISSING_TYPE *stackView;
    MISSING_TYPE *progressViews;
    MISSING_TYPE *segmentCount;
    MISSING_TYPE *currentSegment;
    MISSING_TYPE *progressTintColor;
    MISSING_TYPE *trackTintColor;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

