//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "VISREFTopAndBodyContentView.h"

@class MISSING_TYPE;

@interface _TtC35PodcastCreatorEntityPageFeatureImpl24CreatorHeaderContentView : VISREFTopAndBodyContentView
{
    MISSING_TYPE *theme;
    MISSING_TYPE *dimensions;
    MISSING_TYPE *$__lazy_storage_$_imageView;
    MISSING_TYPE *titleLabel;
    MISSING_TYPE *descriptionLabel;
    MISSING_TYPE *titleProtectionGradient;
    MISSING_TYPE *$__lazy_storage_$_statusBarProtectionGradient;
    MISSING_TYPE *viewModel;
}

- (void).cxx_destruct;
- (id)initWithNaturalHeight:(double)arg1;
- (struct CGSize)systemLayoutSizeFittingSize:(struct CGSize)arg1 withHorizontalFittingPriority:(float)arg2 verticalFittingPriority:(float)arg3;
- (void)headerViewNormalizedProgressUpdate:(double)arg1;
- (id)initWithCoder:(id)arg1;

@end

