//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC22ConnectUIV2FeatureImpl38NowPlayingBarIntegrationImplementation.h"

@interface _TtC22ConnectUIV2FeatureImpl38NowPlayingBarIntegrationImplementation (ConnectUIV2FeatureImpl)
- (void)connectConnectionStateDidChange:(long long)arg1;
- (void)connectActiveConnectionTypeDidChange:(long long)arg1;
- (void)connectAvailableDevicesDidChange:(id)arg1;
@end

