//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface GCKBWeakListenerProxy : NSObject
{
    id _listener;
}

@property(readonly, nonatomic) __weak id listener; // @synthesize listener=_listener;
- (void).cxx_destruct;
- (id)initWithListener:(id)arg1;

@end

