//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GCKDevice, NSString;

@protocol GCKDiscoveryManagerListener <NSObject>

@optional
- (void)didHaveDiscoveredDeviceWhenStartingDiscovery;
- (void)didRemoveDevice:(GCKDevice *)arg1 atIndex:(unsigned long long)arg2;
- (void)didRemoveDeviceAtIndex:(unsigned long long)arg1;
- (void)didUpdateDevice:(GCKDevice *)arg1 atIndex:(unsigned long long)arg2 andMoveToIndex:(unsigned long long)arg3;
- (void)didUpdateDevice:(GCKDevice *)arg1 atIndex:(unsigned long long)arg2;
- (void)didInsertDevice:(GCKDevice *)arg1 atIndex:(unsigned long long)arg2;
- (void)didUpdateDeviceList;
- (void)willUpdateDeviceList;
- (void)didStartDiscoveryForDeviceCategory:(NSString *)arg1;
@end

