//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GCKMDNSRecord.h"

@interface GCKMDNSDataRecord : GCKMDNSRecord
{
    unsigned int _ttl;
    unsigned short _dataLength;
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (unsigned int)getRemainingTTLUntil:(double)arg1;
- (_Bool)isDataEqualTo:(id)arg1;
- (_Bool)writeDataWith:(id)arg1;
- (_Bool)writeWith:(id)arg1 currentTime:(double)arg2;
- (_Bool)readDataWith:(id)arg1;
- (_Bool)readWith:(id)arg1;
@property(nonatomic) long long timeToLive;
- (id)initWithName:(id)arg1 type:(unsigned long long)arg2 recordClass:(unsigned short)arg3;

@end

