//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@interface GPBDoubleValue : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) double value; // @dynamic value;

@end

