//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MMKMessageStrategy.h"

@interface MMKPlayStrategy : MMKMessageStrategy
{
}

- (void)execute:(id)arg1 connection:(id)arg2 sharedSecret:(id)arg3;
- (id)supportedClassString;

@end

