//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCOREventInfo : NSObject
{
    struct EventInfo *_eventInfo;
}

- (struct EventInfo *)cppEventInfo;
- (void)addIncludedPublisher:(id)arg1;
- (void)setLabelWithName:(id)arg1 value:(id)arg2 publisherId:(id)arg3;
- (void)addLabels:(id)arg1 publisherId:(id)arg2;
- (void)setLabelWithName:(id)arg1 value:(id)arg2;
- (void)addLabels:(id)arg1;
- (id)copy;
- (void)dealloc;
- (id)initWithCppEventInfo:(struct EventInfo *)arg1;
- (id)initCopy:(id)arg1;
- (id)init;

@end

