//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SPTAsyncLoading-Protocol.h"

@class NSString, SPTProgressView;

@interface SPTAsyncLoadingView : UIView <SPTAsyncLoading>
{
    SPTProgressView *_progressView;
}

@property(retain, nonatomic) SPTProgressView *progressView; // @synthesize progressView=_progressView;
- (void).cxx_destruct;
- (void)asyncLoadingWillComplete;
- (void)asyncLoadingViewWillAppear;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

