//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, NSURL;
@protocol SPTAssistedCurationCardsProviderDelegate;

@protocol SPTAssistedCurationCardsProvider <NSObject>
+ (NSString *)identifier;
@property(nonatomic) __weak id <SPTAssistedCurationCardsProviderDelegate> delegate;
- (void)provideCardsForCurrentTracks:(NSArray *)arg1 andContextName:(NSString *)arg2;

@optional
- (void)addedTrack:(NSURL *)arg1 fromContext:(unsigned long long)arg2;
@end

