//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GLUEImageStyle, NSString, NSURL, UIColor, UIImage, UIView;

@protocol SPTContextMenuAction <NSObject>
- (id)performAction;
- (NSString *)title;

@optional
- (NSString *)logEventName;
- (NSString *)accessibilityHint;
- (UIView *)accessoryView;
- (_Bool)shouldHaveTwoLineSubtitle;
- (_Bool)shouldHaveTwoLineTitle;
- (NSString *)subtitle;
- (GLUEImageStyle *)imageStyle;
- (UIImage *)placeholderImage;
- (NSURL *)imageURL;
- (UIImage *)iconImage;
- (UIColor *)iconColor;
- (long long)icon;
- (_Bool)isDisabled;
@end

