//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTCanvasMetadataResolver-Protocol.h"

@class NSArray, NSString;
@protocol OS_dispatch_queue, SPTCanvasTrackChecker, SPTResolver;

@interface SPTCanvasMetadataResolverImplementation : NSObject <SPTCanvasMetadataResolver>
{
    NSObject<OS_dispatch_queue> *_queue;
    id <SPTResolver> _resolver;
    id <SPTCanvasTrackChecker> _canvasTrackChecker;
    NSArray *_tracks;
}

+ (id)canvasMetatadataUsingCanvasDictionary:(id)arg1;
+ (id)bodyDataForTracks:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *tracks; // @synthesize tracks=_tracks;
@property(readonly, nonatomic) id <SPTCanvasTrackChecker> canvasTrackChecker; // @synthesize canvasTrackChecker=_canvasTrackChecker;
@property(readonly, nonatomic) id <SPTResolver> resolver; // @synthesize resolver=_resolver;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)didReceiveResponse:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)didFailToLoadMetadataWithError:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)didLoadMetadataWithCanvasModels:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)canvasModelsWithCanvasResponse:(id)arg1 error:(id *)arg2;
- (id)createCanvasRequest;
- (void)resolve:(CDUnknownBlockType)arg1;
- (id)initWithResolver:(id)arg1 canvasTrackChecker:(id)arg2 tracks:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

