//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, SPTPlayerTrack;
@protocol SPTCanvasModel;

@protocol SPTCanvasTrackChecker <NSObject>
- (id <SPTCanvasModel>)canvasModelForTrackMetadata:(NSDictionary *)arg1;
- (id <SPTCanvasModel>)canvasModelForTrack:(SPTPlayerTrack *)arg1;
- (_Bool)isCanvasEnabledForTrack:(SPTPlayerTrack *)arg1;
- (_Bool)trackHasCanvasMetadata:(SPTPlayerTrack *)arg1;
@end

