//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSCache, SPTCarPlayFeatureProperties, SPTCarPlayGradientImageBuilder;
@protocol SPTExternalIntegrationPlaybackController, SPTImageLoaderFactory;

@interface SPTCarPlayContentItemBuilder : NSObject
{
    id <SPTExternalIntegrationPlaybackController> _playbackController;
    id <SPTImageLoaderFactory> _imageLoaderFactory;
    SPTCarPlayFeatureProperties *_properties;
    SPTCarPlayGradientImageBuilder *_imageBuilder;
    NSCache *_iconCache;
}

@property(readonly, nonatomic) NSCache *iconCache; // @synthesize iconCache=_iconCache;
@property(retain, nonatomic) SPTCarPlayGradientImageBuilder *imageBuilder; // @synthesize imageBuilder=_imageBuilder;
@property(retain, nonatomic) SPTCarPlayFeatureProperties *properties; // @synthesize properties=_properties;
@property(readonly, nonatomic) id <SPTImageLoaderFactory> imageLoaderFactory; // @synthesize imageLoaderFactory=_imageLoaderFactory;
@property(readonly, nonatomic) id <SPTExternalIntegrationPlaybackController> playbackController; // @synthesize playbackController=_playbackController;
- (void).cxx_destruct;
- (id)contentItemFromExternalIntegrationContent:(id)arg1;
- (id)errorIsOfflineContentItem;
- (id)errorContentItem;
- (id)emptyListContentItemOfParent:(id)arg1;
- (id)shuffleContentItemOfParent:(id)arg1;
- (id)initWithPlaybackController:(id)arg1 imageLoaderFactory:(id)arg2 properties:(id)arg3;

@end

