//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTRemoteConfigurationProperties-Protocol.h"

@class NSString;

@interface SPTCollectionPlatformFeatureProperties : NSObject <SPTRemoteConfigurationProperties>
{
    _Bool _localTrackHideEnabled;
    _Bool _snackbarForPremiumEnabled;
    _Bool _snackbarWithAcmCopyEnabled;
    _Bool _snackbarWithAcmCopyForArtistsEnabled;
    _Bool _showLikeActionInNpvEnabled;
}

@property(readonly, nonatomic) _Bool showLikeActionInNpvEnabled; // @synthesize showLikeActionInNpvEnabled=_showLikeActionInNpvEnabled;
@property(readonly, nonatomic) _Bool snackbarWithAcmCopyForArtistsEnabled; // @synthesize snackbarWithAcmCopyForArtistsEnabled=_snackbarWithAcmCopyForArtistsEnabled;
@property(readonly, nonatomic) _Bool snackbarWithAcmCopyEnabled; // @synthesize snackbarWithAcmCopyEnabled=_snackbarWithAcmCopyEnabled;
@property(readonly, nonatomic) _Bool snackbarForPremiumEnabled; // @synthesize snackbarForPremiumEnabled=_snackbarForPremiumEnabled;
@property(readonly, nonatomic) _Bool localTrackHideEnabled; // @synthesize localTrackHideEnabled=_localTrackHideEnabled;
- (id)propertyModels;
- (id)initWithPropertyValuesDictionary:(id)arg1;
- (id)initWithConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

