//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GPBMessage, NSData, NSString;
@protocol SPTEventSenderMessage;

@protocol SPTEventSender <NSObject>
- (void)sendWrappedNonAuthenticatedEvent:(id <SPTEventSenderMessage>)arg1;
- (void)sendWrappedEvent:(id <SPTEventSenderMessage>)arg1;
- (void)sendNonAuthenticatedEventWithName:(NSString *)arg1 data:(NSData *)arg2;
- (void)sendNonAuthenticatedEventWithProtobuf:(GPBMessage *)arg1;
- (void)sendEventWithName:(NSString *)arg1 data:(NSData *)arg2;
- (void)sendEventWithProtobuf:(GPBMessage *)arg1;
@end

