//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTEditPlaylistModelDelegate-Protocol.h"
#import "SPTPageLoadable-Protocol.h"

@class NSString;
@protocol SPTEditPlaylistModel, SPTPageLoadStateHandler;

@interface SPTEditPlaylistLoadable : NSObject <SPTEditPlaylistModelDelegate, SPTPageLoadable>
{
    id <SPTEditPlaylistModel> _model;
    id <SPTPageLoadStateHandler> _loadStateHandler;
}

@property(retain, nonatomic) id <SPTPageLoadStateHandler> loadStateHandler; // @synthesize loadStateHandler=_loadStateHandler;
@property(retain, nonatomic) id <SPTEditPlaylistModel> model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)editPlaylistModel:(id)arg1 error:(id)arg2;
- (void)editPlaylistModel:(id)arg1 modelEntityDidChange:(id)arg2;
- (void)cancel;
- (void)loadWithResultHandler:(id)arg1;
- (id)initWithModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

