//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, NSURL;

@interface SPTFreeTierAlbumViewModel : NSObject
{
    NSArray *_albumTracks;
    NSString *_artistName;
    NSString *_albumName;
    NSURL *_albumURL;
}

@property(readonly, copy, nonatomic) NSURL *albumURL; // @synthesize albumURL=_albumURL;
@property(readonly, copy, nonatomic) NSString *albumName; // @synthesize albumName=_albumName;
@property(readonly, copy, nonatomic) NSString *artistName; // @synthesize artistName=_artistName;
@property(readonly, copy, nonatomic) NSArray *albumTracks; // @synthesize albumTracks=_albumTracks;
- (void).cxx_destruct;
- (void)updateModelWithTracksURIs:(id)arg1 albumName:(id)arg2 artistName:(id)arg3;
- (id)initWithAlbumURL:(id)arg1;

@end

