//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, NSURL, UIColor;

@protocol SPTFreeTierPlaylistFullbleedHeaderViewModel <NSObject>
@property(readonly, nonatomic) UIColor *formatListPrimaryColor;
@property(readonly, nonatomic) NSURL *formatListImageURL;
@property(readonly, copy, nonatomic) NSString *formatListSubtitle;
@property(readonly, copy, nonatomic) NSString *playlistDescription;
@property(readonly, copy, nonatomic) NSString *playlistName;
@end

