//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SPTFreeTierPlaylistTestManager, SPTProductState;

@interface SPTFreeTierPlaylistViewModelConfigurationProvider : NSObject
{
    id <SPTProductState> _productState;
    id <SPTFreeTierPlaylistTestManager> _testManager;
}

@property(readonly, nonatomic) id <SPTFreeTierPlaylistTestManager> testManager; // @synthesize testManager=_testManager;
@property(readonly, nonatomic) id <SPTProductState> productState; // @synthesize productState=_productState;
- (void).cxx_destruct;
- (id)provideViewModelConfiguration;
- (id)initWithProductState:(id)arg1 testManager:(id)arg2;

@end

