//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "HUBContentOperation-Protocol.h"

@class NSDictionary;
@protocol HUBContentOperationDelegate, SPTCollectionPlatformDataLoaderRequestToken, SPTCollectionPlatformStateProvider;

@interface SPTFreeTierAlbumBannedTracksContentOperation : NSObject <HUBContentOperation>
{
    id <HUBContentOperationDelegate> delegate;
    id <SPTCollectionPlatformStateProvider> _collectionPlatformStateProvider;
    NSDictionary *_URLBanMap;
    id <SPTCollectionPlatformDataLoaderRequestToken> _requestToken;
}

@property(retain, nonatomic) id <SPTCollectionPlatformDataLoaderRequestToken> requestToken; // @synthesize requestToken=_requestToken;
@property(copy, nonatomic) NSDictionary *URLBanMap; // @synthesize URLBanMap=_URLBanMap;
@property(readonly, nonatomic) id <SPTCollectionPlatformStateProvider> collectionPlatformStateProvider; // @synthesize collectionPlatformStateProvider=_collectionPlatformStateProvider;
@property(nonatomic) __weak id <HUBContentOperationDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)updateTrackComponentBuilders:(id)arg1 withCollectionStates:(id)arg2;
- (id)artistListFromTrackComponentBuilders:(id)arg1;
- (void)subscribeCollectionStateChangesForURLS:(id)arg1;
- (void)performForViewModelBuilder:(id)arg1 previousError:(id)arg2;
- (id)initWithCollectionPlaformStateProvider:(id)arg1;

@end

