//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SPTPlaylistPlatformFieldAddedAt-Protocol.h"
#import "SPTPlaylistPlatformFieldAlbumCovers-Protocol.h"
#import "SPTPlaylistPlatformFieldAlbumName-Protocol.h"
#import "SPTPlaylistPlatformFieldAlbumURL-Protocol.h"
#import "SPTPlaylistPlatformFieldArtists-Protocol.h"
#import "SPTPlaylistPlatformFieldAvailableOfflineStatus-Protocol.h"
#import "SPTPlaylistPlatformFieldCovers-Protocol.h"
#import "SPTPlaylistPlatformFieldDuration-Protocol.h"
#import "SPTPlaylistPlatformFieldEpisodePlayed-Protocol.h"
#import "SPTPlaylistPlatformFieldEpisodePublishDate-Protocol.h"
#import "SPTPlaylistPlatformFieldEpisodeShowName-Protocol.h"
#import "SPTPlaylistPlatformFieldEpisodeTimeLeft-Protocol.h"
#import "SPTPlaylistPlatformFieldFormatListAttributes-Protocol.h"
#import "SPTPlaylistPlatformFieldFreeformDescription-Protocol.h"
#import "SPTPlaylistPlatformFieldFreezeFrames-Protocol.h"
#import "SPTPlaylistPlatformFieldIs19PlusOnly-Protocol.h"
#import "SPTPlaylistPlatformFieldIsEpisode-Protocol.h"
#import "SPTPlaylistPlatformFieldIsExplicit-Protocol.h"
#import "SPTPlaylistPlatformFieldIsPremiumOnly-Protocol.h"
#import "SPTPlaylistPlatformFieldMediaType-Protocol.h"
#import "SPTPlaylistPlatformFieldName-Protocol.h"
#import "SPTPlaylistPlatformFieldOwnerName-Protocol.h"
#import "SPTPlaylistPlatformFieldOwnerUsername-Protocol.h"
#import "SPTPlaylistPlatformFieldPlayStatePlayable-Protocol.h"
#import "SPTPlaylistPlatformFieldPlayStateRestriction-Protocol.h"
#import "SPTPlaylistPlatformFieldPreviewID-Protocol.h"
#import "SPTPlaylistPlatformFieldRowId-Protocol.h"
#import "SPTPlaylistPlatformFieldURL-Protocol.h"
#import "SPTPlaylistPlatformInCollection-Protocol.h"
#import "SPTPlaylistPlatformIsBanned-Protocol.h"

@protocol SPTFreeTierPlaylistModelEntityTrackFields <SPTPlaylistPlatformFieldName, SPTPlaylistPlatformFieldURL, SPTPlaylistPlatformFieldArtists, SPTPlaylistPlatformFieldAlbumName, SPTPlaylistPlatformFieldAlbumURL, SPTPlaylistPlatformFieldAlbumCovers, SPTPlaylistPlatformFieldIsExplicit, SPTPlaylistPlatformFieldIsPremiumOnly, SPTPlaylistPlatformFieldAddedAt, SPTPlaylistPlatformFieldOwnerUsername, SPTPlaylistPlatformFieldOwnerName, SPTPlaylistPlatformFieldRowId, SPTPlaylistPlatformFieldPreviewID, SPTPlaylistPlatformInCollection, SPTPlaylistPlatformFieldAvailableOfflineStatus, SPTPlaylistPlatformIsBanned, SPTPlaylistPlatformFieldFormatListAttributes, SPTPlaylistPlatformFieldFreezeFrames, SPTPlaylistPlatformFieldCovers, SPTPlaylistPlatformFieldMediaType, SPTPlaylistPlatformFieldFreeformDescription, SPTPlaylistPlatformFieldEpisodeShowName, SPTPlaylistPlatformFieldEpisodePublishDate, SPTPlaylistPlatformFieldEpisodeTimeLeft, SPTPlaylistPlatformFieldEpisodePlayed, SPTPlaylistPlatformFieldIsEpisode, SPTPlaylistPlatformFieldDuration, SPTPlaylistPlatformFieldPlayStatePlayable, SPTPlaylistPlatformFieldPlayStateRestriction, SPTPlaylistPlatformFieldIs19PlusOnly>
@end

