//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, NSURL;

@protocol SPTFreeTierPersistentCounter <NSObject>
- (void)setCount:(unsigned long long)arg1 forIdentifier:(NSString *)arg2;
- (unsigned long long)countForIdentifier:(NSString *)arg1;
- (NSString *)settingsKeyForViewURI:(NSURL *)arg1 identifier:(NSString *)arg2;
@end

