//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GLUEImageLoader-Protocol.h"

@protocol SPTImageLoaderInstrumentationObserver;

@protocol SPTGLUEObservableImageLoader <GLUEImageLoader>
- (void)removeInstrumentationObserver:(id <SPTImageLoaderInstrumentationObserver>)arg1;
- (void)addInstrumentationObserver:(id <SPTImageLoaderInstrumentationObserver>)arg1;
@end

