//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTGaiaLockScreenControlsStateProvider-Protocol.h"
#import "SPTGaiaSettingsObserver-Protocol.h"

@class NSString, SPTObserverManager;
@protocol SPTGaiaLockScreenPlayerFlagsProvider, SPTGaiaSettingsProvider;

@interface SPTGaiaLockScreenFeatureManager : NSObject <SPTGaiaSettingsObserver, SPTGaiaLockScreenControlsStateProvider>
{
    id <SPTGaiaLockScreenPlayerFlagsProvider> _lockScreenFlagsProvider;
    id <SPTGaiaSettingsProvider> _settingsProvider;
    SPTObserverManager *_observers;
}

@property(readonly, nonatomic) SPTObserverManager *observers; // @synthesize observers=_observers;
@property(readonly, nonatomic) id <SPTGaiaSettingsProvider> settingsProvider; // @synthesize settingsProvider=_settingsProvider;
@property(readonly, nonatomic) id <SPTGaiaLockScreenPlayerFlagsProvider> lockScreenFlagsProvider; // @synthesize lockScreenFlagsProvider=_lockScreenFlagsProvider;
- (void).cxx_destruct;
- (void)updateObservers;
- (void)localDevicesOnlySettingsChanged:(_Bool)arg1;
- (void)lockScreenControlsSettingsChanged:(_Bool)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (_Bool)lockScreenFeatureIsEnabled;
- (void)dealloc;
- (id)initWithLockScreenPlayerFlagsProvider:(id)arg1 settingsProvider:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

