//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;
@protocol SPTGaiaWirelessRoutesObserver;

@protocol SPTGaiaWirelessRoutesAPI <NSObject>
@property(readonly, nonatomic) long long wirelessConnectionType;
@property(readonly, copy, nonatomic) NSString *activeDeviceName;
@property(readonly, nonatomic, getter=isActive) _Bool active;
@property(readonly, nonatomic, getter=isAvailable) _Bool available;
- (void)presentAirplayPicker;
- (void)removeObserver:(id <SPTGaiaWirelessRoutesObserver>)arg1;
- (void)addObserver:(id <SPTGaiaWirelessRoutesObserver>)arg1;
@end

