//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol SPTGoogleAppFlipParameterValidator <NSObject>
- (_Bool)validateSourceApplication:(NSString *)arg1;
- (_Bool)validateScopes:(NSString *)arg1;
- (_Bool)validateState:(NSString *)arg1;
- (_Bool)validateRedirectURI:(NSString *)arg1;
- (_Bool)validateClientID:(NSString *)arg1;
@end

