//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SPTHiddenContentTrackCellDelegate, SPTHiddenContentTrackViewModel;

@interface SPTHiddenContentTrackCellInteractionListener : NSObject
{
    id <SPTHiddenContentTrackCellDelegate> _cellDelegate;
    id <SPTHiddenContentTrackViewModel> _trackViewModel;
}

@property(nonatomic) __weak id <SPTHiddenContentTrackViewModel> trackViewModel; // @synthesize trackViewModel=_trackViewModel;
@property(nonatomic) __weak id <SPTHiddenContentTrackCellDelegate> cellDelegate; // @synthesize cellDelegate=_cellDelegate;
- (void).cxx_destruct;
- (void)trackPreviewButtonTouchedUpInside:(id)arg1;
- (void)contextMenuTapped:(id)arg1;
- (id)initWithCellDelegate:(id)arg1 trackViewModel:(id)arg2;

@end

