//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface SPTHearablesSpotifyCommand : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int commandName; // @dynamic commandName;
@property(nonatomic) int commandType; // @dynamic commandType;
@property(copy, nonatomic) NSString *deviceBrand; // @dynamic deviceBrand;
@property(copy, nonatomic) NSString *deviceModel; // @dynamic deviceModel;

@end

