//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "HUBCommandHandler-Protocol.h"

@class SPTHomeLocalViewModelOverrides;
@protocol SPTHubInteractionLogger, SPTUBIHubsUtilities;

@interface SPTHomeTasteOnboardingSkipCommandHandler : NSObject <HUBCommandHandler>
{
    SPTHomeLocalViewModelOverrides *_overrides;
    id <SPTHubInteractionLogger> _hubInteractionLogger;
    id <SPTUBIHubsUtilities> _ubiHubsUtilities;
}

@property(readonly, nonatomic) id <SPTUBIHubsUtilities> ubiHubsUtilities; // @synthesize ubiHubsUtilities=_ubiHubsUtilities;
@property(readonly, nonatomic) id <SPTHubInteractionLogger> hubInteractionLogger; // @synthesize hubInteractionLogger=_hubInteractionLogger;
@property(readonly, nonatomic) SPTHomeLocalViewModelOverrides *overrides; // @synthesize overrides=_overrides;
- (void).cxx_destruct;
- (void)handleCommand:(id)arg1 event:(id)arg2;
- (id)initWithViewModelWithOverrides:(id)arg1 hubInteractionLogger:(id)arg2 ubiHubsUtilities:(id)arg3;

@end

