//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SPTInAppMessageSDKTrigger : NSObject
{
    _Bool _cache;
    NSString *_format;
    NSString *_pattern;
    NSString *_type;
}

@property(readonly, nonatomic) _Bool cache; // @synthesize cache=_cache;
@property(readonly, copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(readonly, copy, nonatomic) NSString *pattern; // @synthesize pattern=_pattern;
@property(readonly, copy, nonatomic) NSString *format; // @synthesize format=_format;
- (void).cxx_destruct;
- (id)initWithPattern:(id)arg1 format:(id)arg2 type:(id)arg3 cache:(_Bool)arg4;

@end

