//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTInAppMessageActionHandler-Protocol.h"

@class NSString, SPTInAppMessageActionsRegistryImplementation;

@interface SPTInAppMessageCreatePlaylistAction : NSObject <SPTInAppMessageActionHandler>
{
    SPTInAppMessageActionsRegistryImplementation *_registry;
}

@property(readonly, nonatomic) SPTInAppMessageActionsRegistryImplementation *registry; // @synthesize registry=_registry;
- (void).cxx_destruct;
- (void)executeActionWithURL:(id)arg1;
- (id)initWithActionsRegistry:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

