//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTInstrumentationPageViewLogger-Protocol.h"

@class NSString, SPTInstrumentationPageViewData;
@protocol SPTEventSender;

@interface SPTInstrumentationPageViewDualSendingLoggerImplementation : NSObject <SPTInstrumentationPageViewLogger>
{
    id <SPTEventSender> _eventSender;
    SPTInstrumentationPageViewData *_currentData;
}

@property(retain, nonatomic) SPTInstrumentationPageViewData *currentData; // @synthesize currentData=_currentData;
@property(retain, nonatomic) id <SPTEventSender> eventSender; // @synthesize eventSender=_eventSender;
- (void).cxx_destruct;
- (void)sendPageViewExitForCurrentDataWithTimestamp:(long long)arg1;
- (void)exitCurrentPageWithTimestamp:(long long)arg1;
- (void)sendPageViewEnterWithPageIdentifier:(id)arg1 entityUri:(id)arg2 timestamp:(long long)arg3 navigationRootIdentifier:(id)arg4;
- (void)enterPageWithIdentifier:(id)arg1 URI:(id)arg2 timestamp:(long long)arg3 navigationRootIdentifier:(id)arg4;
- (id)initWithInstrumentsEventSender:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

