//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GLUEStyleable-Protocol.h"

@class GLUELabel, NSLayoutConstraint, NSString;

@interface SPTListenTogetherBetaLabel : UIView <GLUEStyleable>
{
    GLUELabel *_label;
    NSLayoutConstraint *_labelLeadingConstraint;
    NSLayoutConstraint *_labelTrailingConstraint;
    NSLayoutConstraint *_labelTopConstraint;
    NSLayoutConstraint *_labelBottomConstraint;
}

@property(retain, nonatomic) NSLayoutConstraint *labelBottomConstraint; // @synthesize labelBottomConstraint=_labelBottomConstraint;
@property(retain, nonatomic) NSLayoutConstraint *labelTopConstraint; // @synthesize labelTopConstraint=_labelTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *labelTrailingConstraint; // @synthesize labelTrailingConstraint=_labelTrailingConstraint;
@property(retain, nonatomic) NSLayoutConstraint *labelLeadingConstraint; // @synthesize labelLeadingConstraint=_labelLeadingConstraint;
@property(readonly, nonatomic) GLUELabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (void)glue_applyStyle:(id)arg1;
- (void)setupConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

