//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, SPSession;

@protocol SPTLoginStateControllerObserver <NSObject>
- (void)loginStateControllerDidReceiveCoreStateUpdateWithCurrentSession:(SPSession *)arg1 withError:(NSError *)arg2 isPermanentError:(_Bool)arg3;
@end

