//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SPTDynamicSignupFlowController, SPTLoginMethodLedStartViewLogger;

@interface SPTLoginMethodLedStartScreenViewModel : NSObject
{
    SPTLoginMethodLedStartViewLogger *_logger;
    SPTDynamicSignupFlowController *_flowController;
}

@property(readonly, nonatomic) SPTDynamicSignupFlowController *flowController; // @synthesize flowController=_flowController;
@property(readonly, nonatomic) SPTLoginMethodLedStartViewLogger *logger; // @synthesize logger=_logger;
- (void).cxx_destruct;
- (void)userClickedSignup;
- (void)userClickedLogin;
- (id)buttonContainerHeadingText;
- (id)signupButtonText;
- (id)loginButtonText;
- (id)initWithFlowController:(id)arg1 logger:(id)arg2;

@end

