//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTHubRemoteContentOperationURLResolver-Protocol.h"

@class NSString;

@interface SPTMadeForYouHubURLResolver : NSObject <SPTHubRemoteContentOperationURLResolver>
{
    NSString *_locale;
    NSString *_timeZone;
    NSString *_clientVersion;
}

@property(copy, nonatomic) NSString *clientVersion; // @synthesize clientVersion=_clientVersion;
@property(copy, nonatomic) NSString *timeZone; // @synthesize timeZone=_timeZone;
@property(copy, nonatomic) NSString *locale; // @synthesize locale=_locale;
- (void).cxx_destruct;
- (id)resolveContentURL;
- (id)initWithLocale:(id)arg1 timeZone:(id)arg2 clientVersion:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

