//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SPTNowPlayingInformationUnitViewModel;

@protocol SPTNowPlayingInformationUnitViewModelDelegate <NSObject>
- (void)viewModelDidUpdateLyricsButtonVisibility:(_Bool)arg1;
- (void)viewModelDidUpdatePositiveFeedbackButtonState:(id <SPTNowPlayingInformationUnitViewModel>)arg1;
- (void)viewModelDidUpdate:(id <SPTNowPlayingInformationUnitViewModel>)arg1 trackDidChange:(_Bool)arg2;
@end

