//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SPTNowPlayingRemoteControlEventPolicyController, SPTNowPlayingRemoteEventSubtypesController;

@protocol SPTNowPlayingRemoteControlEventControllerRegistry <NSObject>
- (void)unregisterRemoteEventSubtypesController:(id <SPTNowPlayingRemoteEventSubtypesController>)arg1;
- (void)registerRemoteEventSubtypesController:(id <SPTNowPlayingRemoteEventSubtypesController>)arg1;
- (void)unregisterRemoteControlEventPolicyController:(id <SPTNowPlayingRemoteControlEventPolicyController>)arg1;
- (void)registerRemoteControlEventPolicyController:(id <SPTNowPlayingRemoteControlEventPolicyController>)arg1;
@end

