//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTPartnerLogger-Protocol.h"

@class NSString, SPTPartnerTimeTracker;
@protocol SPTLogCenter, SPTPartnerTestManager;

@interface SPTPartnerLoggerImplementation : NSObject <SPTPartnerLogger>
{
    id <SPTLogCenter> _logCenter;
    NSString *_sessionId;
    SPTPartnerTimeTracker *_timeTracker;
    id <SPTPartnerTestManager> _testManager;
}

@property(retain, nonatomic) id <SPTPartnerTestManager> testManager; // @synthesize testManager=_testManager;
@property(retain, nonatomic) SPTPartnerTimeTracker *timeTracker; // @synthesize timeTracker=_timeTracker;
@property(copy, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(retain, nonatomic) id <SPTLogCenter> logCenter; // @synthesize logCenter=_logCenter;
- (void).cxx_destruct;
- (void)logBannerSessionEventWithEventType:(id)arg1 eventReason:(id)arg2 sessionType:(id)arg3 shownApps:(id)arg4 connectedApp:(id)arg5;
- (void)startNewSession;
- (id)initWithLogCenter:(id)arg1 testManager:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

