//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, NSIndexPath, SPTPodcastFilterContextViewController, SPTPodcastViewModel2, UIView;
@protocol SPTPodcastEpisode, SPTPodcastViewModelSection;

@protocol SPTPodcastViewModelDelegate2 <NSObject>
- (void)viewModel:(SPTPodcastViewModel2 *)arg1 showContextMenuForTrailerEpisode:(id <SPTPodcastEpisode>)arg2 atIndexPath:(NSIndexPath *)arg3;
- (void)viewModel:(SPTPodcastViewModel2 *)arg1 scrollToLatestPlayedEpisodeAtIndexPath:(NSIndexPath *)arg2;
- (void)podcastViewModelDidUpdatePlaybackRestrictions:(SPTPodcastViewModel2 *)arg1;
- (void)viewModel:(SPTPodcastViewModel2 *)arg1 didUpdateFilteredState:(_Bool)arg2;
- (void)viewModel:(SPTPodcastViewModel2 *)arg1 didUpdateSectionWithSectionViewModel:(id <SPTPodcastViewModelSection>)arg2 atIndexPath:(NSIndexPath *)arg3;
- (void)viewModelDidSelectContextMenuButton:(SPTPodcastViewModel2 *)arg1 senderView:(UIView *)arg2;
- (void)viewModel:(SPTPodcastViewModel2 *)arg1 willPresentFilterContextViewController:(SPTPodcastFilterContextViewController *)arg2 fromSender:(id)arg3;
- (void)viewModel:(SPTPodcastViewModel2 *)arg1 podcastDidFinishLoadingWithError:(NSError *)arg2;
@end

