//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSMutableArray, NSMutableOrderedSet;

@interface SPTPaletteConfiguration : NSObject <NSCopying>
{
    NSMutableOrderedSet *_targets;
    unsigned long long _maxColorCount;
    NSMutableArray *_filters;
}

+ (id)defaultConfiguration;
@property(readonly, nonatomic) NSMutableArray *filters; // @synthesize filters=_filters;
@property(nonatomic) unsigned long long maxColorCount; // @synthesize maxColorCount=_maxColorCount;
@property(readonly, nonatomic) NSMutableOrderedSet *targets; // @synthesize targets=_targets;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTargets:(id)arg1 maxColorCount:(unsigned long long)arg2 filters:(id)arg3;
- (id)init;

@end

