//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class GLUEAccessoryIconButton, UIImageView, UILabel, UIView;
@protocol SPTEpisodeSegmentsEntity, SPTPodcastEpisodeFeaturedContentTrackActionsDelegate;

@interface SPTPodcastEpisodeFeaturedContentTrackListViewCell : UITableViewCell
{
    UIImageView *_trackImageView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UILabel *_timeLabel;
    GLUEAccessoryIconButton *_contextMenuButton;
    UIView *_timelineView;
    id <SPTEpisodeSegmentsEntity> _currentEpisodeSegmentsEntity;
    id <SPTPodcastEpisodeFeaturedContentTrackActionsDelegate> _trackActionHandler;
}

+ (long long)numberOfLinesForText:(id)arg1 containerWidth:(double)arg2;
+ (double)sizeForCellWithTitle:(id)arg1 containerWidth:(double)arg2;
@property(nonatomic) __weak id <SPTPodcastEpisodeFeaturedContentTrackActionsDelegate> trackActionHandler; // @synthesize trackActionHandler=_trackActionHandler;
@property(retain, nonatomic) id <SPTEpisodeSegmentsEntity> currentEpisodeSegmentsEntity; // @synthesize currentEpisodeSegmentsEntity=_currentEpisodeSegmentsEntity;
@property(retain, nonatomic) UIView *timelineView; // @synthesize timelineView=_timelineView;
@property(retain, nonatomic) GLUEAccessoryIconButton *contextMenuButton; // @synthesize contextMenuButton=_contextMenuButton;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *trackImageView; // @synthesize trackImageView=_trackImageView;
- (void).cxx_destruct;
- (id)formattedTrackStartTimeForEntity:(id)arg1;
- (void)didTouchContextMenu;
- (void)setupConstraints;
- (void)setupLayout;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (id)subTitle:(id)arg1;
- (_Bool)isContextMenuEnabled:(id)arg1;
- (_Bool)isArtistCover:(id)arg1;
- (void)configureCellForEntity:(id)arg1 isLastVisibleTrack:(_Bool)arg2 imageLoader:(id)arg3 trackActionHandler:(id)arg4;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

