//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class HUBComponentDefaults, SPTPremiumDestinationHubManagerConfiguration;
@protocol HUBIconImageResolver, SPTHubCommandHandlerFactory;

@interface SPTPremiumDestinationHubManager : NSObject
{
    HUBComponentDefaults *_componentDefaults;
    id <HUBIconImageResolver> _iconImageResolver;
    id <SPTHubCommandHandlerFactory> _commandHandlerFactory;
    SPTPremiumDestinationHubManagerConfiguration *_configuration;
}

@property(retain, nonatomic) SPTPremiumDestinationHubManagerConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) id <SPTHubCommandHandlerFactory> commandHandlerFactory; // @synthesize commandHandlerFactory=_commandHandlerFactory;
@property(readonly, nonatomic) id <HUBIconImageResolver> iconImageResolver; // @synthesize iconImageResolver=_iconImageResolver;
@property(readonly, nonatomic) HUBComponentDefaults *componentDefaults; // @synthesize componentDefaults=_componentDefaults;
- (void).cxx_destruct;
- (id)provideViewControllerForURL:(id)arg1 referrerIdentifier:(id)arg2 viewModelProvider:(id)arg3 reloadSignalSource:(id)arg4;
- (id)createCommandDispatcherForURL:(id)arg1 referrerIdentifier:(id)arg2 interactionLogger:(id)arg3 reloadSignalSource:(id)arg4;
- (id)createViewModelProviderWithContentOperations:(id)arg1;
- (id)createRemoteContentOperationsWithContentURLResolver:(id)arg1 reloadSignalSource:(id)arg2;
- (id)createLocalContentOperations;
- (id)providePremiumDestinationHubsRemoteURLResolver;
- (id)providePremiumDestinationComponentLayoutManager;
- (id)provideLocalJSONPreviewViewControllerForURL:(id)arg1 referrerIdentifier:(id)arg2;
- (id)provideViewControllerForURL:(id)arg1 referrerIdentifier:(id)arg2;
- (id)initWithHubManagerConfiguration:(id)arg1;

@end

