//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SPTPageControllerBarButtonItemProviderRegistration : NSObject
{
    CDUnknownBlockType _provider;
    NSString *_identifier;
}

@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, copy, nonatomic) CDUnknownBlockType provider; // @synthesize provider=_provider;
- (void).cxx_destruct;
- (id)initWithProvider:(CDUnknownBlockType)arg1 identifier:(id)arg2;

@end

