//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UIImage;

@protocol SPTShareDestination <NSObject>
@property(nonatomic, readonly) NSString *loggingKey;
@property(nonatomic, readonly) unsigned long long capability;
@property(nonatomic, readonly) long long destinationId;
@property(nonatomic, readonly) NSString *URLFormat;
@property(nonatomic, readonly) NSString *URLScheme;
@property(nonatomic, readonly) UIImage *icon;
@property(nonatomic, readonly) NSString *title;
@end

