//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTSpotlightIndexGatekeeper-Protocol.h"

@class NSString, NSUserDefaults;
@protocol SPTReachabilityMonitor;

@interface SPTSpotlightIndexGatekeeperImplementation : NSObject <SPTSpotlightIndexGatekeeper>
{
    _Bool _isIndexing;
    NSUserDefaults *_userDefaults;
    id <SPTReachabilityMonitor> _reachability;
}

@property(nonatomic) _Bool isIndexing; // @synthesize isIndexing=_isIndexing;
@property(readonly, nonatomic) id <SPTReachabilityMonitor> reachability; // @synthesize reachability=_reachability;
@property(readonly, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
- (void).cxx_destruct;
- (void)indexDidDrop:(id)arg1;
- (void)indexDidEndIndexing:(id)arg1 error:(id)arg2;
- (void)indexDidStartIndexing:(id)arg1;
- (_Bool)shouldUpdateIndex:(id)arg1;
- (id)initWithUserDefaults:(id)arg1 reachability:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

