//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "SPTSortingFilteringButtonsCell-Protocol.h"

@class NSArray, NSLayoutConstraint, NSString, UIView;
@protocol SPTSortingFilteringButtonsCellStyle, SPTSortingFilteringButtonsContainer;

@interface SPTSortingFilteringButtonsTableViewCell : UITableViewCell <SPTSortingFilteringButtonsCell>
{
    id <SPTSortingFilteringButtonsCellStyle> _style;
    UIView<SPTSortingFilteringButtonsContainer> *_buttonsContainer;
    NSArray *_layoutConstraints;
    NSLayoutConstraint *_leadingConstraint;
    NSLayoutConstraint *_trailingConstraint;
    NSLayoutConstraint *_topConstraint;
    NSLayoutConstraint *_bottomConstraint;
}

@property(retain, nonatomic) NSLayoutConstraint *bottomConstraint; // @synthesize bottomConstraint=_bottomConstraint;
@property(retain, nonatomic) NSLayoutConstraint *topConstraint; // @synthesize topConstraint=_topConstraint;
@property(retain, nonatomic) NSLayoutConstraint *trailingConstraint; // @synthesize trailingConstraint=_trailingConstraint;
@property(retain, nonatomic) NSLayoutConstraint *leadingConstraint; // @synthesize leadingConstraint=_leadingConstraint;
@property(copy, nonatomic) NSArray *layoutConstraints; // @synthesize layoutConstraints=_layoutConstraints;
@property(retain, nonatomic) UIView<SPTSortingFilteringButtonsContainer> *buttonsContainer; // @synthesize buttonsContainer=_buttonsContainer;
@property(retain, nonatomic) id <SPTSortingFilteringButtonsCellStyle> style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)setupConstraints;
- (void)glue_applyStyle:(id)arg1;
- (id)initWithButtonsContainer:(id)arg1 style:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

