//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTUBIMobilePlaylistEntity_Toolbar_ContextMenuButtonEventFactory-Protocol.h"

@class NSArray, NSString;

@interface SPTUBIMobilePlaylistEntity_Toolbar_ContextMenuButtonEventFactoryImplementation : NSObject <SPTUBIMobilePlaylistEntity_Toolbar_ContextMenuButtonEventFactory>
{
    NSArray *_components;
}

+ (id)factoryWithComponents:(id)arg1;
@property(copy, nonatomic) NSArray *components; // @synthesize components=_components;
- (void).cxx_destruct;
- (id)hitUiReveal;
- (id)shareOptionFactory;
- (id)findOptionFactory;
- (id)sortOptionFactory;
- (id)removeItemsOptionFactory;
- (id)queueItemsOptionFactory;
- (id)banItemsOptionFactory;
- (id)heartItemsOptionFactory;
- (id)addItemsOptionFactory;
- (id)deleteOptionFactory;
- (id)renameOptionFactory;
- (id)editPlaylistOptionFactory;
- (id)addSongsOptionFactory;
- (id)downloadOptionFactory;
- (id)publishedOptionFactory;
- (id)collaborativeOptionFactory;
- (id)heartButtonFactory;
- (id)_location;
- (id)initWithComponents:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

