//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTUBIMobileNowPlayingViewDefaultEventFactory-Protocol.h"

@class NSArray, NSString;

@interface SPTUBIMobileNowPlayingViewDefaultEventFactoryImplementation : NSObject <SPTUBIMobileNowPlayingViewDefaultEventFactory>
{
    NSArray *_components;
}

+ (id)factoryWithPageIdentifier:(id)arg1 pageUri:(id)arg2;
@property(copy, nonatomic) NSArray *components; // @synthesize components=_components;
- (void).cxx_destruct;
- (id)swipeUiHide;
- (id)dragUiReveal;
- (id)scrollComponentsContainerFactory;
- (id)bottomBarContainerFactory;
- (id)mainControlsContainerFactory;
- (id)playbackProgressFactory;
- (id)trackInformationContainerFactory;
- (id)coverArtFactory;
- (id)topBarContainerFactory;
- (id)_location;
- (id)initWithPageIdentifier:(id)arg1 pageUri:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

