//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface SPTURIComponentMatcherResult : NSObject
{
    id _payload;
    NSDictionary *_variables;
}

@property(readonly, nonatomic) NSDictionary *variables; // @synthesize variables=_variables;
@property(readonly, nonatomic) id payload; // @synthesize payload=_payload;
- (void).cxx_destruct;
- (id)initWithPayload:(id)arg1 variables:(id)arg2;

@end

