//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSURL;
@protocol SPTUBIEventFactoryLocation, SPTUBIMobilePlaylistEntity_ItemList_ItemEventFactory, SPTUBIMobilePlaylistEntity_ItemList_ShuffleEducationEventFactory, SPTUBIMobilePlaylistEntity_ItemList_WeAddedSectionHeaderEventFactory;

@protocol SPTUBIMobilePlaylistEntity_ItemListEventFactory <NSObject>
- (id <SPTUBIMobilePlaylistEntity_ItemList_ItemEventFactory>)itemFactoryWithPosition:(long long)arg1 uri:(NSURL *)arg2;
- (id <SPTUBIMobilePlaylistEntity_ItemList_WeAddedSectionHeaderEventFactory>)weAddedSectionHeaderFactory;
- (id <SPTUBIMobilePlaylistEntity_ItemList_ShuffleEducationEventFactory>)shuffleEducationFactory;
- (id <SPTUBIEventFactoryLocation>)_location;
@end

