//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SPTVideoCoordinatorCosmosSender;
@protocol BMPlaybackTimeObservable, BMPlaybackTimeObserverCancellationToken;

@interface SPTVideoCoordinatorPlayerInterruptor : NSObject
{
    id <BMPlaybackTimeObservable> _timeObservable;
    double _stopPosition;
    SPTVideoCoordinatorCosmosSender *_cosmosSender;
    id <BMPlaybackTimeObserverCancellationToken> _cancellationToken;
}

@property(retain, nonatomic) id <BMPlaybackTimeObserverCancellationToken> cancellationToken; // @synthesize cancellationToken=_cancellationToken;
@property(retain, nonatomic) SPTVideoCoordinatorCosmosSender *cosmosSender; // @synthesize cosmosSender=_cosmosSender;
@property(readonly, nonatomic) double stopPosition; // @synthesize stopPosition=_stopPosition;
@property(retain, nonatomic) id <BMPlaybackTimeObservable> timeObservable; // @synthesize timeObservable=_timeObservable;
- (void).cxx_destruct;
- (void)scheduleInterruption;
- (_Bool)canScheduleInterruption;
- (void)unregister;
- (void)registerInterruptorWhenReadyAtPosition:(double)arg1;
- (id)initWithCosmosSender:(id)arg1;

@end

