//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, SPTVoiceLibraryFinalResponse, SPTVoiceLibraryIntermediateResponse;
@protocol SPTVoiceLibrarySession;

@protocol SPTVoiceLibrarySessionObserver <NSObject>

@optional
- (void)voiceSession:(id <SPTVoiceLibrarySession>)arg1 didUpdateMeanAudioLevel:(float)arg2 rmsAudioLevel:(float)arg3 cdfScaledAudioLevel:(float)arg4;
- (void)voiceSession:(id <SPTVoiceLibrarySession>)arg1 didFailWithError:(NSError *)arg2;
- (void)voiceSession:(id <SPTVoiceLibrarySession>)arg1 didReceiveFinalResponse:(SPTVoiceLibraryFinalResponse *)arg2;
- (void)voiceSession:(id <SPTVoiceLibrarySession>)arg1 didUpdateIntermediateResponse:(SPTVoiceLibraryIntermediateResponse *)arg2;
- (void)voiceSessionDidStopListening:(id <SPTVoiceLibrarySession>)arg1;
- (void)voiceSessionDidStartListening:(id <SPTVoiceLibrarySession>)arg1;
- (void)voiceSessionWillStartListening:(id <SPTVoiceLibrarySession>)arg1;
@end

