//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "VISREFActionRowButtonViewModel-Protocol.h"

@class GLUEButton, NSString;
@protocol SPTFreeTierPlaylistBarButtonManagerDelegate, VISREFActionRowButtonViewModelDelegate;

@interface VISREFPlaylistContextMenuViewModel : NSObject <VISREFActionRowButtonViewModel>
{
    GLUEButton<VISREFActionRowButtonViewModelDelegate> *_delegate;
    id <SPTFreeTierPlaylistBarButtonManagerDelegate> _barButtonManagerDelegate;
}

@property(nonatomic) __weak id <SPTFreeTierPlaylistBarButtonManagerDelegate> barButtonManagerDelegate; // @synthesize barButtonManagerDelegate=_barButtonManagerDelegate;
@property(nonatomic) __weak GLUEButton<VISREFActionRowButtonViewModelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateState;
- (id)imageForState:(_Bool)arg1;
- (void)tapContextMenuButton:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

