//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 14 2020 10:06:36).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface VoiceLibraryError : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *errorDescription; // @dynamic errorDescription;
@property(copy, nonatomic) NSString *errorDomain; // @dynamic errorDomain;
@property(copy, nonatomic) NSString *errorType; // @dynamic errorType;
@property(nonatomic) _Bool hasErrorDescription; // @dynamic hasErrorDescription;
@property(nonatomic) _Bool hasErrorDomain; // @dynamic hasErrorDomain;
@property(nonatomic) _Bool hasErrorType; // @dynamic hasErrorType;
@property(nonatomic) _Bool hasReferrerId; // @dynamic hasReferrerId;
@property(nonatomic) _Bool hasUtteranceId; // @dynamic hasUtteranceId;
@property(copy, nonatomic) NSString *referrerId; // @dynamic referrerId;
@property(copy, nonatomic) NSString *utteranceId; // @dynamic utteranceId;

@end

