//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "EXP_SPTHubFrameworkService-Protocol.h"
#import "SPTService-Protocol.h"

@class EXP_SPTHubsRendererFactoryImplementation, NSString, SPTAllocationContext;
@protocol CosmosFeature, SPContextMenuFeature, SPTContainerService, SPTGLUEService, SPTNetworkService, SPTPerformanceMetricsService, SPTPlayerFeature, SPTSessionService, SPTURIDispatchService;

@interface EXP_SPTHubFrameworkServiceImplementation : NSObject <SPTService, EXP_SPTHubFrameworkService>
{
    id <SPTGLUEService> _glueService;
    id <SPTNetworkService> _networkService;
    id <SPTPlayerFeature> _playerService;
    id <SPContextMenuFeature> _contextMenuService;
    id <SPTURIDispatchService> _URIDispatchService;
    id <SPTContainerService> _containerService;
    id <SPTSessionService> _sessionService;
    id <SPTPerformanceMetricsService> _performanceMetricsService;
    id <CosmosFeature> _cosmosFeature;
    EXP_SPTHubsRendererFactoryImplementation *_hubsRendererFactory;
}

+ (id)serviceIdentifier;
@property(retain, nonatomic) EXP_SPTHubsRendererFactoryImplementation *hubsRendererFactory; // @synthesize hubsRendererFactory=_hubsRendererFactory;
@property(nonatomic) __weak id <CosmosFeature> cosmosFeature; // @synthesize cosmosFeature=_cosmosFeature;
@property(nonatomic) __weak id <SPTPerformanceMetricsService> performanceMetricsService; // @synthesize performanceMetricsService=_performanceMetricsService;
@property(nonatomic) __weak id <SPTSessionService> sessionService; // @synthesize sessionService=_sessionService;
@property(nonatomic) __weak id <SPTContainerService> containerService; // @synthesize containerService=_containerService;
@property(nonatomic) __weak id <SPTURIDispatchService> URIDispatchService; // @synthesize URIDispatchService=_URIDispatchService;
@property(nonatomic) __weak id <SPContextMenuFeature> contextMenuService; // @synthesize contextMenuService=_contextMenuService;
@property(nonatomic) __weak id <SPTPlayerFeature> playerService; // @synthesize playerService=_playerService;
@property(nonatomic) __weak id <SPTNetworkService> networkService; // @synthesize networkService=_networkService;
@property(nonatomic) __weak id <SPTGLUEService> glueService; // @synthesize glueService=_glueService;
- (void).cxx_destruct;
- (id)provideHubsRendererFactory;
- (void)load;
- (void)configureWithServices:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

