//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBSDKGraphErrorRecoveryProcessor, NSError;

@protocol FBSDKGraphErrorRecoveryProcessorDelegate <NSObject>
- (void)processorDidAttemptRecovery:(FBSDKGraphErrorRecoveryProcessor *)arg1 didRecover:(_Bool)arg2 error:(NSError *)arg3;

@optional
- (_Bool)processorWillProcessError:(FBSDKGraphErrorRecoveryProcessor *)arg1 error:(NSError *)arg2;
@end

