//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GCKNSocket.h"

@protocol GCKNUDPSocketDelegate;

@interface GCKNUDPSocket : GCKNSocket
{
    char _readBuffer[65536];
    id <GCKNUDPSocketDelegate> _delegate;
}

@property(nonatomic) __weak id <GCKNUDPSocketDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)notifyDidCloseWithError:(id)arg1;
- (void)notifyDidReceivePacket:(id)arg1 fromAddress:(id)arg2;
- (void)closeWithError:(id)arg1;
- (void)onReadable;
- (void)onWritable;
- (void)onDisconnectedWithError:(id)arg1;
- (void)onConnectionFailedWithError:(id)arg1;
- (_Bool)sendScatteredPacket:(id)arg1 toAddress:(id)arg2;
- (_Bool)sendPacket:(id)arg1 toAddress:(id)arg2;
- (_Bool)sendPacket:(id)arg1;
- (id)initWithAddressType:(long long)arg1 localPort:(unsigned short)arg2;
- (id)initWithLocalAddress:(id)arg1 localPort:(unsigned short)arg2;
- (id)initWithAddressType:(long long)arg1;
- (id)init;

@end

