//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface GCKSSecurityIdentity : NSObject
{
    struct __SecIdentity *_identityRef;
}

- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)copyCertificate;
- (struct __SecIdentity *)getRef;
- (void)dealloc;
- (id)initWithSecIdentityRef:(struct __SecIdentity *)arg1;

@end

