//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSBundle;

@interface GCKUIResources : NSObject
{
    NSBundle *_bundle;
}

@property(retain, nonatomic) NSBundle *bundle; // @synthesize bundle=_bundle;
- (void).cxx_destruct;
- (id)storyboardNamed:(id)arg1;
- (id)nibNamed:(id)arg1 owner:(id)arg2 replacementObjects:(id)arg3;
- (id)imageNamed:(id)arg1 withRenderingMode:(long long)arg2;
- (id)imageNamed:(id)arg1;
- (id)init;

@end

