//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface GLUEMathUtil : NSObject
{
}

+ (double)mapFromLow:(double)arg1 fromHigh:(double)arg2 toLow:(double)arg3 toHigh:(double)arg4 value:(double)arg5;

@end

