//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "HUBContentOperationContext-Protocol.h"

@class NSError, NSURL;
@protocol HUBFeatureInfo, HUBViewModelBuilder;

@interface HUBContentOperationContextImplementation : NSObject <HUBContentOperationContext>
{
    NSURL *_viewURI;
    id <HUBFeatureInfo> _featureInfo;
    unsigned long long _connectivityState;
    id <HUBViewModelBuilder> _viewModelBuilder;
    NSError *_previousError;
}

@property(readonly, nonatomic) NSError *previousError; // @synthesize previousError=_previousError;
@property(readonly, nonatomic) id <HUBViewModelBuilder> viewModelBuilder; // @synthesize viewModelBuilder=_viewModelBuilder;
@property(readonly, nonatomic) unsigned long long connectivityState; // @synthesize connectivityState=_connectivityState;
@property(readonly, nonatomic) id <HUBFeatureInfo> featureInfo; // @synthesize featureInfo=_featureInfo;
@property(readonly, copy, nonatomic) NSURL *viewURI; // @synthesize viewURI=_viewURI;
- (void).cxx_destruct;
- (id)initWithViewURI:(id)arg1 featureInfo:(id)arg2 connectivityState:(unsigned long long)arg3 viewModelBuilder:(id)arg4 previousError:(id)arg5;

@end

