//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class HUBComponentGestureRecognizer;

@protocol HUBGestureRecognizerSynchronizing
- (_Bool)gestureRecognizerShouldBeginHandlingTouches:(HUBComponentGestureRecognizer *)arg1;
- (void)gestureRecognizerDidFinishHandlingTouches:(HUBComponentGestureRecognizer *)arg1;
- (void)gestureRecognizerDidBeginHandlingTouches:(HUBComponentGestureRecognizer *)arg1;
@end

