//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "HUGSThemableComponent.h"

#import "HUBComponentWithSelectionState-Protocol.h"

@class NSSet, UIView;
@protocol HUBComponentModel;

@interface HUGSCalendarRowComponent : HUGSThemableComponent <HUBComponentWithSelectionState>
{
    UIView *_view;
    id <HUBComponentModel> _componentModel;
}

@property(retain, nonatomic) id <HUBComponentModel> componentModel; // @synthesize componentModel=_componentModel;
@property(retain, nonatomic) UIView *view; // @synthesize view=_view;
- (void).cxx_destruct;
- (_Bool)modelContainsCalendarWithModel:(id)arg1;
- (void)configureCalendarView:(id)arg1 withModel:(id)arg2 style:(id)arg3 containerViewSize:(struct CGSize)arg4;
- (void)addDisclosureIndicatorViewIfNeededToView:(id)arg1 model:(id)arg2;
- (void)addCalendarViewIfNeededToView:(id)arg1 model:(id)arg2;
- (id)styleForComponentModel:(id)arg1;
- (void)applyThemeLayout;
- (void)prepareViewForReuse;
- (void)updateViewForSelectionState:(unsigned long long)arg1;
- (struct CGSize)preferredViewSizeForDisplayingModel:(id)arg1 containerViewSize:(struct CGSize)arg2;
- (void)configureViewWithModel:(id)arg1 containerViewSize:(struct CGSize)arg2;
- (void)loadView;
@property(readonly, nonatomic) NSSet *layoutTraits;

@end

