//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IDFlushable-Protocol.h"
#import "IDHmiServiceLifecycleProtocol-Protocol.h"

@class IDTableData, IDTableLocation, IDWidgetHmiService, NSString;

@interface IDListModel : NSObject <IDHmiServiceLifecycleProtocol, IDFlushable>
{
    long long _identifier;
    long long _totalRows;
    long long _totalColumns;
    IDTableLocation *_tableLocation;
    IDTableData *_tableData;
    IDWidgetHmiService *_widgetHmiService;
}

+ (id)emptyListModelWithId:(long long)arg1;
@property __weak IDWidgetHmiService *widgetHmiService; // @synthesize widgetHmiService=_widgetHmiService;
@property(retain, nonatomic) IDTableData *tableData; // @synthesize tableData=_tableData;
@property(retain, nonatomic) IDTableLocation *tableLocation; // @synthesize tableLocation=_tableLocation;
@property(nonatomic) long long totalColumns; // @synthesize totalColumns=_totalColumns;
@property(nonatomic) long long totalRows; // @synthesize totalRows=_totalRows;
@property long long identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)flushWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)widgetHmiServiceDidStop:(id)arg1;
- (void)widgetHmiServiceDidStart:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithId:(long long)arg1 totalRows:(long long)arg2 totalColumns:(long long)arg3 tableLocation:(id)arg4 tableData:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

