//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "GLUEThemeObserver-Protocol.h"
#import "SPContentInsetViewController-Protocol.h"
#import "SPObjectRepresentation-Protocol.h"
#import "SPTArtistAboutBiographyViewDelegate-Protocol.h"
#import "SPTArtistAboutViewModelDelegate-Protocol.h"
#import "SPTNavigationControllerNavigationBarState-Protocol.h"
#import "SPTPageController-Protocol.h"

@class NSString, NSURL, SPTArtistAboutBiographyView, SPTArtistAboutGLUETheme, SPTArtistAboutImageGalleryViewController, SPTArtistAboutLogger, SPTArtistAboutMonthlyListenersView, SPTArtistAboutViewModel, SPTInfoView, SPTProgressView, UIStackView;
@protocol GLUEImageLoader, SPTLinkDispatcher, SPTPageContainer, SPTViewLogger;

@interface SPTArtistAboutViewController : UIViewController <SPTArtistAboutViewModelDelegate, SPTArtistAboutBiographyViewDelegate, GLUEThemeObserver, SPTNavigationControllerNavigationBarState, SPContentInsetViewController, SPObjectRepresentation, SPTPageController>
{
    SPTArtistAboutViewModel *_viewModel;
    id <GLUEImageLoader> _glueImageLoader;
    id <SPTViewLogger> _viewLogger;
    SPTArtistAboutLogger *_logger;
    SPTArtistAboutGLUETheme *_theme;
    SPTProgressView *_loadingView;
    SPTInfoView *_infoView;
    UIStackView *_rootStackView;
    UIStackView *_textStackView;
    SPTArtistAboutImageGalleryViewController *_imageGalleryViewController;
    SPTArtistAboutMonthlyListenersView *_monthlyListenersView;
    SPTArtistAboutBiographyView *_biographyView;
    id <SPTLinkDispatcher> _linkDispatcher;
}

@property(nonatomic) __weak id <SPTLinkDispatcher> linkDispatcher; // @synthesize linkDispatcher=_linkDispatcher;
@property(retain, nonatomic) SPTArtistAboutBiographyView *biographyView; // @synthesize biographyView=_biographyView;
@property(retain, nonatomic) SPTArtistAboutMonthlyListenersView *monthlyListenersView; // @synthesize monthlyListenersView=_monthlyListenersView;
@property(retain, nonatomic) SPTArtistAboutImageGalleryViewController *imageGalleryViewController; // @synthesize imageGalleryViewController=_imageGalleryViewController;
@property(retain, nonatomic) UIStackView *textStackView; // @synthesize textStackView=_textStackView;
@property(retain, nonatomic) UIStackView *rootStackView; // @synthesize rootStackView=_rootStackView;
@property(retain, nonatomic) SPTInfoView *infoView; // @synthesize infoView=_infoView;
@property(retain, nonatomic) SPTProgressView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) SPTArtistAboutGLUETheme *theme; // @synthesize theme=_theme;
@property(retain, nonatomic) SPTArtistAboutLogger *logger; // @synthesize logger=_logger;
@property(retain, nonatomic) id <SPTViewLogger> viewLogger; // @synthesize viewLogger=_viewLogger;
@property(retain, nonatomic) id <GLUEImageLoader> glueImageLoader; // @synthesize glueImageLoader=_glueImageLoader;
@property(retain, nonatomic) SPTArtistAboutViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=spt_pageURI) NSURL *pageURI;
@property(readonly, nonatomic, getter=spt_pageIdentifier) NSString *pageIdentifier;
- (id)URI;
- (void)sp_updateContentInsets;
- (unsigned long long)preferredNavigationBarState;
- (void)externalLinkTapped:(id)arg1;
- (void)externalSocialLinkTappedForType:(unsigned long long)arg1;
- (void)artistAboutViewModel:(id)arg1 isOffline:(_Bool)arg2;
- (void)artistAboutViewModel:(id)arg1 isLoading:(_Bool)arg2;
- (void)artistAboutViewModel:(id)arg1 failedWithError:(id)arg2;
- (void)artistAboutViewModel:(id)arg1 loadedDataWithError:(id)arg2;
- (void)showInfoViewForError:(id)arg1;
- (void)showOfflineView;
- (void)showErrorView;
- (void)hideInfoView;
- (void)showInfoView;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)themeUpdated:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)addLayoutConstraints;
- (void)setupView;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithViewModel:(id)arg1 glueImageLoader:(id)arg2 theme:(id)arg3 viewLogger:(id)arg4 logger:(id)arg5 linkDispatcher:(id)arg6;

// Remaining properties
@property(nonatomic) _Bool automaticallyAdjustsScrollViewInsets;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=spt_pageContainer) id <SPTPageContainer> pageContainer;
@property(readonly) Class superclass;

@end

