//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SPTCollectionPlatformFieldName-Protocol.h"
#import "SPTCollectionPlatformFieldURL-Protocol.h"
#import "SPTCollectionPlatformTrackAlbumCovers-Protocol.h"
#import "SPTCollectionPlatformTrackArtists-Protocol.h"
#import "SPTCollectionPlatformTrackIsExplicit-Protocol.h"
#import "SPTCollectionPlatformTrackPreviewId-Protocol.h"

@protocol SPTAssistedCurationCollectionPlatformTrackFields <SPTCollectionPlatformFieldName, SPTCollectionPlatformFieldURL, SPTCollectionPlatformTrackArtists, SPTCollectionPlatformTrackAlbumCovers, SPTCollectionPlatformTrackIsExplicit, SPTCollectionPlatformTrackPreviewId>
@end

