//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SPTAbbaFeatureFlags;

@interface SPTBundlingTestManager : NSObject
{
    id <SPTAbbaFeatureFlags> _featureFlags;
}

@property(readonly, nonatomic) id <SPTAbbaFeatureFlags> featureFlags; // @synthesize featureFlags=_featureFlags;
- (void).cxx_destruct;
- (_Bool)shouldRequestOfferConfiguration;
- (id)initWithFeatureFlags:(id)arg1;

@end

