//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "EXP_HUBViewContentOffsetObserver-Protocol.h"
#import "SPTBrowseViewModelProviderObserver-Protocol.h"
#import "SPTNavigationControllerNavigationBarState-Protocol.h"
#import "SPTPageController-Protocol.h"

@class EXP_SPTHubViewController, NSString, NSURL, SPTProgressView, SPTTheme, VISREFIntegrationManager;
@protocol SPTBrowseViewModelProvider, SPTPageContainer;

@interface SPTBrowseViewController : UIViewController <SPTBrowseViewModelProviderObserver, SPTNavigationControllerNavigationBarState, EXP_HUBViewContentOffsetObserver, SPTPageController>
{
    SPTProgressView *_progressView;
    id <SPTBrowseViewModelProvider> _viewModelProvider;
    EXP_SPTHubViewController *_hubsViewController;
    unsigned long long _preferredNavigationBarState;
    SPTTheme *_theme;
    VISREFIntegrationManager *_visualRefreshIntegrationManager;
}

@property(retain, nonatomic) VISREFIntegrationManager *visualRefreshIntegrationManager; // @synthesize visualRefreshIntegrationManager=_visualRefreshIntegrationManager;
@property(readonly, nonatomic) SPTTheme *theme; // @synthesize theme=_theme;
@property(nonatomic) unsigned long long preferredNavigationBarState; // @synthesize preferredNavigationBarState=_preferredNavigationBarState;
@property(readonly, nonatomic) EXP_SPTHubViewController *hubsViewController; // @synthesize hubsViewController=_hubsViewController;
@property(readonly, nonatomic) id <SPTBrowseViewModelProvider> viewModelProvider; // @synthesize viewModelProvider=_viewModelProvider;
- (void).cxx_destruct;
- (void)performIgnoringOffsetChangeCallbacks:(CDUnknownBlockType)arg1;
- (unsigned long long)navigationBarStateForViewModel:(id)arg1;
- (struct CGRect)statusBarFrame;
- (void)updateWithViewModel:(id)arg1;
- (void)hubView:(id)arg1 contentOffsetDidChange:(struct CGPoint)arg2;
- (void)sp_updateContentInsets;
@property(readonly, nonatomic, getter=spt_pageIdentifier) NSString *pageIdentifier;
@property(readonly, nonatomic, getter=spt_pageURI) NSURL *pageURI;
- (void)viewModelProvider:(id)arg1 didUpdateStateFrom:(unsigned long long)arg2;
- (void)viewModelProvider:(id)arg1 didUpdateFromViewModel:(id)arg2;
- (void)viewDidLoad;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
@property(readonly, nonatomic) SPTProgressView *progressView; // @synthesize progressView=_progressView;
- (id)initWithViewModelProvider:(id)arg1 theme:(id)arg2 pageIdentifier:(id)arg3 pageURI:(id)arg4 componentRegistry:(id)arg5 componentLayoutManager:(id)arg6 imageLoaderFactory:(id)arg7 commandHandler:(id)arg8 impressionLogger:(id)arg9 loadingLogger:(id)arg10 visualRefreshIntegrationManager:(id)arg11;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=spt_pageContainer) id <SPTPageContainer> pageContainer;
@property(readonly) Class superclass;

@end

