//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTFeatureSettingsUIPresentationContext-Protocol.h"

@class NSString, SPTFeatureSettingsItem, UINavigationController, UITableView;

@interface SPTConcreteFeatureSettingsUIPresentationContext : NSObject <SPTFeatureSettingsUIPresentationContext>
{
    SPTFeatureSettingsItem *_item;
    UINavigationController *_navigationController;
    UITableView *_tableView;
}

@property(readonly, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(readonly, nonatomic) UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(readonly, nonatomic) SPTFeatureSettingsItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)reloadData;
- (id)dequeueReusableCellWithIdentifier:(id)arg1;
- (id)initWithFeatureSettingsItem:(id)arg1 tableView:(id)arg2 navigationController:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

