//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, SPTDataLoaderRequest;
@protocol SPTDataLoaderRequestResponseHandler;

@protocol SPTDataLoaderRequestResponseHandlerDelegate <NSObject>
- (void)requestResponseHandler:(id <SPTDataLoaderRequestResponseHandler>)arg1 cancelRequest:(SPTDataLoaderRequest *)arg2;
- (void)requestResponseHandler:(id <SPTDataLoaderRequestResponseHandler>)arg1 performRequest:(SPTDataLoaderRequest *)arg2;

@optional
- (void)requestResponseHandler:(id <SPTDataLoaderRequestResponseHandler>)arg1 failedToAuthoriseRequest:(SPTDataLoaderRequest *)arg2 error:(NSError *)arg3;
- (void)requestResponseHandler:(id <SPTDataLoaderRequestResponseHandler>)arg1 authorisedRequest:(SPTDataLoaderRequest *)arg2;
@end

