//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, SPTDrivingMotionRecorder, SPTDrivingMotionRecorderMeasurement, SPTDrivingMotionRecorderResult;

@protocol SPTDrivingMotionRecorderDelegate <NSObject>

@optional
- (void)motionRecorder:(SPTDrivingMotionRecorder *)arg1 didFinishRecordingWithResult:(SPTDrivingMotionRecorderResult *)arg2;
- (void)motionRecorder:(SPTDrivingMotionRecorder *)arg1 didReceiveGyroscopeMeasurement:(SPTDrivingMotionRecorderMeasurement *)arg2 error:(NSError *)arg3;
- (void)motionRecorder:(SPTDrivingMotionRecorder *)arg1 didReceiveAccelerometerMeasurement:(SPTDrivingMotionRecorderMeasurement *)arg2 error:(NSError *)arg3;
@end

