//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SPTExternalIntegrationSearchRequestContentFactory : NSObject
{
}

- (id)skipToTrackForItemDictionary:(id)arg1 inSection:(id)arg2;
- (id)contextURIForItemDictionary:(id)arg1 inSection:(id)arg2;
- (id)imageURLForItemDictionary:(id)arg1;
- (id)subTitleForItemDictionary:(id)arg1 inSection:(id)arg2;
- (long long)iconForSection:(id)arg1;
- (id)contentItemsForSectionDictionary:(id)arg1 inSection:(id)arg2;
- (id)searchResponseContentDictionaryForJSONDictionary:(id)arg1;

@end

