//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GLUEStyleable-Protocol.h"

@class GLUEAccessoryIconButton, NSLayoutConstraint, NSString, UIStackView;

@interface SPTFreeTierPreCurationQuickActionView : UIView <GLUEStyleable>
{
    GLUEAccessoryIconButton *_contextMenuButton;
    GLUEAccessoryIconButton *_likeButton;
    GLUEAccessoryIconButton *_banButton;
    UIStackView *_buttonContainerView;
    UIView *_spacerView;
    NSLayoutConstraint *_spacerWidthConstraint;
}

@property(retain, nonatomic) NSLayoutConstraint *spacerWidthConstraint; // @synthesize spacerWidthConstraint=_spacerWidthConstraint;
@property(retain, nonatomic) UIView *spacerView; // @synthesize spacerView=_spacerView;
@property(retain, nonatomic) UIStackView *buttonContainerView; // @synthesize buttonContainerView=_buttonContainerView;
@property(retain, nonatomic) GLUEAccessoryIconButton *banButton; // @synthesize banButton=_banButton;
@property(retain, nonatomic) GLUEAccessoryIconButton *likeButton; // @synthesize likeButton=_likeButton;
@property(retain, nonatomic) GLUEAccessoryIconButton *contextMenuButton; // @synthesize contextMenuButton=_contextMenuButton;
- (void).cxx_destruct;
- (void)hideLikeButton;
- (void)hideBanButton;
- (void)glue_applyStyle:(id)arg1;
- (void)addViewConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

