//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SPTAsyncScheduler;

@interface SPTFacebookPermissionsLookupJob : NSObject
{
    struct FacebookService *_facebook_service;
    id <SPTAsyncScheduler> _scheduler;
}

+ (id)facebookPermissionsLookupJobWithFacebookService:(struct FacebookService *)arg1 andScheduler:(id)arg2;
@property(nonatomic) __weak id <SPTAsyncScheduler> scheduler; // @synthesize scheduler=_scheduler;
@property(nonatomic) struct FacebookService *facebook_service; // @synthesize facebook_service=_facebook_service;
- (void).cxx_destruct;
- (void)invalidate;
- (void)run:(CDUnknownBlockType)arg1;
- (id)initWithFacebookService:(struct FacebookService *)arg1 andScheduler:(id)arg2;

@end

