//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface SPTFreeTierPlaylistTrackShuffler : NSObject
{
    NSArray *_randomNumbers;
}

@property(copy, nonatomic) NSArray *randomNumbers; // @synthesize randomNumbers=_randomNumbers;
- (void).cxx_destruct;
- (double)weightForTrack:(id)arg1 recommendedTrack:(_Bool)arg2 mergedList:(_Bool)arg3;
- (id)weightedShuffleListWithTracks:(id)arg1 recommendations:(id)arg2;
- (void)setUpRandomNumbers;
- (id)init;

@end

