//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError;
@protocol SPTFreeTierPlaylistViewModel;

@protocol SPTFreeTierPlaylistViewModelDelegate <NSObject>
- (void)playlistSponsorshipDidChange;
- (void)freeTierPlaylistViewModel:(id <SPTFreeTierPlaylistViewModel>)arg1 error:(NSError *)arg2;
- (void)freeTierPlaylistViewModel:(id <SPTFreeTierPlaylistViewModel>)arg1 initialFollowCount:(unsigned long long)arg2;
- (void)freeTierPlaylistViewModelDidChangeEmptyState:(id <SPTFreeTierPlaylistViewModel>)arg1;
- (void)freeTierPlaylistViewModelDidChange:(id <SPTFreeTierPlaylistViewModel>)arg1;
@end

