//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SPTFreeTierPlaylistHeaderContent-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSArray, NSString, SPTFreeTierPlaylistHeaderPageContainerViewStyle, SPTPageControl, UIScrollView;
@protocol SPTFreeTierPlaylistHeaderPageContainerViewDelegate;

@interface SPTFreeTierPlaylistHeaderPageContainerView : UIView <UIScrollViewDelegate, SPTFreeTierPlaylistHeaderContent>
{
    _Bool _didScrollToFirstViewForRTL;
    id <SPTFreeTierPlaylistHeaderPageContainerViewDelegate> _delegate;
    UIScrollView *_pageScrollView;
    SPTPageControl *_pageControl;
    SPTFreeTierPlaylistHeaderPageContainerViewStyle *_style;
    NSArray *_pages;
}

+ (_Bool)requiresConstraintBasedLayout;
@property(nonatomic) _Bool didScrollToFirstViewForRTL; // @synthesize didScrollToFirstViewForRTL=_didScrollToFirstViewForRTL;
@property(readonly, nonatomic) NSArray *pages; // @synthesize pages=_pages;
@property(readonly, nonatomic) SPTFreeTierPlaylistHeaderPageContainerViewStyle *style; // @synthesize style=_style;
@property(retain, nonatomic) SPTPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIScrollView *pageScrollView; // @synthesize pageScrollView=_pageScrollView;
@property(nonatomic) __weak id <SPTFreeTierPlaylistHeaderPageContainerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)notifyDelegate;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (id)titleView;
- (void)layoutSubviews;
- (void)setupConstraints;
- (void)setup;
- (id)initWithPages:(id)arg1 style:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

