//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SettingsSection.h"

@class SettingsSwitchTableViewCell;
@protocol SPTGaiaSettingsProvider, SPTLogCenter;

@interface SPTGaiaLockScreenControlsSettingsSection : SettingsSection
{
    SettingsSwitchTableViewCell *_lockScreenControlCell;
    id <SPTLogCenter> _logCenter;
    id <SPTGaiaSettingsProvider> _settingsProvider;
}

@property(retain, nonatomic) id <SPTGaiaSettingsProvider> settingsProvider; // @synthesize settingsProvider=_settingsProvider;
@property(readonly, nonatomic) id <SPTLogCenter> logCenter; // @synthesize logCenter=_logCenter;
@property(retain, nonatomic) SettingsSwitchTableViewCell *lockScreenControlCell; // @synthesize lockScreenControlCell=_lockScreenControlCell;
- (void).cxx_destruct;
- (void)lockScreenOptionChanged:(id)arg1;
- (id)footerText;
- (id)cellForRow:(long long)arg1;
- (long long)numberOfRows;
- (id)initWithSettingsViewController:(id)arg1 logCenter:(id)arg2 settingsProvider:(id)arg3;

@end

