//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SPTThemableView-Protocol.h"

@class GLUEButton, GLUELabel, NSString, SPTTheme;
@protocol SPTGaiaEducationTooltipActionDelegate, SPTThemableViewLayoutDelegate;

@interface SPTGaiaEducationTooltipContentView : UIView <SPTThemableView>
{
    id <SPTThemableViewLayoutDelegate> _layoutDelegate;
    id <SPTGaiaEducationTooltipActionDelegate> _delegate;
    long long _context;
    SPTTheme *_theme;
    GLUELabel *_textLabel;
    GLUEButton *_actionButton;
}

@property(retain, nonatomic) GLUEButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) GLUELabel *textLabel; // @synthesize textLabel=_textLabel;
@property(readonly, nonatomic) SPTTheme *theme; // @synthesize theme=_theme;
@property(readonly, nonatomic) long long context; // @synthesize context=_context;
@property(nonatomic) __weak id <SPTGaiaEducationTooltipActionDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SPTThemableViewLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
- (void).cxx_destruct;
- (void)applyThemeLayout;
- (void)applyActionButtonStyle;
- (void)applyMainLabelStyle;
- (void)actionButtonPressed;
- (void)addLayoutConstraints;
- (void)configureActionButtonWithContent:(id)arg1;
- (void)configureMainLabelWithContent:(id)arg1;
- (id)initWithTheme:(id)arg1 message:(id)arg2 actionText:(id)arg3 context:(long long)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

