//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol EXP_HUBComponentModel;

@protocol SPTHomeUICarouselChildSizingDelegate <NSObject>
- (struct CGSize)sizeForChildAtIndex:(unsigned long long)arg1 inModel:(id <EXP_HUBComponentModel>)arg2 containerSize:(struct CGSize)arg3;
@end

