//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTHugsFactory-Protocol.h"

@class EXP_HUGSComponentFallbackHandler, EXP_HUGSComponentLayoutManager, HUGSIconImageResolver, NSString;
@protocol GLUETheme;

@interface SPTHugsFactoryImplementation : NSObject <SPTHugsFactory>
{
    id <GLUETheme> _theme;
    HUGSIconImageResolver *_iconImageResolver;
    EXP_HUGSComponentLayoutManager *_componentLayoutManager;
    EXP_HUGSComponentFallbackHandler *_componentFallbackHandler;
}

@property(readonly, nonatomic) EXP_HUGSComponentFallbackHandler *componentFallbackHandler; // @synthesize componentFallbackHandler=_componentFallbackHandler;
@property(readonly, nonatomic) EXP_HUGSComponentLayoutManager *componentLayoutManager; // @synthesize componentLayoutManager=_componentLayoutManager;
@property(readonly, nonatomic) HUGSIconImageResolver *iconImageResolver; // @synthesize iconImageResolver=_iconImageResolver;
@property(readonly, nonatomic) id <GLUETheme> theme; // @synthesize theme=_theme;
- (void).cxx_destruct;
- (id)createHugs2Components;
- (id)createHugsComponentsWithStyleOverrider:(id)arg1;
- (id)provideSimpleComponentFallbackHandler;
- (id)provideComponentFallbackHandler;
- (id)provideComponentLayoutManager;
- (id)provideIconImageResolver;
- (id)createStyleOverriderWithComponentModelURIResolver:(id)arg1;
- (id)createComponentRegistryWithComponentModelURIResolver:(id)arg1 fallbackHandler:(id)arg2;
- (id)createComponentRegistryWithComponentModelURIResolver:(id)arg1;
- (id)initWithTheme:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

