//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GLUEStyleable-Protocol.h"

@class GLUEButton, GLUELabel, NSLayoutConstraint, NSString;

@interface SPTLoginAutosendLinkFirstVersionView : UIView <GLUEStyleable>
{
    GLUELabel *_titleLabel;
    GLUELabel *_messageLabel;
    GLUEButton *_actionButton;
    UIView *_contentView;
    NSLayoutConstraint *_contentHorizontalMargin;
    NSLayoutConstraint *_titleTopGap;
    NSLayoutConstraint *_messageTopGap;
    NSLayoutConstraint *_actionButtonTopGap;
    NSLayoutConstraint *_actionButtonBottomGap;
}

@property(retain, nonatomic) NSLayoutConstraint *actionButtonBottomGap; // @synthesize actionButtonBottomGap=_actionButtonBottomGap;
@property(retain, nonatomic) NSLayoutConstraint *actionButtonTopGap; // @synthesize actionButtonTopGap=_actionButtonTopGap;
@property(retain, nonatomic) NSLayoutConstraint *messageTopGap; // @synthesize messageTopGap=_messageTopGap;
@property(retain, nonatomic) NSLayoutConstraint *titleTopGap; // @synthesize titleTopGap=_titleTopGap;
@property(retain, nonatomic) NSLayoutConstraint *contentHorizontalMargin; // @synthesize contentHorizontalMargin=_contentHorizontalMargin;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(readonly, nonatomic) GLUEButton *actionButton; // @synthesize actionButton=_actionButton;
@property(readonly, nonatomic) GLUELabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(readonly, nonatomic) GLUELabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)glue_applyStyle:(id)arg1;
- (void)setupConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

