//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;
@protocol SPTLogCenter;

@interface SPTLanguageOnboardingLogger : NSObject
{
    id <SPTLogCenter> _logCenter;
    NSURL *_uri;
    NSURL *_errorDialogUri;
    NSString *_renderType;
}

@property(copy, nonatomic) NSString *renderType; // @synthesize renderType=_renderType;
@property(retain, nonatomic) NSURL *errorDialogUri; // @synthesize errorDialogUri=_errorDialogUri;
@property(retain, nonatomic) NSURL *uri; // @synthesize uri=_uri;
@property(readonly, nonatomic) id <SPTLogCenter> logCenter; // @synthesize logCenter=_logCenter;
- (void).cxx_destruct;
- (void)logToggleInteractionWithIdentifier:(id)arg1 position:(unsigned long long)arg2 didSelect:(_Bool)arg3;
- (void)logDialogInteractionWithTargetUri:(id)arg1;
- (void)logInteractionWithTargetUri:(id)arg1 interactionType:(id)arg2 userIntent:(id)arg3;
- (void)logImpressionWithTargetURI:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)logDialogImpressionWithTargetURI:(id)arg1;
- (void)logPageImpressionWithTargetURI:(id)arg1 type:(id)arg2;
- (void)logLanguagesScrolled;
- (void)logDeselectLanguageWithIdentifier:(id)arg1 position:(unsigned long long)arg2;
- (void)logSelectLanguageWithIdentifier:(id)arg1 position:(unsigned long long)arg2;
- (void)logSkipButtonInteraction;
- (void)logRetryButtonInteraction;
- (void)logNextButtonInteraction;
- (void)logLanguageImpressionWithIdentifier:(id)arg1 position:(unsigned long long)arg2;
- (void)logSkipButtonImpression;
- (void)logRetryButtonImpression;
- (void)logNextButtonImpression;
- (void)logErrorDialogImpression;
- (void)logNoNetworkViewImpression;
- (void)logLanguagesViewImpression;
- (void)logLoadingViewImpression;
- (id)initWithLogCenter:(id)arg1 uri:(id)arg2 errorDialogUri:(id)arg3 renderType:(id)arg4;

@end

