//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTService-Protocol.h"

@class NSString, SPTAllocationContext, SPTLoginKeychainCredentialsWriter, SPTLoginSignupMarketingOptInFlashController;
@protocol SPTCoreService, SPTFeatureFlaggingService, SPTLoginService, SPTNotificationsService, SPTSessionService, SPTURIDispatchService;

@interface SPTLoginSessionServiceImplementation : NSObject <SPTService>
{
    id <SPTCoreService> _coreService;
    id <SPTLoginService> _loginService;
    id <SPTSessionService> _sessionService;
    id <SPTURIDispatchService> _URIDispatchService;
    id <SPTNotificationsService> _notificationsService;
    id <SPTFeatureFlaggingService> _featureFlaggingService;
    SPTLoginKeychainCredentialsWriter *_credentialsWriter;
    SPTLoginSignupMarketingOptInFlashController *_marketingOptInController;
}

+ (id)serviceIdentifier;
@property(retain, nonatomic) SPTLoginSignupMarketingOptInFlashController *marketingOptInController; // @synthesize marketingOptInController=_marketingOptInController;
@property(retain, nonatomic) SPTLoginKeychainCredentialsWriter *credentialsWriter; // @synthesize credentialsWriter=_credentialsWriter;
@property(nonatomic) __weak id <SPTFeatureFlaggingService> featureFlaggingService; // @synthesize featureFlaggingService=_featureFlaggingService;
@property(nonatomic) __weak id <SPTNotificationsService> notificationsService; // @synthesize notificationsService=_notificationsService;
@property(nonatomic) __weak id <SPTURIDispatchService> URIDispatchService; // @synthesize URIDispatchService=_URIDispatchService;
@property(nonatomic) __weak id <SPTSessionService> sessionService; // @synthesize sessionService=_sessionService;
@property(nonatomic) __weak id <SPTLoginService> loginService; // @synthesize loginService=_loginService;
@property(nonatomic) __weak id <SPTCoreService> coreService; // @synthesize coreService=_coreService;
- (void).cxx_destruct;
- (void)storePreferredLocale;
- (void)load;
- (void)configureWithServices:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

