//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SPTLogMessage.h"

@class NSString;

@interface SPTLogMessageFeedInteraction1 : SPTLogMessage
{
    NSString *_sessionIdValue;
    NSString *_userIntentValue;
    NSString *_interactionOriginValue;
    NSString *_destinationUriValue;
}

+ (id)messageWithSessionId:(id)arg1 userIntent:(id)arg2 interactionOrigin:(id)arg3 destinationUri:(id)arg4;
@property(copy, nonatomic) NSString *destinationUriValue; // @synthesize destinationUriValue=_destinationUriValue;
@property(copy, nonatomic) NSString *interactionOriginValue; // @synthesize interactionOriginValue=_interactionOriginValue;
@property(copy, nonatomic) NSString *userIntentValue; // @synthesize userIntentValue=_userIntentValue;
@property(copy, nonatomic) NSString *sessionIdValue; // @synthesize sessionIdValue=_sessionIdValue;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)serialize;

@end

