//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTMandatoryPremiumTrialTestManager-Protocol.h"

@class NSString;
@protocol SPTFeatureFlagFactory, SPTFeatureFlagSignal;

@interface SPTMandatoryPremiumTrialTestManagerImplementation : NSObject <SPTMandatoryPremiumTrialTestManager>
{
    id <SPTFeatureFlagFactory> _featureFlagFactory;
    id <SPTFeatureFlagSignal> _inTrialSignal;
    id <SPTFeatureFlagSignal> _mandatoryPremiumTrialFlagSignal;
    id <SPTFeatureFlagSignal> _mandatoryPremiumTrialUserPolicySignal;
    long long _mandatoryPremiumTrialFlagState;
    long long _mandatoryPremiumTrialUserPolicyFlagState;
}

@property(nonatomic) long long mandatoryPremiumTrialUserPolicyFlagState; // @synthesize mandatoryPremiumTrialUserPolicyFlagState=_mandatoryPremiumTrialUserPolicyFlagState;
@property(nonatomic) long long mandatoryPremiumTrialFlagState; // @synthesize mandatoryPremiumTrialFlagState=_mandatoryPremiumTrialFlagState;
@property(retain, nonatomic) id <SPTFeatureFlagSignal> mandatoryPremiumTrialUserPolicySignal; // @synthesize mandatoryPremiumTrialUserPolicySignal=_mandatoryPremiumTrialUserPolicySignal;
@property(retain, nonatomic) id <SPTFeatureFlagSignal> mandatoryPremiumTrialFlagSignal; // @synthesize mandatoryPremiumTrialFlagSignal=_mandatoryPremiumTrialFlagSignal;
@property(retain, nonatomic) id <SPTFeatureFlagSignal> inTrialSignal; // @synthesize inTrialSignal=_inTrialSignal;
@property(readonly, nonatomic) id <SPTFeatureFlagFactory> featureFlagFactory; // @synthesize featureFlagFactory=_featureFlagFactory;
- (void).cxx_destruct;
- (_Bool)isUserPolicyEnabled;
- (_Bool)isFeatureEnabled;
- (void)featureFlagSignal:(id)arg1 hasAssumedState:(long long)arg2;
- (void)setupUserPolicySignal;
- (void)setupInTrialSignal;
- (void)setupABBAFlagSignal;
- (void)setupSignals;
- (void)dealloc;
- (id)initWithFeatureFlagFactory:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

