//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTMetaViewControllerObserver-Protocol.h"

@class NSString, SPCore;
@protocol SPTExternalLinkController, SPTMetaViewController;

@interface SPTNavigationRoutingLoginStateMonitor : NSObject <SPTMetaViewControllerObserver>
{
    SPCore *_core;
    id <SPTMetaViewController> _metaViewController;
    id <SPTExternalLinkController> _externalLinkController;
}

@property(retain, nonatomic) id <SPTExternalLinkController> externalLinkController; // @synthesize externalLinkController=_externalLinkController;
@property(retain, nonatomic) id <SPTMetaViewController> metaViewController; // @synthesize metaViewController=_metaViewController;
@property(nonatomic) __weak SPCore *core; // @synthesize core=_core;
- (void).cxx_destruct;
- (void)didChangeRootViewOfMetaViewController:(id)arg1;
- (void)willLogOut:(id)arg1;
- (_Bool)loggedInForURIDispatchPurposes;
- (id)initWithCore:(id)arg1 metaViewController:(id)arg2 externalLinkController:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

