//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTNowPlayingContentLayerProvider-Protocol.h"

@class NSString, SPTTheme;
@protocol SPTGLUEImageLoaderFactory;

@interface SPTNowPlayingCoverArtProvider : NSObject <SPTNowPlayingContentLayerProvider>
{
    SPTTheme *_theme;
    id <SPTGLUEImageLoaderFactory> _imageLoaderFactory;
}

@property(readonly, nonatomic) id <SPTGLUEImageLoaderFactory> imageLoaderFactory; // @synthesize imageLoaderFactory=_imageLoaderFactory;
@property(readonly, nonatomic) SPTTheme *theme; // @synthesize theme=_theme;
- (void).cxx_destruct;
- (_Bool)isActiveForTrack:(id)arg1;
- (void)configureCell:(id)arg1 withTrack:(id)arg2 windowedContentInsets:(struct UIEdgeInsets)arg3;
- (Class)cellClass;
- (id)contentIdentifier;
- (id)initWithTheme:(id)arg1 imageLoaderFactory:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

