//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SPTNowPlayingBarViewControllerObserver;

@protocol SPTNowPlayingBarViewControllerObservable <NSObject>
- (void)removeNowPlayingBarViewControllerObserver:(id <SPTNowPlayingBarViewControllerObserver>)arg1;
- (void)addNowPlayingBarViewControllerObserver:(id <SPTNowPlayingBarViewControllerObserver>)arg1;
@end

