//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;
@protocol SPTNowPlayingDurationUnitViewModelDelegate;

@protocol SPTNowPlayingDurationUnitViewModel <NSObject>
@property(nonatomic) __weak id <SPTNowPlayingDurationUnitViewModelDelegate> delegate;
- (void)updateObservers:(_Bool)arg1;
- (void)scrubbedToPosition:(double)arg1;
- (_Bool)disallowsSeeking;
- (double)animationSpeed;
- (NSString *)currentTimeRemainingTextWithSliderValue:(float)arg1;
- (NSString *)currentTrackProgressTextWithSliderValue:(float)arg1;
- (double)currentTrackLength;
- (double)currentTrackProgress;
@end

