//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray, SPTNowPlayingBackgroundCornersView, SPTNowPlayingBackgroundGradientView, SPTNowPlayingCarouselBackgroundBlurController, SPTNowPlayingCarouselBackgroundBlurView, SPTNowPlayingContentUnitProvider, SPTTheme;

@interface SPTNowPlayingBackgroundMusicViewController : UIViewController
{
    SPTNowPlayingContentUnitProvider *_contentUnitProvider;
    SPTTheme *_theme;
    SPTNowPlayingCarouselBackgroundBlurView *_backgroundView;
    SPTNowPlayingCarouselBackgroundBlurController *_blurController;
    SPTNowPlayingBackgroundGradientView *_backgroundGradientView;
    SPTNowPlayingBackgroundCornersView *_backgroundCornersView;
    NSArray *_layoutConstraints;
    NSArray *_extraLayoutConstraints;
}

@property(retain, nonatomic) NSArray *extraLayoutConstraints; // @synthesize extraLayoutConstraints=_extraLayoutConstraints;
@property(copy, nonatomic) NSArray *layoutConstraints; // @synthesize layoutConstraints=_layoutConstraints;
@property(retain, nonatomic) SPTNowPlayingBackgroundCornersView *backgroundCornersView; // @synthesize backgroundCornersView=_backgroundCornersView;
@property(retain, nonatomic) SPTNowPlayingBackgroundGradientView *backgroundGradientView; // @synthesize backgroundGradientView=_backgroundGradientView;
@property(retain, nonatomic) SPTNowPlayingCarouselBackgroundBlurController *blurController; // @synthesize blurController=_blurController;
@property(retain, nonatomic) SPTNowPlayingCarouselBackgroundBlurView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) SPTTheme *theme; // @synthesize theme=_theme;
@property(readonly, nonatomic) SPTNowPlayingContentUnitProvider *contentUnitProvider; // @synthesize contentUnitProvider=_contentUnitProvider;
- (void).cxx_destruct;
- (void)updateViewConstraints;
- (void)viewDidLoad;
- (id)initWithContentUnitProvider:(id)arg1 theme:(id)arg2;

@end

