//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SPTNowPlayingBaseHeadUnitView.h"

@class UIButton;

@interface SPTNowPlayingPodcastHeadUnitView : SPTNowPlayingBaseHeadUnitView
{
    UIButton *_leftAccessoryButton;
    UIButton *_rightAccessoryButton;
}

- (id)rightAccessoryButton;
- (id)leftAccessoryButton;
- (void).cxx_destruct;
- (id)initWithTheme:(id)arg1;

@end

