//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SPTNowPlayingVideoViewV2;

@protocol SPTNowPlayingVideoViewV2Delegate <NSObject>

@optional
- (void)videoViewSurfaceDidDetach:(SPTNowPlayingVideoViewV2 *)arg1;
- (void)videoViewSurfaceDidAttach:(SPTNowPlayingVideoViewV2 *)arg1;
- (void)videoView:(SPTNowPlayingVideoViewV2 *)arg1 didChangeControlsVisibility:(_Bool)arg2;
@end

