//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SPAction.h"

@protocol SPTNowPlayingManager;

@interface SPTNowPlayingViewQueueAction : SPAction
{
    id <SPTNowPlayingManager> _nowPlayingManager;
}

@property(nonatomic) __weak id <SPTNowPlayingManager> nowPlayingManager; // @synthesize nowPlayingManager=_nowPlayingManager;
- (void).cxx_destruct;
- (id)execute:(id)arg1;
- (id)logEventName;
- (long long)icon;
- (id)title;
- (id)initWithNowPlayingManager:(id)arg1 logContext:(id)arg2;

@end

