//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTNowPlayingModelObserver-Protocol.h"
#import "SPTNowPlayingTrackMetadataQueueObserver-Protocol.h"
#import "SPTNowPlayingTrackPositionObserver-Protocol.h"

@class NSString, SPTNowPlayingLogger, SPTNowPlayingModel, SPTNowPlayingPlaybackController, SPTNowPlayingSkipLimitReachedMessageRequester, SPTNowPlayingTrackMetadataQueue;
@protocol SPTNowPlayingCarouselModelDelegate;

@interface SPTNowPlayingCarouselModel : NSObject <SPTNowPlayingTrackMetadataQueueObserver, SPTNowPlayingModelObserver, SPTNowPlayingTrackPositionObserver>
{
    id <SPTNowPlayingCarouselModelDelegate> _delegate;
    SPTNowPlayingLogger *_logger;
    SPTNowPlayingSkipLimitReachedMessageRequester *_skipLimitReachedMessageRequester;
    SPTNowPlayingTrackMetadataQueue *_trackMetadataQueue;
    SPTNowPlayingPlaybackController *_playbackController;
    SPTNowPlayingModel *_nowPlayingModel;
}

@property(retain, nonatomic) SPTNowPlayingModel *nowPlayingModel; // @synthesize nowPlayingModel=_nowPlayingModel;
@property(retain, nonatomic) SPTNowPlayingPlaybackController *playbackController; // @synthesize playbackController=_playbackController;
@property(retain, nonatomic) SPTNowPlayingTrackMetadataQueue *trackMetadataQueue; // @synthesize trackMetadataQueue=_trackMetadataQueue;
@property(readonly, nonatomic) SPTNowPlayingSkipLimitReachedMessageRequester *skipLimitReachedMessageRequester; // @synthesize skipLimitReachedMessageRequester=_skipLimitReachedMessageRequester;
@property(retain, nonatomic) SPTNowPlayingLogger *logger; // @synthesize logger=_logger;
@property(nonatomic) __weak id <SPTNowPlayingCarouselModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)nowPlayingTrackPositionDidChange:(id)arg1;
- (void)nowPlayingModelDidUpdateMetadata:(id)arg1;
- (void)nowPlayingModel:(id)arg1 didMoveToRelativeTrack:(id)arg2;
- (void)trackMetadataQueueDidFinishUpdating:(id)arg1;
- (void)trackMetadataQueue:(id)arg1 didMoveToRelativeTrack:(id)arg2;
- (void)requestAnimation:(unsigned long long)arg1;
- (void)dragToRight;
- (void)attemptDragToLeft;
- (void)dragToLeft;
@property(readonly, nonatomic) unsigned long long dragToRightBehaviour;
@property(readonly, nonatomic) unsigned long long dragToLeftBehaviour;
- (_Bool)canShowRelativePage:(long long)arg1;
- (_Bool)canScrollToRelativePage:(long long)arg1;
- (_Bool)canScroll;
@property(readonly, nonatomic, getter=isPaused) _Bool paused;
- (_Bool)isLoading;
- (_Bool)isInSyncWithPlayer;
- (id)trackAtRelativePage:(long long)arg1;
- (_Bool)disallowDisplayingMetadataAtRelativePage:(long long)arg1;
- (void)dealloc;
- (id)initWithTrackMetadataQueue:(id)arg1 playbackController:(id)arg2 nowPlayingModel:(id)arg3 logger:(id)arg4 skipLimitReachedMessageRequester:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

