//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDate, NSString, SPTNRFItemContent, SPTNRFItemCreator;

@interface SPTNRFItem : NSObject
{
    NSString *_itemID;
    long long _itemType;
    NSString *_recommendationReason;
    SPTNRFItemCreator *_creator;
    NSArray *_creators;
    SPTNRFItemContent *_content;
    NSDate *_timestamp;
    NSString *_text;
}

@property(readonly, copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(readonly, copy, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, nonatomic) SPTNRFItemContent *content; // @synthesize content=_content;
@property(readonly, nonatomic) NSArray *creators; // @synthesize creators=_creators;
@property(readonly, nonatomic) SPTNRFItemCreator *creator; // @synthesize creator=_creator;
@property(readonly, copy, nonatomic) NSString *recommendationReason; // @synthesize recommendationReason=_recommendationReason;
@property(readonly, nonatomic) long long itemType; // @synthesize itemType=_itemType;
@property(readonly, copy, nonatomic) NSString *itemID; // @synthesize itemID=_itemID;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

