//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTNowPlayingBar_PlayButtonInteractionEventFactory-Protocol.h"

@class NSArray, NSString;

@interface SPTNowPlayingBar_PlayButtonInteractionEventFactoryImplementation : NSObject <SPTNowPlayingBar_PlayButtonInteractionEventFactory>
{
    NSArray *_components;
}

+ (id)factoryWithComponents:(id)arg1;
@property(copy, nonatomic) NSArray *components; // @synthesize components=_components;
- (void).cxx_destruct;
- (id)hitResumeWithTargetUri:(id)arg1;
- (id)hitPauseWithTargetUri:(id)arg1;
- (id)initWithComponents:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

