//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SPTNavigationItemsDeserialization : NSObject
{
}

+ (id)localizedTitleForSourceIdentifier:(id)arg1;
+ (id)deserializeNavigationItems:(id)arg1;
+ (id)deserializeItemsWithResourceAtURL:(id)arg1 identifier:(id)arg2;

@end

