//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSLocale, NSString, SPTPhoneNumberSignupPhoneNumberEntryModel;
@protocol SPTPhoneNumberSignupCallingCodeViewModelDelegate;

@interface SPTPhoneNumberSignupCallingCodeViewModel : NSObject
{
    _Bool _isCountrySelectionEnabled;
    NSString *_searchQueryText;
    SPTPhoneNumberSignupPhoneNumberEntryModel *_model;
    NSArray *_initialRowViewModels;
    NSArray *_filteredRowViewModels;
    id <SPTPhoneNumberSignupCallingCodeViewModelDelegate> _delegate;
    NSLocale *_locale;
}

@property(readonly, nonatomic) NSLocale *locale; // @synthesize locale=_locale;
@property(readonly) __weak id <SPTPhoneNumberSignupCallingCodeViewModelDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSArray *filteredRowViewModels; // @synthesize filteredRowViewModels=_filteredRowViewModels;
@property(copy, nonatomic) NSArray *initialRowViewModels; // @synthesize initialRowViewModels=_initialRowViewModels;
@property(readonly, nonatomic) __weak SPTPhoneNumberSignupPhoneNumberEntryModel *model; // @synthesize model=_model;
@property(nonatomic) _Bool isCountrySelectionEnabled; // @synthesize isCountrySelectionEnabled=_isCountrySelectionEnabled;
@property(copy, nonatomic) NSString *searchQueryText; // @synthesize searchQueryText=_searchQueryText;
- (void).cxx_destruct;
- (void)dealloc;
- (void)viewModelDidUpdate;
@property(readonly, nonatomic) unsigned long long numberOfRows;
- (id)rowViewModelAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long indexOfCurrentLocale;
- (id)filterRowViewModelsWithText:(id)arg1;
- (void)countriesDidUpdate;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)observeChangesInCountries;
- (id)setupAndSortRowViewModelsWithModel:(id)arg1;
- (id)initWithModel:(id)arg1 locale:(id)arg2 withDelegate:(id)arg3;

@end

