//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, SPTPartnerIntegrationAuthorizer, SPTPartnerIntegrationStateLoader, SPTPartnerTestManagerImplementation;
@protocol SPTPartnerIntegrationRegistry, SPTPartnerIntegrationSettingsViewModelDelegate;

@interface SPTPartnerIntegrationSettingsViewModel : NSObject
{
    id <SPTPartnerIntegrationSettingsViewModelDelegate> _delegate;
    NSArray *_sections;
    SPTPartnerIntegrationStateLoader *_stateLoader;
    SPTPartnerIntegrationAuthorizer *_authorizer;
    SPTPartnerTestManagerImplementation *_testManager;
    id <SPTPartnerIntegrationRegistry> _integrationRegistry;
}

@property(readonly, nonatomic) id <SPTPartnerIntegrationRegistry> integrationRegistry; // @synthesize integrationRegistry=_integrationRegistry;
@property(readonly, nonatomic) SPTPartnerTestManagerImplementation *testManager; // @synthesize testManager=_testManager;
@property(readonly, nonatomic) SPTPartnerIntegrationAuthorizer *authorizer; // @synthesize authorizer=_authorizer;
@property(readonly, nonatomic) SPTPartnerIntegrationStateLoader *stateLoader; // @synthesize stateLoader=_stateLoader;
@property(copy, nonatomic) NSArray *sections; // @synthesize sections=_sections;
@property(nonatomic) __weak id <SPTPartnerIntegrationSettingsViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)sectionsFromCategories:(id)arg1;
- (void)loadData;
- (id)initWithIntegrationStateLoader:(id)arg1 authorizer:(id)arg2 testManager:(id)arg3;

@end

