//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTPlaylistExtenderModelEvent-Protocol.h"

@class NSString, NSURL;

@interface SPTPlaylistExtenderModelEventTrackAdded : NSObject <SPTPlaylistExtenderModelEvent>
{
    unsigned long long _trackIndex;
    NSURL *_playlistURL;
}

@property(readonly, nonatomic) NSURL *playlistURL; // @synthesize playlistURL=_playlistURL;
@property(readonly, nonatomic) unsigned long long trackIndex; // @synthesize trackIndex=_trackIndex;
- (void).cxx_destruct;
- (void)processWithState:(id)arg1 loop:(id)arg2;
- (id)initWithTrackIndex:(unsigned long long)arg1 playlistURL:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

