//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSError, SPTPersistentCacheRecord;

@interface SPTPersistentCacheResponse : NSObject
{
    long long _result;
    NSError *_error;
    SPTPersistentCacheRecord *_record;
}

@property(retain, nonatomic) SPTPersistentCacheRecord *record; // @synthesize record=_record;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) long long result; // @synthesize result=_result;
- (void).cxx_destruct;
- (id)debugDescription;
- (id)description;
- (id)initWithResult:(long long)arg1 error:(id)arg2 record:(id)arg3;

@end

