//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSURL;

@protocol SPTQueueHeadUnitRegistry <NSObject>
- (UIViewController<SPTQueueTableHeaderViewController> * (^)(void))tableHeaderBlockForURI:(NSURL *)arg1;
- (void)registerTableHeaderBlock:(UIViewController<SPTQueueTableHeaderViewController> * (^)(void))arg1 withPredicate:(_Bool (^)(NSURL *))arg2;
- (UIViewController<SPTQueueHeadUnitViewController> * (^)(void))headUnitBlockForURI:(NSURL *)arg1;
- (void)registerHeadUnitBlock:(UIViewController<SPTQueueHeadUnitViewController> * (^)(void))arg1 withPredicate:(_Bool (^)(NSURL *))arg2;
@end

