//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SPTQueueSelectableLeadingView, SPTQueueTrack;

@protocol SPTQueueSelectableLeadingViewDelegate <NSObject>
- (void)queueCellLeadingView:(id <SPTQueueSelectableLeadingView>)arg1 didDeselectTrack:(id <SPTQueueTrack>)arg2;
- (void)queueCellLeadingView:(id <SPTQueueSelectableLeadingView>)arg1 didSelectTrack:(id <SPTQueueTrack>)arg2;
@end

