//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTSocialListeningSessionModelEntity-Protocol.h"

@class NSArray, NSString, NSURL, UIImage;

@interface SPTSocialListeningSession : NSObject <SPTSocialListeningSessionModelEntity>
{
    _Bool _sessionHost;
    NSArray *_connectedUsers;
    UIImage *_scannablesImage;
    NSString *_sessionID;
    NSString *_accessToken;
    NSURL *_joinSessionURL;
}

@property(readonly, nonatomic) NSURL *joinSessionURL; // @synthesize joinSessionURL=_joinSessionURL;
@property(readonly, copy, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
@property(readonly, copy, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
@property(retain, nonatomic) UIImage *scannablesImage; // @synthesize scannablesImage=_scannablesImage;
@property(readonly, nonatomic) NSArray *connectedUsers; // @synthesize connectedUsers=_connectedUsers;
@property(readonly, nonatomic, getter=isSessionHost) _Bool sessionHost; // @synthesize sessionHost=_sessionHost;
- (void).cxx_destruct;
@property(readonly) unsigned long long hash;
- (_Bool)isEqualToSession:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

