//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SPTSerializableCredentials : NSObject
{
    struct SerializableCredentials _credentials;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)authBlob;
- (id)username;
- (const struct SerializableCredentials *)cpp;
- (id)credentialsByTransferringToDeviceId:(id)arg1;
- (id)initWithSerializableCredentials:(struct SerializableCredentials)arg1;
- (id)initWithUsername:(id)arg1 authBlob:(id)arg2 deviceId:(id)arg3;

@end

