//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;
@protocol SPTVideoSubtitle;

@protocol SPTVideoSubtitleFactory <NSObject>
- (id <SPTVideoSubtitle>)createSubtitleWithLangtag:(NSString *)arg1 closedCaption:(_Bool)arg2;
- (id <SPTVideoSubtitle>)createSubtitleWithLangtag:(NSString *)arg1;
- (id <SPTVideoSubtitle>)offSubtitle;
@end

