//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SPTVideoSubtitleLayouter : NSObject
{
}

+ (void)updateAvPlayerItem:(id)arg1 withSubtitleWidthPercentage:(double)arg2 fontPercentage:(double)arg3;
+ (struct CGRect)adjustedDisplayViewFrameWithSurface:(id)arg1 videoAspectRatio:(double)arg2;
+ (double)fontSizeForVideoSize:(struct CGSize)arg1;
+ (struct CGSize)estimatedVideoSizeWithSurface:(id)arg1 videoAspectRatio:(double)arg2;
+ (void)layoutSubtitleWithSurface:(id)arg1 videoAspectRatio:(double)arg2 avPlayerItem:(id)arg3;

@end

