//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary, NSNumber, NSSet, NSString, NSURL, SPTObserverManager;
@protocol SPTLogCenter;

@interface SPTViewLogger : NSObject
{
    NSString *_pageIdentifier;
    long long _state;
    id <SPTLogCenter> _logCenter;
    NSURL *_viewURI;
    NSString *_connectionType;
    struct __CFRunLoopObserver *_runLoopObserver;
    NSMutableDictionary *_steps;
    NSString *_terminalState;
    NSMutableDictionary *_metaData;
    SPTObserverManager *_observerManager;
    NSNumber *_viewStartedLoadingAt;
    NSSet *_pendingImageLoadingRequests;
    NSArray *_finishedImageLoadingRequests;
}

@property(copy, nonatomic) NSArray *finishedImageLoadingRequests; // @synthesize finishedImageLoadingRequests=_finishedImageLoadingRequests;
@property(copy, nonatomic) NSSet *pendingImageLoadingRequests; // @synthesize pendingImageLoadingRequests=_pendingImageLoadingRequests;
@property(retain, nonatomic) NSNumber *viewStartedLoadingAt; // @synthesize viewStartedLoadingAt=_viewStartedLoadingAt;
@property(readonly, nonatomic) SPTObserverManager *observerManager; // @synthesize observerManager=_observerManager;
@property(retain, nonatomic) NSMutableDictionary *metaData; // @synthesize metaData=_metaData;
@property(copy, nonatomic) NSString *terminalState; // @synthesize terminalState=_terminalState;
@property(retain, nonatomic) NSMutableDictionary *steps; // @synthesize steps=_steps;
@property(nonatomic) struct __CFRunLoopObserver *runLoopObserver; // @synthesize runLoopObserver=_runLoopObserver;
@property(copy, nonatomic) NSString *connectionType; // @synthesize connectionType=_connectionType;
@property(copy, nonatomic) NSURL *viewURI; // @synthesize viewURI=_viewURI;
@property(nonatomic) __weak id <SPTLogCenter> logCenter; // @synthesize logCenter=_logCenter;
@property long long state; // @synthesize state=_state;
@property(copy, nonatomic) NSString *pageIdentifier; // @synthesize pageIdentifier=_pageIdentifier;
- (void).cxx_destruct;
- (void)removeImageLoadingRequest:(id)arg1;
- (void)addImageLoadingRequest:(id)arg1;
- (void)notifyObserversOfStateChange:(long long)arg1 timeSinceStart:(double)arg2;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)logViewLoadingRendered;
- (void)logViewLoadingCancelledWithPageIdentifier:(id)arg1;
- (void)logViewDataDidFailToLoadWithError:(id)arg1 pageIdentifier:(id)arg2;
- (void)logImageLoadingEndedForImageWithURI:(id)arg1;
- (void)logImageLoadingStartedForImageWithURI:(id)arg1;
- (void)logViewDataDidLoadWithPageIdentifier:(id)arg1;
- (void)logViewLoadingStartedWithPageIdentifier:(id)arg1;
- (_Bool)isViewLoadingInProgress;
- (void)reset;
- (void)terminateSequence;
- (void)logViewLoadWithStepName:(id)arg1 timeSinceStart:(double)arg2 isTerminalStep:(_Bool)arg3 terminateSequence:(_Bool)arg4;
- (double)durationSinceStart:(id)arg1;
- (void)dealloc;
- (id)initWithLogCenter:(id)arg1 viewURI:(id)arg2 connectionType:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

