//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SPTWAMPMessage-Protocol.h"

@class NSArray, NSDictionary, NSString;

@protocol SPTWAMPErrorMessage <SPTWAMPMessage>
@property(readonly, nonatomic) NSDictionary *namedArguments;
@property(readonly, nonatomic) NSArray *arguments;
@property(readonly, copy, nonatomic) NSString *error;
@property(readonly, nonatomic) NSDictionary *details;
@property(readonly, nonatomic) unsigned long long triggeringRequestID;
@property(readonly, nonatomic) long long triggeringRequestType;
@end

