//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (BMWAppKit)
- (id)idResizedImage:(struct CGSize)arg1 interpolationQuality:(int)arg2;
- (id)idPNGImageData;
- (id)idJPEGImageDataWithCompressionFactor:(float)arg1;
- (id)imageDataWithImageProperties:(id)arg1 andTargetImageType:(struct __CFString *)arg2;
- (id)grayscaleImage;
- (id)imageByAddingBackgroundColor:(id)arg1 toImage:(id)arg2;
- (_Bool)imageTypeSupportsAlpha:(struct __CFString *)arg1;
- (_Bool)imageHasAlphaChannel;
@end

