//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:12:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "VISREFTopAndBodyContentView.h"

#import "VISREFHeaderComponent-Protocol.h"
#import "VISREFHeaderViewAnimationProgress-Protocol.h"

@class NSLayoutConstraint, NSString, TKNLabel, UIButton, UIImage, UIStackView, VISREFAlignedImageView, VISREFGradientView;

@interface VISREFFullBleedContentView : VISREFTopAndBodyContentView <VISREFHeaderViewAnimationProgress, VISREFHeaderComponent>
{
    UIButton *_contextButton;
    UIButton *_followButton;
    VISREFGradientView *_titleProtectionGradient;
    VISREFGradientView *_statusBarProtectionGradient;
    TKNLabel *_titleLabel;
    TKNLabel *_metadataLabel;
    UIStackView *_buttonsStackView;
    VISREFAlignedImageView *_alignedImageView;
    NSLayoutConstraint *_imageWidthConstraint;
    double _lastProgress;
    CDStruct_5a28e70a _imageAlphaProgressRange;
    CDStruct_5a28e70a _statusBarProtectionProgressRange;
    CDStruct_5a28e70a _titleLabelAlphaProgressRange;
    CDStruct_5a28e70a _titleProtectionProgressRange;
}

@property(nonatomic) CDStruct_5a28e70a titleProtectionProgressRange; // @synthesize titleProtectionProgressRange=_titleProtectionProgressRange;
@property(nonatomic) CDStruct_5a28e70a titleLabelAlphaProgressRange; // @synthesize titleLabelAlphaProgressRange=_titleLabelAlphaProgressRange;
@property(nonatomic) CDStruct_5a28e70a statusBarProtectionProgressRange; // @synthesize statusBarProtectionProgressRange=_statusBarProtectionProgressRange;
@property(nonatomic) CDStruct_5a28e70a imageAlphaProgressRange; // @synthesize imageAlphaProgressRange=_imageAlphaProgressRange;
@property(nonatomic) double lastProgress; // @synthesize lastProgress=_lastProgress;
@property(retain, nonatomic) NSLayoutConstraint *imageWidthConstraint; // @synthesize imageWidthConstraint=_imageWidthConstraint;
@property(retain, nonatomic) VISREFAlignedImageView *alignedImageView; // @synthesize alignedImageView=_alignedImageView;
@property(retain, nonatomic) UIStackView *buttonsStackView; // @synthesize buttonsStackView=_buttonsStackView;
@property(retain, nonatomic) TKNLabel *metadataLabel; // @synthesize metadataLabel=_metadataLabel;
@property(retain, nonatomic) TKNLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) VISREFGradientView *statusBarProtectionGradient; // @synthesize statusBarProtectionGradient=_statusBarProtectionGradient;
@property(retain, nonatomic) VISREFGradientView *titleProtectionGradient; // @synthesize titleProtectionGradient=_titleProtectionGradient;
@property(retain, nonatomic) UIButton *followButton; // @synthesize followButton=_followButton;
@property(retain, nonatomic) UIButton *contextButton; // @synthesize contextButton=_contextButton;
- (void).cxx_destruct;
- (void)updateAccessibilityLabels;
- (void)headerViewDidRemountHeaderComponents:(id)arg1;
- (void)fullHeaderViewNormalizedProgressUpdate:(double)arg1;
- (void)headerViewNormalizedProgressUpdate:(double)arg1;
- (void)setAssociatedColor:(id)arg1;
- (void)setMetadataText:(id)arg1;
- (void)setTitle:(id)arg1;
@property(retain, nonatomic) UIImage *image;
- (void)setImage:(id)arg1 animated:(_Bool)arg2;
- (void)scaleImage:(double)arg1;
- (void)updateProgressPositions;
- (void)updateActionRow;
- (void)setupLayout;
- (void)setup;
- (id)initWithNaturalHeight:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

