//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "EXP_HUBContentOperation.h"
#import "SPTOfflineModeStateObserver.h"

@class NSError, NSString, SPTRequestLifetime, SPTResponse;

@interface EXP_SPTHubCosmosContentOperation : NSObject <SPTOfflineModeStateObserver, EXP_HUBContentOperation>
{
    _Bool _requestFiredOnce;
    id <EXP_HUBContentOperationDelegate> _delegate;
    id <EXP_SPTHubRemoteContentOperationURLResolver> _contentURLResolver;
    NSString *_sourceIdentifier;
    id <SPTResolver> _resolver;
    id <SPTOfflineModeState> _offlineModeState;
    id <EXP_HUBViewModelBuilder> _viewModelBuilder;
    NSError *_previousError;
    SPTRequestLifetime *_requestLifetime;
    SPTResponse *_storedResponse;
}

@property(retain, nonatomic) SPTResponse *storedResponse; // @synthesize storedResponse=_storedResponse;
@property(nonatomic, getter=isRequestExpected) _Bool requestFiredOnce; // @synthesize requestFiredOnce=_requestFiredOnce;
@property(retain, nonatomic) SPTRequestLifetime *requestLifetime; // @synthesize requestLifetime=_requestLifetime;
@property(retain, nonatomic) NSError *previousError; // @synthesize previousError=_previousError;
@property(retain, nonatomic) id <EXP_HUBViewModelBuilder> viewModelBuilder; // @synthesize viewModelBuilder=_viewModelBuilder;
@property(readonly, nonatomic) id <SPTOfflineModeState> offlineModeState; // @synthesize offlineModeState=_offlineModeState;
@property(readonly, nonatomic) id <SPTResolver> resolver; // @synthesize resolver=_resolver;
@property(readonly, copy, nonatomic) NSString *sourceIdentifier; // @synthesize sourceIdentifier=_sourceIdentifier;
@property(readonly, nonatomic) id <EXP_SPTHubRemoteContentOperationURLResolver> contentURLResolver; // @synthesize contentURLResolver=_contentURLResolver;
@property(nonatomic) __weak id <EXP_HUBContentOperationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)offlineModeState:(id)arg1 updated:(_Bool)arg2;
- (void)performForViewModelBuilder:(id)arg1 previousError:(id)arg2;
- (void)dealloc;
- (void)dispatchBlockOnMainThread:(CDUnknownBlockType)arg1;
- (void)handleResponse:(id)arg1;
- (void)parseBody:(id)arg1;
- (void)finishAfterPerformingOperation:(_Bool)arg1;
- (id)initWithContentURLResolver:(id)arg1 sourceIdentifier:(id)arg2 resolver:(id)arg3 offlineModeState:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

