//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GLUEStyle.h"

@class NSDictionary, NSString, UIColor, UIFont;

@interface GLUELabelStyle : NSObject <GLUEStyle>
{
    _Bool _upperCase;
    UIFont *_font;
    UIColor *_textColor;
    long long _textAlignment;
    long long _numberOfLines;
    long long _lineBreakMode;
    double _lineHeightMultiple;
    double _kerning;
    long long _verticalAlignment;
    double _lineSpacing;
}

@property(nonatomic) double lineSpacing; // @synthesize lineSpacing=_lineSpacing;
@property(nonatomic) _Bool upperCase; // @synthesize upperCase=_upperCase;
@property(nonatomic) long long verticalAlignment; // @synthesize verticalAlignment=_verticalAlignment;
@property(nonatomic) double kerning; // @synthesize kerning=_kerning;
@property(nonatomic) double lineHeightMultiple; // @synthesize lineHeightMultiple=_lineHeightMultiple;
@property(nonatomic) long long lineBreakMode; // @synthesize lineBreakMode=_lineBreakMode;
@property(nonatomic) long long numberOfLines; // @synthesize numberOfLines=_numberOfLines;
@property(nonatomic) long long textAlignment; // @synthesize textAlignment=_textAlignment;
@property(copy, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(copy, nonatomic) UIFont *font; // @synthesize font=_font;
- (void).cxx_destruct;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToLabelStyle:(id)arg1;
@property(nonatomic) double lineHeightPoints;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithFont:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *attributedStringAttributes;
- (id)attributedStringFromText:(id)arg1;
- (id)paragraphStyle;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

