//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSCBasePacket.h"

@interface MSCPacketAudioTypeCommand : MSCBasePacket
{
    unsigned char _audioType;
    unsigned char _command;
    unsigned short _duration;
    unsigned int _requestID;
}

@property unsigned short duration; // @synthesize duration=_duration;
@property unsigned char command; // @synthesize command=_command;
@property unsigned char audioType; // @synthesize audioType=_audioType;
@property unsigned int requestID; // @synthesize requestID=_requestID;

@end

