//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RAPIGroupPart : NSObject
{
    long long _groupIndex;
    long long _itemOffset;
    long long _itemCount;
}

@property long long itemCount; // @synthesize itemCount=_itemCount;
@property long long itemOffset; // @synthesize itemOffset=_itemOffset;
@property long long groupIndex; // @synthesize groupIndex=_groupIndex;

@end

