//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTSettingsTableViewCell.h"

@class SPTSliderWithLabel, UILabel;

@interface SettingsSliderTableViewCell : SPTSettingsTableViewCell
{
    SPTSliderWithLabel *_slider;
    UILabel *_leftLabel;
    UILabel *_rightLabel;
}

@property(readonly, nonatomic) UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;
@property(readonly, nonatomic) UILabel *leftLabel; // @synthesize leftLabel=_leftLabel;
@property(readonly, nonatomic) SPTSliderWithLabel *slider; // @synthesize slider=_slider;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)applyThemeLayout;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 animationView:(id)arg3;

@end

