//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTAdRegistryObserver.h"

@class NSString, SPTAdFeatureFlagChecks, SPTAdRegistry, UILocalNotification;

@interface SPTAdLocalNotificationManager : NSObject <SPTAdRegistryObserver>
{
    SPTAdRegistry *_registry;
    SPTAdFeatureFlagChecks *_featureChecker;
    id <SPTAdsManager> _manager;
    id <SPTAdEventLogger> _logger;
    UILocalNotification *_activeNotification;
    long long _screenLockState;
}

@property(nonatomic) long long screenLockState; // @synthesize screenLockState=_screenLockState;
@property(retain, nonatomic) UILocalNotification *activeNotification; // @synthesize activeNotification=_activeNotification;
@property(readonly, nonatomic) id <SPTAdEventLogger> logger; // @synthesize logger=_logger;
@property(readonly, nonatomic) id <SPTAdsManager> manager; // @synthesize manager=_manager;
@property(readonly, nonatomic) SPTAdFeatureFlagChecks *featureChecker; // @synthesize featureChecker=_featureChecker;
@property(readonly, nonatomic) SPTAdRegistry *registry; // @synthesize registry=_registry;
- (void).cxx_destruct;
- (void)logEvent:(id)arg1 adID:(id)arg2;
- (void)cancelLocalNotification;
- (void)createLocalNotificationWithEntity:(id)arg1;
- (_Bool)canPresentNotification;
- (void)adRegistry:(id)arg1 didProcessAdEntity:(id)arg2 event:(long long)arg3;
- (void)applicationDidReceiveLocalNotification:(id)arg1;
- (void)deviceDidUnlock:(id)arg1;
- (void)deviceWillLock:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)removeNotificationObservers;
- (void)addNotificationObservers;
- (void)dealloc;
- (id)initWithRegistry:(id)arg1 featureChecker:(id)arg2 manager:(id)arg3 logger:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

