//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, SPTAdCosmosBridge, SPTObserverManager;

@interface SPTAdRegistry : NSObject
{
    SPTAdCosmosBridge *_cosmosBridge;
    NSMutableArray *_entities;
    SPTObserverManager *_observerManager;
}

@property(readonly, nonatomic) SPTObserverManager *observerManager; // @synthesize observerManager=_observerManager;
@property(retain, nonatomic) NSMutableArray *entities; // @synthesize entities=_entities;
@property(readonly, nonatomic) SPTAdCosmosBridge *cosmosBridge; // @synthesize cosmosBridge=_cosmosBridge;
- (void).cxx_destruct;
- (long long)adEventFromString:(id)arg1;
- (id)adEntityFromMetadata:(id)arg1 format:(id)arg2 slot:(id)arg3;
- (void)notifyObserversOfAdEntity:(id)arg1 event:(long long)arg2;
- (void)processMetadata:(id)arg1;
- (void)subscribeToEvents;
- (void)subscribeToFormats;
- (id)adEntityWithIdentifier:(id)arg1;
- (void)discardAd:(id)arg1;
- (_Bool)prerollAvailable;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *availableEntities;
- (id)initWithCosmosBridge:(id)arg1;

@end

