//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SPTCastDebugMenuHelper;

@interface SPTCastReceiverAppIDManager : NSObject
{
    id <SPTLocalSettings> _localSettings;
    SPTCastDebugMenuHelper *_debugMenuHelper;
}

@property(retain, nonatomic) SPTCastDebugMenuHelper *debugMenuHelper; // @synthesize debugMenuHelper=_debugMenuHelper;
@property(retain, nonatomic) id <SPTLocalSettings> localSettings; // @synthesize localSettings=_localSettings;
- (void).cxx_destruct;
- (_Bool)receiverIsJS:(id)arg1;
- (id)receiverJSAppIDs;
- (void)updateCustomReceiverAppID:(id)arg1;
- (id)defaultAppID;
- (id)receiverAppType;
- (id)currentReceiverAppID;
- (id)initWithLocalSettings:(id)arg1 debugMenuHelper:(id)arg2;

@end

