//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTCollectionPlatformDataLoaderFieldsImplementation.h"

#import "SPTCollectionPlatformFieldName.h"
#import "SPTCollectionPlatformFieldURL.h"

@class NSString, NSURL;

@interface SPTCollectionPlatformAlbumMetadataFieldsArtistsImplementation : SPTCollectionPlatformDataLoaderFieldsImplementation <SPTCollectionPlatformFieldName, SPTCollectionPlatformFieldURL>
{
}


// Remaining properties
@property(readonly, nonatomic) NSURL *URL;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSString *name;
@property(readonly) Class superclass;
@end

