//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPTCeramicQualifier : NSObject
{
}

+ (id)performQualificationForObject:(id)arg1 successBlock:(CDUnknownBlockType)arg2 requiredProtocol:(id)arg3 qualificationBlock:(CDUnknownBlockType)arg4;
+ (id)ifCollectionViewCellHasMetaDataPrefixView:(id)arg1 runBlock:(CDUnknownBlockType)arg2;
+ (id)ifItemHasMetaData:(id)arg1 runBlock:(CDUnknownBlockType)arg2;
+ (id)ifItemHasImageDecoration:(id)arg1 runBlock:(CDUnknownBlockType)arg2;
+ (id)ifItemHasImageStyle:(id)arg1 runBlock:(CDUnknownBlockType)arg2;
+ (id)ifItemIsTrack:(id)arg1 runBlock:(CDUnknownBlockType)arg2;
+ (id)ifItemHasMetaDataTitle:(id)arg1 runBlock:(CDUnknownBlockType)arg2;
+ (id)ifItemHasDescription:(id)arg1 runBlock:(CDUnknownBlockType)arg2;
+ (id)ifItemHasIcon:(id)arg1 runBlock:(CDUnknownBlockType)arg2;
+ (id)ifSpaceHasRequestId:(id)arg1 runBlock:(CDUnknownBlockType)arg2;

@end

