//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSURL, SPTInfoView;

@interface SPTCollectionFilterTableFooterView : UIView
{
    SPTInfoView *_infoView;
    NSURL *_pageURI;
    id <SPTCollectionLogger> _logger;
}

+ (double)collectionFilterTableFooterViewPreferredHeight;
@property(retain, nonatomic) id <SPTCollectionLogger> logger; // @synthesize logger=_logger;
@property(retain, nonatomic) NSURL *pageURI; // @synthesize pageURI=_pageURI;
@property(retain, nonatomic) SPTInfoView *infoView; // @synthesize infoView=_infoView;
- (void).cxx_destruct;
- (void)logFilterResetButton;
- (id)initWithWidth:(double)arg1 target:(id)arg2 selector:(SEL)arg3 pageURI:(id)arg4 collectionLogger:(id)arg5;

@end

