//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SPTDrivingState;

@protocol SPTDrivingStateObserver <NSObject>
- (void)drivingStateDetector:(id <SPTDrivingStateDetector>)arg1 drivingStateDidChange:(SPTDrivingState *)arg2;
@end

