//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SettingsSection.h"

@class SPTDataSaverLogger, SettingsSwitchTableViewCell;

@interface SPTDataSaverSettingsSection : SettingsSection
{
    id <SPTPreferences> _preferences;
    id <SPTLocalSettings> _localSettings;
    SettingsSwitchTableViewCell *_dataSaverCell;
    SPTDataSaverLogger *_logger;
}

@property(readonly, nonatomic) SPTDataSaverLogger *logger; // @synthesize logger=_logger;
@property(retain, nonatomic) SettingsSwitchTableViewCell *dataSaverCell; // @synthesize dataSaverCell=_dataSaverCell;
@property(retain, nonatomic) id <SPTLocalSettings> localSettings; // @synthesize localSettings=_localSettings;
@property(retain, nonatomic) id <SPTPreferences> preferences; // @synthesize preferences=_preferences;
- (void).cxx_destruct;
- (void)updateDataSaverCellTitleWithActivatedState:(_Bool)arg1;
- (id)footerText;
- (id)cellForRow:(long long)arg1;
- (long long)numberOfRows;
- (void)dataSaverSwitchChanged:(id)arg1;
- (void)dealloc;
- (id)initWithSettingsViewController:(id)arg1 preferences:(id)arg2 localSettings:(id)arg3 logger:(id)arg4;

@end

