//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTFreeTierCollectionEntityModelDelegate.h"
#import "SPTFreeTierCollectionEntityViewModel.h"

@class NSString, SPTFreeTierCollectionLogger;

@interface SPTFreeTierCollectionEntityViewModelImplementation : NSObject <SPTFreeTierCollectionEntityViewModel, SPTFreeTierCollectionEntityModelDelegate>
{
    _Bool _compactMode;
    _Bool _buttonSectionEnabled;
    id <SPTFreeTierCollectionEntityViewModelDelegate> _delegate;
    NSString *_title;
    id <SPTFreeTierCollectionEntityModel> _model;
    id <SPTLinkDispatcher> _linkDispatcher;
    SPTFreeTierCollectionLogger *_logger;
    id <SPTFreeTierCollectionTestManager> _testManager;
}

@property(retain, nonatomic) id <SPTFreeTierCollectionTestManager> testManager; // @synthesize testManager=_testManager;
@property(retain, nonatomic) SPTFreeTierCollectionLogger *logger; // @synthesize logger=_logger;
@property(nonatomic, getter=isButtonSectionEnabled) _Bool buttonSectionEnabled; // @synthesize buttonSectionEnabled=_buttonSectionEnabled;
@property(retain, nonatomic) id <SPTLinkDispatcher> linkDispatcher; // @synthesize linkDispatcher=_linkDispatcher;
@property(retain, nonatomic) id <SPTFreeTierCollectionEntityModel> model; // @synthesize model=_model;
@property(readonly, nonatomic, getter=isCompactMode) _Bool compactMode; // @synthesize compactMode=_compactMode;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) __weak id <SPTFreeTierCollectionEntityViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)entityModelDidUpdate:(id)arg1;
- (void)entityModel:(id)arg1 error:(id)arg2;
- (_Bool)showSeparatorForSection:(long long)arg1;
- (long long)numberOfRowsInSections:(long long)arg1;
- (void)itemSelectedAtIndexPath:(id)arg1;
- (id)itemAtIndexPath:(id)arg1;
- (void)loadViewModel;
@property(readonly, nonatomic, getter=isEmpty) _Bool empty;
@property(readonly, nonatomic, getter=isLoaded) _Bool loaded;
- (id)initWithTitle:(id)arg1 model:(id)arg2 linkDispatcher:(id)arg3 buttonSectionEnabled:(_Bool)arg4 logger:(id)arg5 testManager:(id)arg6 compactMode:(_Bool)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

