//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@protocol SPTFreeTierPlaylistModelEntity <NSObject>
@property(readonly, nonatomic) unsigned long long onDemandType;
@property(readonly, nonatomic) NSArray *recommendations;
@property(readonly, nonatomic) unsigned long long unrangedTracksLength;
@property(readonly, nonatomic) NSArray *tracks;
@property(readonly, nonatomic) id <SPTFreeTierPlaylistModelEntityMetadataFields> metadata;
@end

