//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@protocol SPTFollowFeatureLogger <NSObject>
+ (id)new;
- (id)init;
- (void)logFollowIntent:(unsigned long long)arg1 feature:(NSString *)arg2 pageURI:(NSURL *)arg3 targetURI:(NSURL *)arg4;
@end

