//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "GLUEReusable.h"
#import "GLUEStatefulItem.h"
#import "GLUEStyleable.h"
#import "SPTCellImageLoadingContextCompatibleCell.h"

@class GLUEImageView, GLUELabel, GLUEStatefulStyle, NSLayoutConstraint, NSString, SPTLayoutConstraintBuilder, SPTOfflineSyncStatusView, SPTTrackAccessoryLabel, UIButton, UICollectionView, UIView;

@interface SPTFriendsHomeEntityViewCell : UICollectionViewCell <GLUEStatefulItem, GLUEStyleable, GLUEReusable, SPTCellImageLoadingContextCompatibleCell>
{
    _Bool _didSetupConstraints;
    GLUEImageView *_imageView;
    GLUELabel *_textLabel;
    GLUELabel *_detailTextLabel;
    UIView *_accessoryView;
    SPTTrackAccessoryLabel *_trackAccessoryLabel;
    UIView *_animationContentView;
    long long _offlineSyncStatus;
    SPTOfflineSyncStatusView *_offlineSyncStatusView;
    UICollectionView *_facepileView;
    id <SPTFriendsHomeEntityViewCellDelegate> _delegate;
    GLUEStatefulStyle *_style;
    unsigned long long _state;
    NSLayoutConstraint *_textLabelRightEdgeConstraint;
    NSLayoutConstraint *_detailTextLabelLeftEdgeConstraint;
    NSLayoutConstraint *_detailTextLabelRightEdgeConstraint;
    SPTLayoutConstraintBuilder *_accessoryViewLayout;
    UIButton *_facepileTouch;
}

@property(retain, nonatomic) UIButton *facepileTouch; // @synthesize facepileTouch=_facepileTouch;
@property(retain, nonatomic) SPTLayoutConstraintBuilder *accessoryViewLayout; // @synthesize accessoryViewLayout=_accessoryViewLayout;
@property(retain, nonatomic) NSLayoutConstraint *detailTextLabelRightEdgeConstraint; // @synthesize detailTextLabelRightEdgeConstraint=_detailTextLabelRightEdgeConstraint;
@property(retain, nonatomic) NSLayoutConstraint *detailTextLabelLeftEdgeConstraint; // @synthesize detailTextLabelLeftEdgeConstraint=_detailTextLabelLeftEdgeConstraint;
@property(retain, nonatomic) NSLayoutConstraint *textLabelRightEdgeConstraint; // @synthesize textLabelRightEdgeConstraint=_textLabelRightEdgeConstraint;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(copy, nonatomic) GLUEStatefulStyle *style; // @synthesize style=_style;
@property(nonatomic) __weak id <SPTFriendsHomeEntityViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UICollectionView *facepileView; // @synthesize facepileView=_facepileView;
@property(readonly, nonatomic) SPTOfflineSyncStatusView *offlineSyncStatusView; // @synthesize offlineSyncStatusView=_offlineSyncStatusView;
@property(nonatomic) long long offlineSyncStatus; // @synthesize offlineSyncStatus=_offlineSyncStatus;
@property(readonly, nonatomic) UIView *animationContentView; // @synthesize animationContentView=_animationContentView;
@property(retain, nonatomic) SPTTrackAccessoryLabel *trackAccessoryLabel; // @synthesize trackAccessoryLabel=_trackAccessoryLabel;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(readonly, nonatomic) GLUELabel *detailTextLabel; // @synthesize detailTextLabel=_detailTextLabel;
@property(readonly, nonatomic) GLUELabel *textLabel; // @synthesize textLabel=_textLabel;
@property(readonly, nonatomic) GLUEImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)didTapFacepile;
- (void)updateStateStyle;
- (void)setImage:(id)arg1 animated:(_Bool)arg2;
- (void)setImage:(id)arg1;
@property(nonatomic, getter=isActive) _Bool active;
@property(nonatomic, getter=isHighlighted) _Bool highlighted;
@property(nonatomic, getter=isSelected) _Bool selected;
@property(nonatomic, getter=isDisabled) _Bool disabled;
- (void)glue_applyStateStyle:(id)arg1;
- (void)glue_applyStyle:(id)arg1;
- (void)updateAccessoryViewConstraints;
- (void)updateLabelRightEdgeConstraints;
- (void)updateConstraints;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

