//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTFreeTierTasteOnboardingTrackSwipeAnimating.h"

@class SPTFreeTierTasteOnboardingTrackSwipeAnimator;

@protocol SPTFreeTierTasteOnboardingTrackSwipeAnimatorDelegate <SPTFreeTierTasteOnboardingTrackSwipeAnimating>
- (void)trackSwipeAnimator:(SPTFreeTierTasteOnboardingTrackSwipeAnimator *)arg1 dismissedInDirection:(unsigned long long)arg2 withTransform:(struct CATransform3D)arg3;
@end

