//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GLUECardDetailsView.h"

@class SPTLayoutConstraintBuilder, UIButton, UICollectionView;

@interface SPTFriendsHomeGLUECardAvatarDetailsView : GLUECardDetailsView
{
    _Bool _emptySubtitle;
    UICollectionView *_avatarCollectionView;
    UIButton *_avatarTouch;
    SPTLayoutConstraintBuilder *_avatarLayout;
}

@property(nonatomic) _Bool emptySubtitle; // @synthesize emptySubtitle=_emptySubtitle;
@property(retain, nonatomic) SPTLayoutConstraintBuilder *avatarLayout; // @synthesize avatarLayout=_avatarLayout;
@property(retain, nonatomic) UIButton *avatarTouch; // @synthesize avatarTouch=_avatarTouch;
@property(retain, nonatomic) UICollectionView *avatarCollectionView; // @synthesize avatarCollectionView=_avatarCollectionView;
- (void).cxx_destruct;
- (void)addAvatarTouchTarget:(id)arg1;
- (void)setCollectionViewDataSource:(id)arg1 delegate:(id)arg2 emptySubtitle:(_Bool)arg3;
- (void)layoutSubviews;
- (void)addCollectionViewConstraints;
- (void)updateConstraints;
- (void)setupCollectionView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

