//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTContextMenuViewDataSource.h"
#import "SPTGaiaContextMenuActionDelegate.h"

@class NSArray, NSString, SPTGaiaDevice, SPTGaiaDeviceAppearanceMapping;

@interface SPTGaiaContextMenuModel : NSObject <SPTGaiaContextMenuActionDelegate, SPTContextMenuViewDataSource>
{
    id <SPTGaiaContextMenuModelDelegate> _delegate;
    SPTGaiaDevice *_device;
    id <SPTGaiaDevicePickerContextMenuFlagsProvider><SPTGaiaHomeDeviceFlagsProvider> _flagsProvider;
    NSArray *_actions;
    NSArray *_filteredActions;
    SPTGaiaDeviceAppearanceMapping *_iconMapper;
    id <SPTImageLoaderFactory> _imageLoaderFactory;
}

@property(retain, nonatomic) id <SPTImageLoaderFactory> imageLoaderFactory; // @synthesize imageLoaderFactory=_imageLoaderFactory;
@property(readonly, nonatomic) SPTGaiaDeviceAppearanceMapping *iconMapper; // @synthesize iconMapper=_iconMapper;
@property(retain, nonatomic) NSArray *filteredActions; // @synthesize filteredActions=_filteredActions;
@property(retain, nonatomic) NSArray *actions; // @synthesize actions=_actions;
@property(retain, nonatomic) id <SPTGaiaDevicePickerContextMenuFlagsProvider><SPTGaiaHomeDeviceFlagsProvider> flagsProvider; // @synthesize flagsProvider=_flagsProvider;
@property(readonly, nonatomic) SPTGaiaDevice *device; // @synthesize device=_device;
@property(nonatomic) __weak id <SPTGaiaContextMenuModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)enabledActionsInArray:(id)arg1;
- (void)action:(id)arg1 isPerformedWithEventVersion:(id)arg2 logData:(id)arg3;
- (void)action:(id)arg1 wantsToPresentViewController:(id)arg2;
- (id)contextMenuView:(id)arg1 actionForIndexPath:(id)arg2;
- (unsigned long long)numberOfSectionsInContextMenuView:(id)arg1;
- (unsigned long long)contextMenuView:(id)arg1 numberOfActionsInSection:(unsigned long long)arg2;
- (id)contextMenuView:(id)arg1 actionForRow:(unsigned long long)arg2;
- (unsigned long long)numberOfActionsInContextMenuView:(id)arg1;
- (unsigned long long)numberOfSections;
- (unsigned long long)numberOfActionsInSection:(unsigned long long)arg1;
@property(readonly, nonatomic) _Bool contextMenuAvailable;
@property(readonly, nonatomic) NSArray *enabledActionIdentifiers;
@property(readonly, nonatomic) long long icon;
@property(readonly, copy, nonatomic) NSString *title;
- (id)initWithDevice:(id)arg1 actions:(id)arg2 flagsProvider:(id)arg3 iconMapper:(id)arg4 imageLoaderFactory:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

