//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, SPTIAPPurchaseRequest;

@protocol SPTIAPPurchaseRequestDelegate <NSObject>
- (void)purchaseRequest:(SPTIAPPurchaseRequest *)arg1 givingUpOnTransactionWithError:(NSError *)arg2;
- (void)purchaseRequest:(SPTIAPPurchaseRequest *)arg1 didFailWithError:(NSError *)arg2;
- (void)purchaseRequestDidFinish:(SPTIAPPurchaseRequest *)arg1;
- (void)purchaseRequestDidStartActivation:(SPTIAPPurchaseRequest *)arg1;
- (void)purchaseRequestDidResumeTransaction:(SPTIAPPurchaseRequest *)arg1;
- (void)purchaseRequestDidStartTransaction:(SPTIAPPurchaseRequest *)arg1;
@end

