//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@protocol SPTLocalFilesImportModelItem <NSObject>
@property(readonly, nonatomic) _Bool isPartiallySelected;
@property(readonly, nonatomic) _Bool isSelected;
@property(readonly, nonatomic) NSURL *imageURL;
@property(readonly, nonatomic) NSString *title;
@end

