//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTLogMessage.h"

@class NSString;

@interface SPTLogMessageInAppPurchase2 : SPTLogMessage
{
    NSString *_domainValue;
    NSString *_eventValue;
    NSString *_jsonDataValue;
    NSString *_contextValue;
}

+ (id)messageWithDomain:(id)arg1 event:(id)arg2 jsonData:(id)arg3 context:(id)arg4;
@property(retain, nonatomic) NSString *contextValue; // @synthesize contextValue=_contextValue;
@property(retain, nonatomic) NSString *jsonDataValue; // @synthesize jsonDataValue=_jsonDataValue;
@property(retain, nonatomic) NSString *eventValue; // @synthesize eventValue=_eventValue;
@property(retain, nonatomic) NSString *domainValue; // @synthesize domainValue=_domainValue;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)serialize;

@end

