//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTLogMessage.h"

@class NSArray, NSString;

@interface SPTLogMessageShare5 : SPTLogMessage
{
    _Bool _textChangedValue;
    NSString *_sessionIdValue;
    NSString *_userIntentValue;
    NSString *_interactionTypeValue;
    NSString *_resultValue;
    NSString *_uriValue;
    NSString *_contextUriValue;
    NSString *_sourcePageIdValue;
    NSString *_destinationIdValue;
    long long _destinationIndexValue;
    NSArray *_testGroupsValue;
    NSString *_shareIdValue;
    NSString *_typeValue;
    NSString *_currentlyPlayingValue;
}

+ (id)messageWithSessionId:(id)arg1 userIntent:(id)arg2 interactionType:(id)arg3 result:(id)arg4 uri:(id)arg5 contextUri:(id)arg6 textChanged:(_Bool)arg7 sourcePageId:(id)arg8 destinationId:(id)arg9 destinationIndex:(long long)arg10 testGroups:(id)arg11 shareId:(id)arg12 type:(id)arg13 currentlyPlaying:(id)arg14;
@property(retain, nonatomic) NSString *currentlyPlayingValue; // @synthesize currentlyPlayingValue=_currentlyPlayingValue;
@property(retain, nonatomic) NSString *typeValue; // @synthesize typeValue=_typeValue;
@property(retain, nonatomic) NSString *shareIdValue; // @synthesize shareIdValue=_shareIdValue;
@property(retain, nonatomic) NSArray *testGroupsValue; // @synthesize testGroupsValue=_testGroupsValue;
@property(nonatomic) long long destinationIndexValue; // @synthesize destinationIndexValue=_destinationIndexValue;
@property(retain, nonatomic) NSString *destinationIdValue; // @synthesize destinationIdValue=_destinationIdValue;
@property(retain, nonatomic) NSString *sourcePageIdValue; // @synthesize sourcePageIdValue=_sourcePageIdValue;
@property(nonatomic) _Bool textChangedValue; // @synthesize textChangedValue=_textChangedValue;
@property(retain, nonatomic) NSString *contextUriValue; // @synthesize contextUriValue=_contextUriValue;
@property(retain, nonatomic) NSString *uriValue; // @synthesize uriValue=_uriValue;
@property(retain, nonatomic) NSString *resultValue; // @synthesize resultValue=_resultValue;
@property(retain, nonatomic) NSString *interactionTypeValue; // @synthesize interactionTypeValue=_interactionTypeValue;
@property(retain, nonatomic) NSString *userIntentValue; // @synthesize userIntentValue=_userIntentValue;
@property(retain, nonatomic) NSString *sessionIdValue; // @synthesize sessionIdValue=_sessionIdValue;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)serialize;

@end

