//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIButton, UILabel;

@protocol SPTNowPlayingInformationView <NSObject>
@property(readonly, copy, nonatomic) NSString *artistName;
@property(readonly, copy, nonatomic) NSString *trackTitle;
@property(readonly, nonatomic) UIButton *labelButton;
@property(readonly, nonatomic) UILabel *rightAccessoryIndicator;
@property(readonly, nonatomic) UILabel *leftAccessoryIndicator;
@property(retain, nonatomic) UIButton *rightAccessoryButton;
@property(retain, nonatomic) UIButton *leftAccessoryButton;
- (void)resetLayout;
@end

