//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIButton, UILabel;

@protocol SPTNowPlayingHeadUnitView <NSObject>
@property(readonly, nonatomic) UILabel *rightAccessoryIndicator;
@property(readonly, nonatomic) UILabel *leftAccessoryIndicator;
@property(readonly, nonatomic) UIButton *rightAccessoryButton;
@property(readonly, nonatomic) UIButton *leftAccessoryButton;
@end

