//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTOnDemandService.h"

@class NSString, SPTAllocationContext, SPTOnDemandSetImplementation, SPTPersistentCache;

@interface SPTOnDemandServiceImplementation : NSObject <SPTOnDemandService>
{
    id <SPTFeatureFlaggingService> _featureFlaggingService;
    SPTOnDemandSetImplementation *_onDemandSet;
    SPTPersistentCache *_persistentCache;
}

+ (id)serviceIdentifier;
@property(retain, nonatomic) SPTPersistentCache *persistentCache; // @synthesize persistentCache=_persistentCache;
@property(retain, nonatomic) SPTOnDemandSetImplementation *onDemandSet; // @synthesize onDemandSet=_onDemandSet;
@property(nonatomic) __weak id <SPTFeatureFlaggingService> featureFlaggingService; // @synthesize featureFlaggingService=_featureFlaggingService;
- (void).cxx_destruct;
- (id)provideOnDemandCeramicViewDecorator;
- (id)provideOnDemandCardAccessibilityContentOperation;
- (id)provideOnDemandReloadContentOperation;
- (id)provideOnDemandDecoratorContentOperation;
- (id)provideOnDemandExtractorContentOperation;
- (id)provideOnDemandSet;
- (void)load;
- (void)configureWithServices:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

