//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTService.h"

@class NSString, SPTAllocationContext;

@interface SPTPlaylistPlatformServiceImplementation : NSObject <SPTService>
{
    id <CosmosFeature> _cosmosFeature;
    id <SPTCosmosDataLoaderService> _cosmosDataLoaderService;
    id <SPTResolver> _playlistCosmosRouter;
    id <SPTPlaylistPlatformPlaylistSynchroniser> _playlistSynchroniser;
}

+ (id)serviceIdentifier;
@property(retain, nonatomic) id <SPTPlaylistPlatformPlaylistSynchroniser> playlistSynchroniser; // @synthesize playlistSynchroniser=_playlistSynchroniser;
@property(retain, nonatomic) id <SPTResolver> playlistCosmosRouter; // @synthesize playlistCosmosRouter=_playlistCosmosRouter;
@property(retain, nonatomic) id <SPTCosmosDataLoaderService> cosmosDataLoaderService; // @synthesize cosmosDataLoaderService=_cosmosDataLoaderService;
@property(retain, nonatomic) id <CosmosFeature> cosmosFeature; // @synthesize cosmosFeature=_cosmosFeature;
- (void).cxx_destruct;
- (id)provideResolverPlaylist;
- (id)providePlaylistURIResolver;
- (id)providePlaylistSynchroniser;
- (id)providePlaylistPlatformDataLoader;
- (id)providePlaylistModel;
- (void)configureWithServices:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

