//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, NSURL;

@interface SPTPlayerContextPage : NSObject <NSCopying>
{
    NSURL *_pageURL;
    NSURL *_nextPageURL;
    NSArray *_tracks;
}

@property(copy, nonatomic) NSArray *tracks; // @synthesize tracks=_tracks;
@property(copy, nonatomic) NSURL *nextPageURL; // @synthesize nextPageURL=_nextPageURL;
@property(copy, nonatomic) NSURL *pageURL; // @synthesize pageURL=_pageURL;
- (void).cxx_destruct;
- (id)init;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)serializedDictionary;
- (id)initWithDictionary:(id)arg1;

@end

