//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPTShowInfoViewProvider : NSObject
{
    id <SPTShowInfoViewStringProvider> _stringProvider;
}

@property(retain, nonatomic) id <SPTShowInfoViewStringProvider> stringProvider; // @synthesize stringProvider=_stringProvider;
- (void).cxx_destruct;
- (void)navigateToVideoHub;
- (void)navigateToShowsHub;
- (id)createLinkButtonWithViewURI:(id)arg1 browseButtonTitle:(id)arg2 mediaType:(unsigned long long)arg3;
- (void)setupEmptyCollectionInfoView:(id)arg1 title:(id)arg2 text:(id)arg3 icon:(long long)arg4 browseButtonTitle:(id)arg5 emptyViewURI:(id)arg6 mediaType:(unsigned long long)arg7;
- (void)setupEmptyCollectionInfoView:(id)arg1 title:(id)arg2 text:(id)arg3 icon:(long long)arg4;
- (id)showInfoViewForEmptyViewURI:(id)arg1 standAlonePage:(_Bool)arg2 size:(struct CGSize)arg3;
- (id)showInfoViewForEmptyViewURI:(id)arg1 size:(struct CGSize)arg2;
- (id)showInfoViewForEmptyViewURI:(id)arg1 mediaType:(unsigned long long)arg2 size:(struct CGSize)arg3;
- (id)initWithStringProvider:(id)arg1;

@end

