//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDictionary, NSError, NSString, UILocalNotification;

@protocol SPTThirdPartyNotificationsTracker <NSObject>
- (void)setPushNotificationsDeviceToken:(NSData *)arg1;

@optional
- (void)handleActionWithIdentifier:(NSString *)arg1 forLocalNotification:(UILocalNotification *)arg2 completionHandler:(void (^)(void))arg3;
- (void)handleActionWithIdentifier:(NSString *)arg1 forRemoteNotification:(NSDictionary *)arg2 completionHandler:(void (^)(void))arg3;
- (void)handleIncomingLocalNotification:(NSDictionary *)arg1;
- (void)handleIncomingRemoteNotification:(NSDictionary *)arg1;
- (void)didFailToRegisterForRemoteNotificationsWithError:(NSError *)arg1;
@end

