//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SPTTasteCollectionFinishViewController;

@protocol SPTTasteCollectionFinishViewControllerDelegate <NSObject>
- (void)tasteCollectionFinishViewController:(SPTTasteCollectionFinishViewController *)arg1 succeededToSendAnswers:(_Bool)arg2;
@end

