//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FCDInterceptor.h"

@class FCDBoqDataParams, NSObject<OS_dispatch_queue>, NSString;

@interface FCDBoqDataInterceptor : NSObject <FCDInterceptor>
{
    NSObject<OS_dispatch_queue> *_interceptorQueue;
    FCDBoqDataParams *_params;
}

+ (id)stage;
@property(retain, nonatomic) FCDBoqDataParams *params; // @synthesize params=_params;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *interceptorQueue; // @synthesize interceptorQueue=_interceptorQueue;
- (void).cxx_destruct;
- (void)rpcRequestWillStart:(id)arg1 context:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)initWithBoqDataParams:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

