//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MDXBasePlayerOverlayView.h"

@class UIButton, YTLabel, YTPlayerBarView;

@interface MDXPlayerOverlayView : MDXBasePlayerOverlayView
{
    YTLabel *_autoplayNoticeLabel;
    UIButton *_replayButton;
    UIButton *_dismissAutoplayButton;
    UIButton *_previousButton;
    UIButton *_nextButton;
    YTPlayerBarView *_playerBarView;
}

+ (id)newButtonWithImage:(id)arg1 accessibilityId:(id)arg2 accessibilityLabel:(id)arg3;
- (void).cxx_destruct;
- (void)showPlayerControlsOrAutoplayDismissButton:(_Bool)arg1;
- (void)showVideoTitleOrAutoplayNotice:(_Bool)arg1;
- (void)didTapPlayNext;
- (void)didTapPlayPrevious;
- (void)didTapReplay;
- (void)didTapVideoTitle;
- (void)setMediaTime:(double)arg1;
- (void)setTotalTime:(double)arg1;
- (void)setMode:(int)arg1;
- (void)setTitle:(id)arg1;
- (void)setPlayerBarViewEnabled:(_Bool)arg1;
- (void)setPlayerBarViewDelegate:(id)arg1;
- (void)setNowAutoplaying:(_Bool)arg1;
- (void)setPlaybackInSyncWithLivePlayhead:(_Bool)arg1;
- (void)setMinimumSeekableTime:(double)arg1 maximumSeekableTime:(double)arg2;
- (void)setPreviousButtonVisible:(_Bool)arg1;
- (void)setNextButtonVisible:(_Bool)arg1;
- (void)showReplayButton;
- (void)showPauseButton;
- (void)showPlayButton;
- (void)setupPlayerBarView;
- (void)setupMainControlsViewGroup;
- (void)setupPlayerControlsContainerView;
- (void)layoutSubviews;
- (id)initWithParentResponder:(id)arg1;

// Remaining properties
@property(nonatomic) __weak id <MDXPlayerOverlayViewDelegate> delegate; // @dynamic delegate;

@end

