//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YTCowatchSessionChangeSet : NSObject
{
    _Bool _currentQueueItemChanged;
    _Bool _videoPlaybackModeChanged;
    _Bool _cowatchMembersChanged;
    _Bool _cowatchQueueDidChange;
    _Bool _videoPlaybackAlreadyPlaying;
}

@property(readonly, nonatomic) _Bool videoPlaybackAlreadyPlaying; // @synthesize videoPlaybackAlreadyPlaying=_videoPlaybackAlreadyPlaying;
@property(readonly, nonatomic) _Bool cowatchQueueDidChange; // @synthesize cowatchQueueDidChange=_cowatchQueueDidChange;
@property(readonly, nonatomic) _Bool cowatchMembersChanged; // @synthesize cowatchMembersChanged=_cowatchMembersChanged;
@property(readonly, nonatomic) _Bool videoPlaybackModeChanged; // @synthesize videoPlaybackModeChanged=_videoPlaybackModeChanged;
@property(readonly, nonatomic) _Bool currentQueueItemChanged; // @synthesize currentQueueItemChanged=_currentQueueItemChanged;
- (_Bool)didCowatchQueueChangeFromPreviousSession:(id)arg1 toUpdatedSession:(id)arg2;
- (_Bool)didCowatchMembersChangeFromPreviousSession:(id)arg1 toUpdatedSession:(id)arg2;
- (id)initWithPreviousSession:(id)arg1 updatedSession:(id)arg2;

@end

