//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "YTFullscreenVideoViewControllerPresenter.h"
#import "YTResponder.h"

@class NSString;

@interface YTCowatchPlayerContainerViewController : UIViewController <YTResponder, YTFullscreenVideoViewControllerPresenter>
{
    id <YTResponder> _parentResponder;
    id <YTCowatchPlayerContainerViewControllerDelegete> _delegate;
}

@property(nonatomic) __weak id <YTCowatchPlayerContainerViewControllerDelegete> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) __weak id <YTResponder> parentResponder; // @synthesize parentResponder=_parentResponder;
- (void).cxx_destruct;
- (void)fullScreenVideoViewControllerDidDismiss;
- (struct CGRect)frameForDismissedPlayerView;
- (void)loadView;
- (id)initWithParentResponder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

