//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "YTConnectionStatusControllerObserver.h"
#import "YTResponder.h"

@class GIMMe, NSDate, NSMapTable, NSString, YTConnectionStatusController, YTTimedAction;

@interface YTConnectionBarController : NSObject <YTConnectionStatusControllerObserver, YTResponder>
{
    NSMapTable *_observers;
    YTConnectionStatusController *_connectionStatusController;
    NSDate *_dateOfLastShownDisabledAction;
    _Bool _isLoggingDelayed;
    GIMMe *_gimme;
    YTTimedAction *_dismissTimer;
}

@property(retain, nonatomic) YTTimedAction *dismissTimer; // @synthesize dismissTimer=_dismissTimer;
@property(nonatomic) __weak GIMMe *gimme; // @synthesize gimme=_gimme;
- (void).cxx_destruct;
@property(readonly, nonatomic) __weak id <YTResponder> parentResponder;
- (void)logConnectionBarAppearanceChange;
- (void)processDelayedLogsIfNeeded;
- (void)scheduleConnectionBarsDisplayUpdate:(_Bool)arg1 temporarily:(_Bool)arg2;
- (void)setConnectionBarViewDisplayed:(_Bool)arg1 temporarily:(_Bool)arg2;
- (void)updateConnectionBarViewsAppearanceForIsConnected:(_Bool)arg1 animated:(_Bool)arg2;
- (double)connectionBarDisplayHeight;
- (void)updateConnectionBarView:(id)arg1 isTemporary:(_Bool)arg2;
- (void)addConnectionBarView:(id)arg1 withObserver:(id)arg2;
- (void)connectionStatusDidChange:(_Bool)arg1;
- (void)shutdown;
- (void)showOfflineDisabledActionIfNeeded;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

