//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YTMultiSizeViewController.h"

#import "YTAutonavPermittingPresentedViewController.h"

@class MPVolumeView, NSString, UIViewController, YTNGWatchCollectionViewController, YTVolumeBarView;

@interface YTNGWatchFullscreenViewController : YTMultiSizeViewController <YTAutonavPermittingPresentedViewController>
{
    YTVolumeBarView *_volumeBarView;
    MPVolumeView *_hiddenVolumeView;
    _Bool _rotating;
    _Bool _miniBarTransition;
    UIViewController *_fullscreenPresenter;
    YTNGWatchCollectionViewController *_collectionViewController;
}

@property(readonly, nonatomic) __weak YTNGWatchCollectionViewController *collectionViewController; // @synthesize collectionViewController=_collectionViewController;
@property(readonly, nonatomic) __weak UIViewController *fullscreenPresenter; // @synthesize fullscreenPresenter=_fullscreenPresenter;
@property(readonly, nonatomic, getter=isMiniBarTransition) _Bool miniBarTransition; // @synthesize miniBarTransition=_miniBarTransition;
@property(readonly, nonatomic, getter=isRotating) _Bool rotating; // @synthesize rotating=_rotating;
- (void).cxx_destruct;
- (void)moveCollectionViewControllerToParent:(id)arg1;
- (_Bool)isParentOfCollectionViewController;
- (void)didTransitionFromSize:(struct CGSize)arg1 toSize:(struct CGSize)arg2;
- (void)willTransitionFromSize:(struct CGSize)arg1 toSize:(struct CGSize)arg2;
- (_Bool)prefersHomeIndicatorAutoHidden;
- (unsigned long long)preferredScreenEdgesDeferringSystemGestures;
- (_Bool)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)loadView;
- (id)initWithFullscreenPresenter:(id)arg1 collectionViewController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

