//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "YTImageViewLoadingDelegate.h"
#import "YTResponder.h"
#import "YTSystemNotificationsObserver.h"
#import "YTVideoAsThumbnailDetailsViewDelegate.h"

@class AVPlayer, GIMMe, NSString, NSURL, YTIAThumbnailDetails, YTIVideoAsThumbnailDetails, YTPersistentMediaCacheConfig, YTReachabilityController, YTThumbnailController, YTVideoAsThumbnailDetailsView;

@interface YTVideoAsThumbnailDetailsController : NSObject <YTImageViewLoadingDelegate, YTSystemNotificationsObserver, YTVideoAsThumbnailDetailsViewDelegate, YTResponder>
{
    YTPersistentMediaCacheConfig *_cacheConfig;
    YTThumbnailController *_thumbnailController;
    YTIAThumbnailDetails *_currentPlaceholderAsset;
    NSURL *_currentURL;
    id <YTEventLogger> _eventLogger;
    struct CGSize _mediaSize;
    NSString *_mediaKey;
    _Bool _shouldPlayOnPlaceholderLoaded;
    _Bool _thumbnailPlaceholderLoaded;
    _Bool _forcedPaused;
    YTReachabilityController *_reachabilityController;
    double _lastVideoSeekTime;
    id <YTResponder> _parentResponder;
    GIMMe *_gimme;
    YTVideoAsThumbnailDetailsView *_view;
    id <YTVideoAsThumbnailDetailsDelegate> _delegate;
    AVPlayer *_player;
    YTIVideoAsThumbnailDetails *_videoAsThumbnail;
    unsigned long long _state;
}

@property(readonly, nonatomic) unsigned long long state; // @synthesize state=_state;
@property(retain, nonatomic) YTIVideoAsThumbnailDetails *videoAsThumbnail; // @synthesize videoAsThumbnail=_videoAsThumbnail;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(nonatomic) __weak id <YTVideoAsThumbnailDetailsDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) YTVideoAsThumbnailDetailsView *view; // @synthesize view=_view;
@property(nonatomic) __weak GIMMe *gimme; // @synthesize gimme=_gimme;
@property(readonly, nonatomic) __weak id <YTResponder> parentResponder; // @synthesize parentResponder=_parentResponder;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (_Bool)isPlayingState;
- (void)releasePlayerWithLoggingType:(int)arg1;
- (id)placeholderThumbnailDetails;
- (void)logSimplePlaybackEventWithType:(int)arg1;
- (void)playerItemDidReachEnd:(id)arg1;
- (id)urlForViewportSize:(struct CGSize)arg1;
- (void)playWithFileURL:(id)arg1;
- (void)buildPlayerWithViewportSize:(struct CGSize)arg1;
- (id)placeholderAsset;
- (void)viewDidGetSizedWithFrame:(struct CGRect)arg1;
- (void)imageViewDidLoad:(id)arg1;
- (void)appDidReceiveMemoryWarning:(id)arg1;
- (void)appWillEnterForeground:(id)arg1;
- (void)pause;
- (void)resume;
- (void)dealloc;
- (id)initWithVideoThumbnailDetails:(id)arg1 parentResponder:(id)arg2;
- (id)thumbnailRenderer;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

