//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "YCHPlaybackEventsProvider.h"
#import "YTActiveVideoProvider.h"
#import "YTActiveVideoReportingRendererProvider.h"
#import "YTEngagementPanelNavigationControllerEventObserver.h"
#import "YTExternalCompanionShelfResponderProvider.h"
#import "YTOfflineModeObserver.h"
#import "YTOfflineVideoControllerObserver.h"
#import "YTOfflineabilityResponderProvider.h"
#import "YTPlaybackControllerEventsDelegate.h"
#import "YTPlaybackControllerUIDelegate.h"
#import "YTPlaybackDebugDataProvider.h"
#import "YTPlaylistPanelControllerPlaybackDelegate.h"
#import "YTResponder.h"
#import "YTShareObserver.h"
#import "YTSpeedyGResponderProvider.h"
#import "YTWatchBreakControllerDelegate.h"
#import "YTWatchControllerProtocol.h"
#import "YTWatchNextStateResponderProvider.h"
#import "YTYouThereControllerDelegate.h"

@class GIMMe, NSError, NSHashTable, NSMutableDictionary, NSString, SKStoreProductViewController, UIView, YTDelayedWatchNextService, YTICommand, YTIMenuRenderer, YTIShowAppStorePanelCommand, YTISurveyTriggerRenderer, YTIVideoReportingSupportedRenderers, YTIWatchNextResponse, YTInnerTubeControllerFactory, YTPlaybackDebugData, YTPlayerResponse, YTPlayerViewController, YTPlayerWatchNextOrderingController, YTShareEndpointController, YTStickyVarispeedController, YTVideoQualityPromoController, YTWatchNextResultsViewController, YTWatchNextViewController, YTWatchTransition, YTYouThereController;

@interface YTWatchController : NSObject <YCHPlaybackEventsProvider, YTEngagementPanelNavigationControllerEventObserver, YTExternalCompanionShelfResponderProvider, YTOfflineModeObserver, YTOfflineVideoControllerObserver, YTPlaybackControllerUIDelegate, YTShareObserver, YTSpeedyGResponderProvider, YTWatchBreakControllerDelegate, YTYouThereControllerDelegate, YTActiveVideoProvider, YTActiveVideoReportingRendererProvider, YTOfflineabilityResponderProvider, YTPlaybackControllerEventsDelegate, YTPlaybackDebugDataProvider, YTPlaylistPanelControllerPlaybackDelegate, YTResponder, YTWatchControllerProtocol, YTWatchNextStateResponderProvider>
{
    id <YTWatchNextResultsControllerProtocol> _watchNextResultsController;
    YTICommand *_navigationEndpoint;
    int _watchEndpointSource;
    YTPlaybackDebugData *_savedPlaybackDebugData;
    YTPlayerResponse *_savedPlayerResponse;
    _Bool _watchNextResponseLoaded;
    NSHashTable *_offlineabilityObservers;
    NSHashTable *_speedyGObservers;
    NSHashTable *_playbackEventsObservers;
    YTVideoQualityPromoController *_videoQualityPromoController;
    YTIVideoReportingSupportedRenderers *_videoReportingRenderers;
    YTIMenuRenderer *_addToMenuRenderer;
    YTISurveyTriggerRenderer *_surveyRenderer;
    id <YTWatchFlowControllerProtocol> _watchFlowController;
    id <YTAdInnerTubeConfig> _adInnerTubeConfig;
    YTPlayerWatchNextOrderingController *_orderingController;
    YTDelayedWatchNextService *_delayedWatchNextService;
    YTYouThereController *_youThereController;
    YTIWatchNextResponse *_lastInitialWatchNextResponse;
    YTStickyVarispeedController *_stickyVarispeedController;
    id <YTCrashRestoreVideoProtocol> _crashRestoreVideoController;
    id <YTWatchUIStateResponderProvider> _watchUIStateResponderProvider;
    YTWatchTransition *_preparedWatchTransition;
    _Bool _videoWasPausedForShareSheet;
    SKStoreProductViewController *_storeProductViewController;
    YTIShowAppStorePanelCommand *_showAppStorePanelCommand;
    _Bool _shouldTriggerTerminationCommandForAppStorePanel;
    id <YTInceptionControllerProtocol> _inceptionController;
    YTICommand *_watchBreakTriggeredCommand;
    _Bool _isWatchBreakActive;
    NSError *_deferredUnplayableError;
    YTICommand *_adWatchNextOnUiReadyCommand;
    _Bool _pausedBeforePlayback;
    id <YTResponder> _parentResponder;
    GIMMe *_gimme;
    id <YTWatchControllerDelegate> _watchControllerDelegate;
    id <YTServices> _services;
    id <YTPlayerServices> _playerServices;
    id <YTShareServices> _shareServices;
    id <MDXServices> _MDXServices;
    YTInnerTubeControllerFactory *_innerTubeControllerFactory;
    YTPlayerViewController *_playerViewController;
    YTWatchNextViewController *_watchNextViewController;
    YTWatchNextResultsViewController *_descriptionDetailsViewController;
    unsigned long long _watchPlaylistEndpointRequestID;
    YTShareEndpointController *_shareEndpointController;
    YTICommand *_watchTransitionNavigationEndpoint;
    YTICommand *_shareEndpoint;
    YTICommand *_sharePrivateEndpoint;
    id <YTInfoCardContainerProtocol> _watchNextInfoCardContainer;
    id <YTLiveChatContainerProtocol> _watchNextLiveChatContainer;
    NSMutableDictionary *_inlinedTransitions;
}

@property(retain, nonatomic) NSMutableDictionary *inlinedTransitions; // @synthesize inlinedTransitions=_inlinedTransitions;
@property(readonly, nonatomic) id <YTLiveChatContainerProtocol> watchNextLiveChatContainer; // @synthesize watchNextLiveChatContainer=_watchNextLiveChatContainer;
@property(readonly, nonatomic) id <YTInfoCardContainerProtocol> watchNextInfoCardContainer; // @synthesize watchNextInfoCardContainer=_watchNextInfoCardContainer;
@property(retain, nonatomic) YTICommand *sharePrivateEndpoint; // @synthesize sharePrivateEndpoint=_sharePrivateEndpoint;
@property(retain, nonatomic) YTICommand *shareEndpoint; // @synthesize shareEndpoint=_shareEndpoint;
@property(retain, nonatomic) YTICommand *watchTransitionNavigationEndpoint; // @synthesize watchTransitionNavigationEndpoint=_watchTransitionNavigationEndpoint;
@property(retain, nonatomic) YTShareEndpointController *shareEndpointController; // @synthesize shareEndpointController=_shareEndpointController;
@property(readonly, nonatomic) unsigned long long watchPlaylistEndpointRequestID; // @synthesize watchPlaylistEndpointRequestID=_watchPlaylistEndpointRequestID;
@property(retain, nonatomic) YTWatchNextResultsViewController *descriptionDetailsViewController; // @synthesize descriptionDetailsViewController=_descriptionDetailsViewController;
@property(readonly, nonatomic) YTWatchNextViewController *watchNextViewController; // @synthesize watchNextViewController=_watchNextViewController;
@property(readonly, nonatomic) YTPlayerViewController *playerViewController; // @synthesize playerViewController=_playerViewController;
@property(readonly, nonatomic) YTInnerTubeControllerFactory *innerTubeControllerFactory; // @synthesize innerTubeControllerFactory=_innerTubeControllerFactory;
@property(readonly, nonatomic) __weak id <MDXServices> MDXServices; // @synthesize MDXServices=_MDXServices;
@property(readonly, nonatomic) __weak id <YTShareServices> shareServices; // @synthesize shareServices=_shareServices;
@property(readonly, nonatomic) __weak id <YTPlayerServices> playerServices; // @synthesize playerServices=_playerServices;
@property(readonly, nonatomic) __weak id <YTServices> services; // @synthesize services=_services;
@property(nonatomic, getter=isPausedBeforePlayback) _Bool pausedBeforePlayback; // @synthesize pausedBeforePlayback=_pausedBeforePlayback;
@property(nonatomic) __weak id <YTWatchControllerDelegate> watchControllerDelegate; // @synthesize watchControllerDelegate=_watchControllerDelegate;
@property(nonatomic) __weak GIMMe *gimme; // @synthesize gimme=_gimme;
@property(readonly, nonatomic) __weak id <YTResponder> parentResponder; // @synthesize parentResponder=_parentResponder;
- (void).cxx_destruct;
- (void)displayFirstMealbarInPlayerResponse:(id)arg1 withTriggerCondition:(int)arg2;
- (id)navigationEndpoint;
- (_Bool)isCompanionAdLoaded;
- (void)loadCompanionAd:(id)arg1;
- (void)setAdWatchNextResponse:(id)arg1;
- (id)contentPlayerOverlay;
- (_Bool)ignoreStateChangeForWatchBreak;
- (_Bool)isInlinePlayback;
- (void)expandWatchIfRequired;
- (_Bool)isPresentingAppStorePanel;
- (_Bool)handleAppStorePanelDismiss:(CDUnknownBlockType)arg1;
- (_Bool)handleShowAppStorePanelCommand:(id)arg1;
- (void)dismissAppStorePanelIfNeeded;
- (void)setPlayerViewController:(id)arg1;
- (_Bool)handleCommandResponderEvent:(id)arg1;
- (void)handleWatchNavigationEndpointResponderEvent:(id)arg1;
- (_Bool)handleNavigationEndpointResponderEvent:(id)arg1;
- (void)notifyOfflineabilityObserversDidChange;
- (void)loadWatchNextInfoCardControllers;
- (id)getPlayerResponseAppInfoCard;
- (void)loadCompanionFromPlayerResponse;
- (_Bool)handleOfflineButtonEvent:(id)arg1;
- (void)notifySpeedyGObservers;
- (void)maybeCreateAndSetYouThereControllerWithPlayerResponse:(id)arg1;
- (void)maybeAutoplay;
- (id)watchNextServiceForNavEndpoint:(id)arg1;
- (void)createWatchNextViewControllerIfNeeded;
- (void)destroyWatchNextViewController;
- (void)claimPlayerViewController;
- (_Bool)isMDXActive;
- (void)removeCompanionAd;
- (void)resetPlayerViewControllerStartPlayback:(_Bool)arg1 latencyLogger:(id)arg2;
- (void)updatePlayerControllerControls;
- (id)CSN;
- (void)setWatchFlowController:(id)arg1;
- (void)prepareWithWatchNextResponse:(id)arg1;
- (id)currentMediaTimeEndpoint;
- (id)resign;
- (void)applyWatchTransition:(id)arg1 startPlayback:(_Bool)arg2;
- (_Bool)shouldExitFullScreenOnFinish;
- (void)fetchWatchNextForWatchTransition:(id)arg1 startPlayback:(_Bool)arg2;
- (void)prepareForWatchTransition:(id)arg1 expectedLayout:(id)arg2 startPlayback:(_Bool)arg3;
- (void)prepareForWatchTransition:(id)arg1 startPlayback:(_Bool)arg2;
- (void)startLatencyTickLoggerForTransition:(id)arg1;
- (void)offlineModeDidChange;
- (void)shareSheetExitedFullScreen;
- (void)shareSheetEnteredFullScreen;
- (void)exitFullScreenIfRequired;
- (id)currentCSN;
- (void)youThereControllerDidTransitionFromState:(long long)arg1 toState:(long long)arg2;
- (void)watchBreakFrequencyDidChange;
- (void)showWatchBreak;
- (_Bool)isPlaybackVideoPlayingAd;
- (_Bool)isPlaybackVideoPlaying;
- (double)contentVideoMediaTime;
- (void)removePlaybackEventsObserver:(id)arg1;
- (void)addPlaybackEventsObserver:(id)arg1;
- (void)addOfflineabilityChangeObserver:(id)arg1;
- (void)addSpeedyGObserver:(id)arg1;
- (_Bool)playlistShuffleEnabledOnLoad;
- (void)setAutoplay:(id)arg1 autonav:(id)arg2 playlistPanel:(id)arg3 playlistUIDelegate:(id)arg4 infoCardContainer:(id)arg5 liveChatContainer:(id)arg6 watchNextResults:(id)arg7 descriptionDetails:(id)arg8 currentEndpoint:(id)arg9 videoReportingRenderers:(id)arg10 addToMenuRenderer:(id)arg11 shareEndpoint:(id)arg12 surveyRenderer:(id)arg13 watchNextResponse:(id)arg14;
- (_Bool)isExternalCompanionShelfAllowed;
- (void)willCollapseEngagementPanelForPanelIdentifier:(id)arg1;
- (void)willCollapseEngagementPanelsNavigationView;
- (void)willPresentEngagementPanelRootNavigationView;
- (id)activeVideoReportingRenderer;
- (_Bool)isShowingLiveChat;
- (void)showLiveChat:(_Bool)arg1;
- (void)showAddToMenuFromView:(id)arg1;
- (void)adDidComplete:(long long)arg1;
- (void)hideWatch;
- (void)showSmallScreen;
- (void)showFullScreen;
- (void)playbackControllerExternalPlaybackActiveStateDidChange:(_Bool)arg1;
- (void)playbackControllerVRStateDidChange:(_Bool)arg1;
- (void)playbackControllerDidPressPause;
- (void)playbackControllerDidPressReplay;
- (void)playbackControllerDidPressPlay;
- (void)playbackRouteDidChange;
- (void)playbackControllerCurrentVideoAspectRatioDidChange:(double)arg1;
- (void)playbackControllerDidPressCopyDebugInfo;
- (void)playbackControllerDidFinishPlayingAd;
- (void)playbackControllerDidReceivePlayerResponse:(id)arg1;
- (void)playbackControllerDidFailWithError:(id)arg1;
- (void)playbackControllerWillFailWithError:(id)arg1;
- (void)playbackControllerPlayerStateDidChange;
- (void)playbackControllerDidLoadPlayerWithPlaybackData:(id)arg1;
- (void)playbackControllerDidPause;
- (void)playbackControllerDidPlay;
- (void)playbackControllerStateDidChange;
- (void)playbackControllerDidFinishPlayback;
- (void)playbackControllerCurrentVideoMediaTimeDidChange:(double)arg1;
- (id)playbackDebugData;
- (void)didDeleteOfflineVideoWithID:(id)arg1 pinTypes:(int)arg2;
- (void)didDeleteAllOfflineVideos;
- (_Bool)isActiveVideoPlayable;
- (unsigned long long)activeVideoIndex;
- (id)activePlaylistID;
- (double)activeVideoMediaTime;
- (id)activeVideoID;
@property(readonly, nonatomic) UIView *descriptionDetailsView;
@property(readonly, nonatomic) UIView *playerView;
@property(readonly, nonatomic) UIView *watchNextView;
- (_Bool)shouldReloadVideoForWatchTransition:(id)arg1;
- (void)handleRemoteControlEvent:(long long)arg1;
- (void)handleChangePlaybackPositionCommand:(id)arg1;
- (void)handleNextTrackCommand:(id)arg1;
- (void)handlePreviousTrackCommand:(id)arg1;
- (void)handlePauseCommand:(id)arg1;
- (void)handlePlayCommand:(id)arg1;
- (void)handleTogglePlayPauseCommand:(id)arg1;
- (void)noopHandler:(id)arg1;
- (void)clearNavEndpoint;
- (void)reloadWatchNextIfNecessary;
- (void)reloadStartPlayback:(_Bool)arg1;
- (void)reload;
- (void)setWatchTransition:(id)arg1 startPlayback:(_Bool)arg2;
- (void)setWatchTransition:(id)arg1;
- (void)prepareForWatchTransition:(id)arg1 expectedLayout:(id)arg2;
- (id)parentCSN;
- (void)dealloc;
- (id)initWithWatchFlowController:(id)arg1 parentResponder:(id)arg2 handleRemoteCommands:(_Bool)arg3;
- (id)initWithWatchFlowController:(id)arg1 parentResponder:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

